# Image-Only CLIP Fine-Tuning: Tuning And Robustness Experiments

This notebook contains the self-contained partial CLIP image-encoder fine-tuning pipeline used for configuration selection and matched-seed robustness evaluation.

Completed workflow:
1. verified CSV split loading and image-path remapping on matched seeds
2. ran a one-seed parameter search over several trial configurations
3. selected the best setup using **validation macro-F1** only
4. compared the top two configurations on additional matched seeds
5. reran the selected configuration cleanly on the default seed
6. ran the final selected configuration on all 30 matched seeds

Primary output roots:
- `experiments/imageonly_clip_finetuned_pilot/`
- `experiments/imageonly_clip_finetuned_robustness/`

In [1]:
from pathlib import Path
from urllib.parse import unquote
import json
import os
import random
import time
import warnings

import clip
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from PIL import Image
from sklearn.metrics import f1_score, precision_score, recall_score
from sklearn.utils.class_weight import compute_class_weight
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

warnings.filterwarnings("ignore")

_walk = Path.cwd().resolve()
for _ in range(10):
    if (_walk / "experiments").is_dir() and (_walk / "data").is_dir():
        PROJECT_ROOT = _walk
        break
    _walk = _walk.parent
else:
    PROJECT_ROOT = Path.cwd().resolve()

BASE_DIR = PROJECT_ROOT
SPLITS_ROOT = PROJECT_ROOT / "data" / "splits"
DATASET_CSV = PROJECT_ROOT / "data" / "processed" / "caption_dataset_final_full.csv"
OUTPUT_ROOT = PROJECT_ROOT / "experiments" / "imageonly_clip_finetuned_pilot"
METRICS_DIR = OUTPUT_ROOT / "metrics"
ARTIFACTS_DIR = OUTPUT_ROOT / "artifacts"
(METRICS_DIR / "trials").mkdir(parents=True, exist_ok=True)
(METRICS_DIR / "experiments").mkdir(parents=True, exist_ok=True)
(ARTIFACTS_DIR / "trial_models").mkdir(parents=True, exist_ok=True)
(ARTIFACTS_DIR / "trial_learning_curves").mkdir(parents=True, exist_ok=True)
(ARTIFACTS_DIR / "models").mkdir(parents=True, exist_ok=True)
(ARTIFACTS_DIR / "learning_curves").mkdir(parents=True, exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
MODEL_INIT_SEED = 42
DEFAULT_SEED = 13
DEBUG_SAMPLES = 5
NUM_WORKERS = 2
CLIP_MODEL_NAME = "ViT-B/32"

TRIAL_CONFIGS = [
    {
        "name": "trial_a_blocks2",
        "clip_model": CLIP_MODEL_NAME,
        "batch_size": 32,
        "max_epochs": 15,
        "patience": 4,
        "dropout": 0.5,
        "weight_decay": 1e-4,
        "head_lr": 5e-5,
        "clip_lr": 1e-5,
        "unfreeze_visual_blocks": 2,
    },
    {
        "name": "trial_b_blocks1",
        "clip_model": CLIP_MODEL_NAME,
        "batch_size": 32,
        "max_epochs": 15,
        "patience": 4,
        "dropout": 0.5,
        "weight_decay": 1e-4,
        "head_lr": 5e-5,
        "clip_lr": 5e-6,
        "unfreeze_visual_blocks": 1,
    },
    {
        "name": "trial_c_more_head_lr",
        "clip_model": CLIP_MODEL_NAME,
        "batch_size": 32,
        "max_epochs": 15,
        "patience": 4,
        "dropout": 0.4,
        "weight_decay": 1e-4,
        "head_lr": 1e-4,
        "clip_lr": 1e-5,
        "unfreeze_visual_blocks": 2,
    },
    {
        "name": "trial_d_blocks2_lower_clip_lr",
        "clip_model": CLIP_MODEL_NAME,
        "batch_size": 32,
        "max_epochs": 15,
        "patience": 4,
        "dropout": 0.5,
        "weight_decay": 1e-4,
        "head_lr": 1e-4,
        "clip_lr": 2e-6,
        "unfreeze_visual_blocks": 2,
    },
    {
        "name": "trial_e_blocks4_low_lr",
        "clip_model": CLIP_MODEL_NAME,
        "batch_size": 32,
        "max_epochs": 15,
        "patience": 4,
        "dropout": 0.5,
        "weight_decay": 1e-4,
        "head_lr": 1e-4,
        "clip_lr": 2e-6,
        "unfreeze_visual_blocks": 4,
    },
]

print("PROJECT_ROOT:", PROJECT_ROOT)
print("SPLITS_ROOT:", SPLITS_ROOT)
print("DATASET_CSV:", DATASET_CSV)
print("OUTPUT_ROOT:", OUTPUT_ROOT)
print("DEVICE:", DEVICE)
print("Trial configs:")
for cfg in TRIAL_CONFIGS:
    print(" ", cfg)

/home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

PROJECT_ROOT: /home/ding-zhang/Dongmei/DATA255/Project
SPLITS_ROOT: /home/ding-zhang/Dongmei/DATA255/Project/data/splits
DATASET_CSV: /home/ding-zhang/Dongmei/DATA255/Project/data/processed/caption_dataset_final_full.csv
OUTPUT_ROOT: /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot
DEVICE: cuda
Trial configs:
  {'name': 'trial_a_blocks2', 'clip_model': 'ViT-B/32', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'head_lr': 5e-05, 'clip_lr': 1e-05, 'unfreeze_visual_blocks': 2}
  {'name': 'trial_b_blocks1', 'clip_model': 'ViT-B/32', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'head_lr': 5e-05, 'clip_lr': 5e-06, 'unfreeze_visual_blocks': 1}
  {'name': 'trial_c_more_head_lr', 'clip_model': 'ViT-B/32', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.4, 'weight_decay': 0.0001, 'head_lr': 0.0001, 'clip_lr': 1e-05, 'unfreeze_visual_blocks': 2}
  {'name': 'trial_d_blocks2_lower_clip_lr', 'clip_model': 'ViT-B/32', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'head_lr': 0.0001, 'clip_lr': 2e-06, 'unfreeze_visual_blocks': 2}
  {'name': 'trial_e_blocks4_low_lr', 'clip_model': 'ViT-B/32', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'head_lr': 0.0001, 'clip_lr': 2e-06, 'unfreeze_visual_blocks': 4}

## 1. Load Metadata, Split CSVs, And Verify Image Paths

This section loads shared metadata and performs initial path-resolution checks before training:
- load style metadata
- load a selected seed from `data/splits/seed_<seed>/`
- verify that `dataset/...` paths remap into `data/raw dataset/...`
- confirm that sample images exist before launching training runs

In [2]:
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_style_metadata(dataset_csv):
    df = pd.read_csv(dataset_csv)
    df = df[df["status"] == "success"].copy()
    df["style"] = df["style"].str.strip()
    all_styles = sorted(df["style"].unique())
    style_to_idx = {style: idx for idx, style in enumerate(all_styles)}
    return all_styles, style_to_idx, len(all_styles)


def load_split_csvs(seed):
    split_dir = SPLITS_ROOT / f"seed_{seed}"
    train_df = pd.read_csv(split_dir / "train.csv")
    val_df = pd.read_csv(split_dir / "val.csv")
    test_df = pd.read_csv(split_dir / "test.csv")
    return split_dir, train_df, val_df, test_df


def resolve_image_path(image_path, base_dir):
    image_path = str(image_path)
    if not os.path.isabs(image_path):
        rel_path = image_path.replace("\\", "/")
        dataset_root = base_dir / "dataset"
        if rel_path.startswith("dataset/") and not dataset_root.is_dir():
            image_path = str(base_dir / "data" / "raw dataset" / rel_path[len("dataset/"):])
        else:
            image_path = str(base_dir / image_path)

    if "%" in image_path:
        parts = image_path.split("/")
        image_path = "/".join(unquote(part) if "%" in part else part for part in parts)

    return os.path.normpath(image_path)


def debug_path_resolution(df, base_dir=BASE_DIR, sample_count=DEBUG_SAMPLES):
    print("=== Path resolution sanity check ===")
    print("BASE_DIR:", base_dir)
    print("Top-level dataset/ exists:", (base_dir / "dataset").is_dir())
    print("data/raw dataset/ exists:", (base_dir / "data" / "raw dataset").is_dir())

    checked = 0
    found = 0
    for _, row in df.head(sample_count).iterrows():
        raw_path = row["image_path"]
        resolved_path = resolve_image_path(raw_path, base_dir)
        exists = os.path.isfile(resolved_path)
        found += int(exists)
        checked += 1
        print(f"  exists={exists} raw={raw_path}")
        print(f"         resolved={resolved_path}")

    print(f"Resolved files found: {found}/{checked}")
    if found != checked:
        raise RuntimeError("Some pilot image paths did not resolve correctly.")


all_styles, style_to_idx, num_classes = load_style_metadata(DATASET_CSV)
split_dir, train_df, val_df, test_df = load_split_csvs(DEFAULT_SEED)

print("Loaded seed:", DEFAULT_SEED)
print("Split dir:", split_dir)
print("Split sizes:", len(train_df), len(val_df), len(test_df))
print("Classes:", num_classes)
debug_path_resolution(train_df)

Loaded seed: 13
Split dir: /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Split sizes: 9261 1984 1985
Classes: 14
=== Path resolution sanity check ===
BASE_DIR: /home/ding-zhang/Dongmei/DATA255/Project
Top-level dataset/ exists: False
data/raw dataset/ exists: True
  exists=True raw=dataset/mode/9234303ea1b3437acd91437fb29df533.jpg
         resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/9234303ea1b3437acd91437fb29df533.jpg
  exists=True raw=dataset/conservative/deec85adc5c257cecbecd14ad2c6241999eb1fc4.jpg
         resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/conservative/deec85adc5c257cecbecd14ad2c6241999eb1fc4.jpg
  exists=True raw=dataset/retro/a8a3be106a52c363efff4aad6bd427c0.jpg
         resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/a8a3be106a52c363efff4aad6bd427c0.jpg
  exists=True raw=dataset/conservative/m_93b41ab3faace1063459db9e7bab6137bf3d7dca1449738231.jpg
         resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/conservative/m_93b41ab3faace1063459db9e7bab6137bf3d7dca1449738231.jpg
  exists=True raw=dataset/ethnic/20140328180630283_276.jpg
         resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/ethnic/20140328180630283_276.jpg
Resolved files found: 5/5

## 2. Dataset, Model, And Training Helpers

This section defines the reusable components for the fine-tuned CLIP image-only experiments:
- dataset loading and image-path resolution
- partial CLIP visual encoder unfreezing
- optimizer parameter groups for `clip_lr` and `head_lr`
- training, validation, and per-class metric computation
- deterministic DataLoader seeding and prediction saving
- a single-trial runner for one matched seed

In [3]:
class FashionImageOnlyDataset(Dataset):
    def __init__(self, df, style_to_idx, transform=None, base_dir=None):
        self.df = df.reset_index(drop=True)
        self.style_to_idx = style_to_idx
        self.transform = transform
        self.base_dir = Path(base_dir) if base_dir is not None else None
        self.valid_indices = []
        self.missing_examples = []

        for idx in range(len(self.df)):
            row = self.df.iloc[idx]
            resolved_path = resolve_image_path(row["image_path"], self.base_dir or PROJECT_ROOT)
            if os.path.exists(resolved_path):
                self.valid_indices.append(idx)
            elif len(self.missing_examples) < 5:
                self.missing_examples.append((str(row["image_path"]), resolved_path))

        print(f"Dataset initialized with {len(self.valid_indices)} valid samples (out of {len(self.df)})")
        if self.missing_examples:
            print("  Missing image examples:")
            for raw_path, resolved_path in self.missing_examples:
                print(f"    raw={raw_path}")
                print(f"    resolved={resolved_path}")

    def __len__(self):
        return len(self.valid_indices)

    def __getitem__(self, idx):
        actual_idx = self.valid_indices[idx]
        row = self.df.iloc[actual_idx]
        image_path = resolve_image_path(row["image_path"], self.base_dir or PROJECT_ROOT)
        image = Image.open(image_path).convert("RGB")
        if self.transform:
            image = self.transform(image)
        style = row["style"]
        label = self.style_to_idx[style]
        return {
            "image": image,
            "label": label,
            "style": style,
            "image_path": image_path,
        }


class ImageOnlyFashionClassifier(nn.Module):
    def __init__(self, clip_model, num_classes, dropout=0.5, visual_dim=512):
        super().__init__()
        self.clip_model = clip_model
        self.classifier = nn.Sequential(
            nn.Linear(visual_dim, 256),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, num_classes),
        )

    def forward(self, images):
        visual_features = self.clip_model.encode_image(images).float()
        return self.classifier(visual_features)


def configure_partial_visual_finetuning(model, unfreeze_visual_blocks):
    for param in model.clip_model.parameters():
        param.requires_grad = False

    visual = model.clip_model.visual
    trainable_names = []

    if hasattr(visual, "transformer") and hasattr(visual.transformer, "resblocks"):
        blocks = list(visual.transformer.resblocks)
        unfreeze_visual_blocks = max(0, min(unfreeze_visual_blocks, len(blocks)))
        for block_idx in range(len(blocks) - unfreeze_visual_blocks, len(blocks)):
            if block_idx < 0:
                continue
            for name, param in blocks[block_idx].named_parameters():
                param.requires_grad = True
                trainable_names.append(f"clip_model.visual.transformer.resblocks.{block_idx}.{name}")

    if hasattr(visual, "ln_post"):
        for name, param in visual.ln_post.named_parameters():
            param.requires_grad = True
            trainable_names.append(f"clip_model.visual.ln_post.{name}")

    if hasattr(visual, "proj") and isinstance(visual.proj, torch.nn.Parameter):
        visual.proj.requires_grad = True
        trainable_names.append("clip_model.visual.proj")

    for name, param in model.classifier.named_parameters():
        param.requires_grad = True
        trainable_names.append(f"classifier.{name}")

    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    return {
        "trainable_parameter_names": trainable_names,
        "trainable_parameter_count": int(trainable_params),
        "total_parameter_count": int(total_params),
        "unfrozen_visual_blocks": int(unfreeze_visual_blocks),
    }


def build_optimizer(model, clip_lr, head_lr, weight_decay):
    clip_params = []
    head_params = []
    for name, param in model.named_parameters():
        if not param.requires_grad:
            continue
        if name.startswith("clip_model.visual"):
            clip_params.append(param)
        else:
            head_params.append(param)

    param_groups = []
    if clip_params:
        param_groups.append({"params": clip_params, "lr": clip_lr, "name": "clip"})
    if head_params:
        param_groups.append({"params": head_params, "lr": head_lr, "name": "head"})
    return torch.optim.AdamW(param_groups, weight_decay=weight_decay)


def train_epoch(model, data_loader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    correct = 0
    total = 0
    for batch in tqdm(data_loader, desc="Training", leave=False):
        images = batch["image"].to(device)
        labels = batch["label"].to(device)
        optimizer.zero_grad(set_to_none=True)
        logits = model(images)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
        _, predicted = torch.max(logits.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
    return total_loss / len(data_loader), 100.0 * correct / total


def validate_epoch(model, data_loader, criterion, device):
    model.eval()
    total_loss = 0.0
    correct = 0
    total = 0
    all_predictions = []
    all_labels = []
    with torch.no_grad():
        for batch in tqdm(data_loader, desc="Validation", leave=False):
            images = batch["image"].to(device)
            labels = batch["label"].to(device)
            logits = model(images)
            loss = criterion(logits, labels)
            total_loss += loss.item()
            _, predicted = torch.max(logits.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            all_predictions.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    macro_f1 = f1_score(all_labels, all_predictions, average="macro", zero_division=0)
    return total_loss / len(data_loader), 100.0 * correct / total, all_predictions, all_labels, macro_f1


def evaluate_with_per_class_metrics(model, data_loader, criterion, device, all_styles):
    model.eval()
    total_loss = 0.0
    correct = 0
    total = 0
    all_predictions = []
    all_labels = []
    all_image_paths = []
    all_style_names = []
    with torch.no_grad():
        for batch in tqdm(data_loader, desc="Evaluating", leave=False):
            images = batch["image"].to(device)
            labels = batch["label"].to(device)
            logits = model(images)
            loss = criterion(logits, labels)
            total_loss += loss.item()
            _, predicted = torch.max(logits.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            all_predictions.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            all_image_paths.extend(list(batch["image_path"]))
            all_style_names.extend(list(batch["style"]))

    accuracy = 100.0 * correct / total
    avg_loss = total_loss / len(data_loader)
    macro_f1 = f1_score(all_labels, all_predictions, average="macro", zero_division=0)
    macro_precision = precision_score(all_labels, all_predictions, average="macro", zero_division=0)
    macro_recall = recall_score(all_labels, all_predictions, average="macro", zero_division=0)
    per_class_f1 = f1_score(all_labels, all_predictions, average=None, zero_division=0)
    per_class_precision = precision_score(all_labels, all_predictions, average=None, zero_division=0)
    per_class_recall = recall_score(all_labels, all_predictions, average=None, zero_division=0)

    per_class_accuracy = []
    labels_np = np.array(all_labels)
    predictions_np = np.array(all_predictions)
    for class_idx in range(len(all_styles)):
        class_mask = labels_np == class_idx
        class_acc = float(np.sum((predictions_np == class_idx) & class_mask) / np.sum(class_mask)) if np.sum(class_mask) > 0 else 0.0
        per_class_accuracy.append(class_acc)

    per_class_f1_dict = {all_styles[i]: float(per_class_f1[i]) for i in range(len(all_styles))}
    per_class_precision_dict = {all_styles[i]: float(per_class_precision[i]) for i in range(len(all_styles))}
    per_class_recall_dict = {all_styles[i]: float(per_class_recall[i]) for i in range(len(all_styles))}
    per_class_accuracy_dict = {all_styles[i]: float(per_class_accuracy[i]) for i in range(len(all_styles))}

    return (
        avg_loss,
        accuracy,
        all_predictions,
        all_labels,
        all_image_paths,
        all_style_names,
        macro_f1,
        macro_precision,
        macro_recall,
        per_class_f1_dict,
        per_class_precision_dict,
        per_class_recall_dict,
        per_class_accuracy_dict,
    )


def save_learning_curves(train_losses, val_losses, train_accs, val_accs, val_macro_f1s, clip_lrs, head_lrs, best_epoch, output_path, seed):
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes[0, 0].plot(train_losses, label="Train Loss", color="blue", linewidth=2)
    axes[0, 0].plot(val_losses, label="Val Loss", color="red", linewidth=2)
    axes[0, 0].axvline(x=best_epoch - 1, color="green", linestyle="--", alpha=0.7)
    axes[0, 0].set_title("Training and Validation Loss")
    axes[0, 0].legend(); axes[0, 0].grid(True, alpha=0.3)

    axes[0, 1].plot(train_accs, label="Train Acc", color="blue", linewidth=2)
    axes[0, 1].plot(val_accs, label="Val Acc", color="red", linewidth=2)
    axes[0, 1].axvline(x=best_epoch - 1, color="green", linestyle="--", alpha=0.7)
    axes[0, 1].set_title("Training and Validation Accuracy")
    axes[0, 1].legend(); axes[0, 1].grid(True, alpha=0.3)

    axes[1, 0].plot(val_macro_f1s, label="Val Macro F1", color="green", linewidth=2)
    axes[1, 0].axvline(x=best_epoch - 1, color="red", linestyle="--", alpha=0.7)
    axes[1, 0].set_title("Validation Macro F1")
    axes[1, 0].legend(); axes[1, 0].grid(True, alpha=0.3)

    axes[1, 1].plot(head_lrs, label="Head LR", color="purple", linewidth=2)
    if clip_lrs:
        axes[1, 1].plot(clip_lrs, label="CLIP LR", color="orange", linewidth=2)
    axes[1, 1].set_title("Learning Rates")
    axes[1, 1].legend(); axes[1, 1].grid(True, alpha=0.3)

    plt.suptitle(f"Image-only CLIP fine-tune pilot: seed {seed}", fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close()


def run_finetune_trial(config, seed=DEFAULT_SEED, save_as_seed_result=False):
    set_seed(MODEL_INIT_SEED)
    split_dir, train_df, val_df, test_df = load_split_csvs(seed)

    clip_model, clip_preprocess = clip.load(config.get("clip_model", CLIP_MODEL_NAME), device=DEVICE, jit=False)
    clip_model = clip_model.float()
    model = ImageOnlyFashionClassifier(
        clip_model=clip_model,
        num_classes=num_classes,
        dropout=config["dropout"],
        visual_dim=int(getattr(clip_model.visual, "output_dim", 512)),
    ).to(DEVICE)

    trainable_info = configure_partial_visual_finetuning(model, config["unfreeze_visual_blocks"])
    print("\n=== Trainable parameter summary ===")
    print("Trial:", config["name"])
    print("Unfrozen visual blocks:", trainable_info["unfrozen_visual_blocks"])
    print("Trainable parameters:", trainable_info["trainable_parameter_count"])
    for name in trainable_info["trainable_parameter_names"][:20]:
        print("  ", name)
    if len(trainable_info["trainable_parameter_names"]) > 20:
        print("  ...")

    train_dataset = FashionImageOnlyDataset(train_df, style_to_idx, clip_preprocess, base_dir=BASE_DIR)
    val_dataset = FashionImageOnlyDataset(val_df, style_to_idx, clip_preprocess, base_dir=BASE_DIR)
    test_dataset = FashionImageOnlyDataset(test_df, style_to_idx, clip_preprocess, base_dir=BASE_DIR)

    worker_seed_base = MODEL_INIT_SEED + seed

    def seed_worker(worker_id):
        worker_seed = worker_seed_base + worker_id
        np.random.seed(worker_seed)
        random.seed(worker_seed)

    g = torch.Generator()
    g.manual_seed(worker_seed_base)

    train_loader = DataLoader(
        train_dataset,
        batch_size=config["batch_size"],
        shuffle=True,
        num_workers=NUM_WORKERS,
        worker_init_fn=seed_worker,
        generator=g,
    )
    val_loader = DataLoader(val_dataset, batch_size=config["batch_size"], shuffle=False, num_workers=NUM_WORKERS)
    test_loader = DataLoader(test_dataset, batch_size=config["batch_size"], shuffle=False, num_workers=NUM_WORKERS)

    train_valid_df = train_dataset.df.iloc[train_dataset.valid_indices]
    class_weights = compute_class_weight(
        class_weight="balanced",
        classes=np.array(list(style_to_idx.values())),
        y=train_valid_df["style"].map(style_to_idx).values,
    )
    class_weights = torch.FloatTensor(class_weights).to(DEVICE)

    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = build_optimizer(model, config["clip_lr"], config["head_lr"], config["weight_decay"])
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config["max_epochs"])

    train_losses, val_losses, train_accs, val_accs, val_macro_f1s = [], [], [], [], []
    clip_lrs, head_lrs = [], []
    best_val_macro_f1 = -1.0
    min_val_loss = float("inf")
    best_epoch = 0
    best_train_loss = None
    best_train_acc = None
    best_val_loss_at_epoch = None
    best_val_acc_at_epoch = None
    patience_counter = 0
    early_stopped = False
    start_time = time.time()

    if save_as_seed_result:
        model_path = ARTIFACTS_DIR / "models" / f"seed_{seed}_best_model.pth"
        curve_path = ARTIFACTS_DIR / "learning_curves" / f"seed_{seed}_learning_curves.png"
        result_path = METRICS_DIR / "experiments" / f"seed_{seed}_results.json"
    else:
        model_path = ARTIFACTS_DIR / "trial_models" / f"{config['name']}_seed_{seed}.pth"
        curve_path = ARTIFACTS_DIR / "trial_learning_curves" / f"{config['name']}_seed_{seed}.png"
        result_path = METRICS_DIR / "trials" / f"{config['name']}_seed_{seed}.json"

    print(f"\n{'=' * 70}")
    print(f"Running trial {config['name']} on seed {seed}")
    print(f"Loaded CSVs from {split_dir}")
    print(f"Train/Val/Test: {len(train_df)} / {len(val_df)} / {len(test_df)}")
    print(f"{'=' * 70}")

    for epoch in range(config["max_epochs"]):
        train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, DEVICE)
        val_loss, val_acc, _, _, val_macro_f1 = validate_epoch(model, val_loader, criterion, DEVICE)

        current_clip_lr = 0.0
        current_head_lr = 0.0
        for group in optimizer.param_groups:
            if group.get("name") == "clip":
                current_clip_lr = float(group["lr"])
            else:
                current_head_lr = float(group["lr"])

        clip_lrs.append(current_clip_lr)
        head_lrs.append(current_head_lr)
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_accs.append(train_acc)
        val_accs.append(val_acc)
        val_macro_f1s.append(val_macro_f1)

        if val_macro_f1 > best_val_macro_f1:
            best_val_macro_f1 = val_macro_f1
            best_epoch = epoch + 1
            best_train_loss = train_loss
            best_train_acc = train_acc
            best_val_loss_at_epoch = val_loss
            best_val_acc_at_epoch = val_acc
            patience_counter = 0
            torch.save(model.state_dict(), model_path)
        else:
            patience_counter += 1

        if val_loss < min_val_loss:
            min_val_loss = val_loss

        print(
            f"Epoch {epoch + 1}/{config['max_epochs']}: "
            f"train_loss={train_loss:.4f} val_loss={val_loss:.4f} "
            f"val_macro_f1={val_macro_f1:.4f} clip_lr={current_clip_lr:.2e} head_lr={current_head_lr:.2e}"
        )

        scheduler.step()
        if patience_counter >= config["patience"]:
            early_stopped = True
            print(f"Early stopping at epoch {epoch + 1}")
            break

    total_time = time.time() - start_time
    model.load_state_dict(torch.load(model_path, map_location=DEVICE))

    (
        val_loss,
        val_acc,
        val_predictions,
        val_labels,
        val_image_paths,
        val_styles,
        val_macro_f1,
        val_macro_precision,
        val_macro_recall,
        val_per_class_f1,
        val_per_class_precision,
        val_per_class_recall,
        val_per_class_accuracy,
    ) = evaluate_with_per_class_metrics(model, val_loader, criterion, DEVICE, all_styles)

    (
        test_loss,
        test_acc,
        test_predictions,
        test_labels,
        test_image_paths,
        test_styles,
        test_macro_f1,
        test_macro_precision,
        test_macro_recall,
        test_per_class_f1,
        test_per_class_precision,
        test_per_class_recall,
        test_per_class_accuracy,
    ) = evaluate_with_per_class_metrics(model, test_loader, criterion, DEVICE, all_styles)

    recomputed_val_loss_best_checkpoint = float(val_loss)
    recomputed_val_macro_f1_best_checkpoint = float(val_macro_f1)
    val_loss_at_best_epoch = float(best_val_loss_at_epoch) if best_val_loss_at_epoch is not None else recomputed_val_loss_best_checkpoint
    val_accuracy_at_best_epoch = float(best_val_acc_at_epoch) if best_val_acc_at_epoch is not None else float(val_acc)
    final_val_loss = float(val_losses[-1]) if val_losses else recomputed_val_loss_best_checkpoint
    overfitting_detected = final_val_loss > val_loss_at_best_epoch * 1.05

    train_val_gap = float(best_train_loss - val_loss_at_best_epoch) if best_train_loss is not None else 0.0
    save_learning_curves(train_losses, val_losses, train_accs, val_accs, val_macro_f1s, clip_lrs, head_lrs, best_epoch, curve_path, seed)

    results = {
        "experiment_id": f"seed_{seed}",
        "seed_value": seed,
        "seed_index": 1,
        "trial_name": config["name"],
        "model_type": "image_only_clip_finetuned_partial",
        "configuration": {
            **config,
            "model_init_seed": MODEL_INIT_SEED,
            "data_split_seed": seed,
            "split_source": "csv",
        },
        "training_info": {
            "total_epochs": len(train_losses),
            "best_epoch": best_epoch,
            "early_stopped": early_stopped,
            "total_time_minutes": float(total_time / 60.0),
            "trainable_parameter_count": trainable_info["trainable_parameter_count"],
            "train_loss_at_best_epoch": float(best_train_loss) if best_train_loss is not None else None,
            "train_accuracy_at_best_epoch": float(best_train_acc) if best_train_acc is not None else None,
        },
        "validation_metrics": {
            "best_val_macro_f1": float(best_val_macro_f1),
            "best_val_accuracy": float(val_accuracy_at_best_epoch),
            "best_val_macro_precision": float(val_macro_precision),
            "best_val_macro_recall": float(val_macro_recall),
            "val_loss_at_best_epoch": float(val_loss_at_best_epoch),
            "val_accuracy_at_best_epoch": float(val_accuracy_at_best_epoch),
            "recomputed_val_macro_f1_best_checkpoint": float(recomputed_val_macro_f1_best_checkpoint),
            "recomputed_val_loss_best_checkpoint": float(recomputed_val_loss_best_checkpoint),
            "min_val_loss": float(min_val_loss),
            "predictions": [int(x) for x in val_predictions],
            "labels": [int(x) for x in val_labels],
            "image_paths": [str(x) for x in val_image_paths],
            "styles": [str(x) for x in val_styles],
            "per_class_metrics": {
                "f1": val_per_class_f1,
                "precision": val_per_class_precision,
                "recall": val_per_class_recall,
                "accuracy": val_per_class_accuracy,
            },
        },
        "test_metrics": {
            "test_macro_f1": float(test_macro_f1),
            "test_accuracy": float(test_acc),
            "test_macro_precision": float(test_macro_precision),
            "test_macro_recall": float(test_macro_recall),
            "test_loss": float(test_loss),
            "predictions": [int(x) for x in test_predictions],
            "labels": [int(x) for x in test_labels],
            "image_paths": [str(x) for x in test_image_paths],
            "styles": [str(x) for x in test_styles],
            "per_class_metrics": {
                "f1": test_per_class_f1,
                "precision": test_per_class_precision,
                "recall": test_per_class_recall,
                "accuracy": test_per_class_accuracy,
            },
        },
        "overfitting_analysis": {
            "overfitting_detected": overfitting_detected,
            "val_loss_at_best_epoch": float(val_loss_at_best_epoch),
            "min_val_loss": float(min_val_loss),
            "final_val_loss": float(final_val_loss),
            "train_val_gap": float(train_val_gap),
        },
        "training_curves": {
            "train_losses": [float(x) for x in train_losses],
            "val_losses": [float(x) for x in val_losses],
            "train_accs": [float(x) for x in train_accs],
            "val_accs": [float(x) for x in val_accs],
            "val_macro_f1s": [float(x) for x in val_macro_f1s],
            "clip_learning_rates": [float(x) for x in clip_lrs],
            "head_learning_rates": [float(x) for x in head_lrs],
        },
        "data_split_info": {
            "train_size": len(train_df),
            "val_size": len(val_df),
            "test_size": len(test_df),
        },
        "trainable_parameters": trainable_info,
    }

    with open(result_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    print(f"Saved result JSON to {result_path}")
    print(f"Best val macro F1: {results['validation_metrics']['best_val_macro_f1']:.4f}")
    print(f"Test macro F1: {results['test_metrics']['test_macro_f1']:.4f}")
    return results

## 3. One-Seed Parameter Search

This section runs a small set of partial CLIP fine-tuning trials on one matched seed (`DEFAULT_SEED`) and ranks them by validation performance.

Configuration selection is **validation-only**: `BEST_CONFIG` is chosen using validation macro-F1 and validation loss. Test metrics are logged for reference but are not used for model selection.

In [4]:
SEARCH_RESULTS = []
for trial_cfg in TRIAL_CONFIGS:
    result = run_finetune_trial(trial_cfg, seed=DEFAULT_SEED, save_as_seed_result=False)
    SEARCH_RESULTS.append(
        {
            "trial_name": trial_cfg["name"],
            "best_val_macro_f1": result["validation_metrics"]["best_val_macro_f1"],
            "val_loss_at_best_epoch": result["validation_metrics"]["val_loss_at_best_epoch"],
            "min_val_loss": result["validation_metrics"]["min_val_loss"],
            "test_macro_f1": result["test_metrics"]["test_macro_f1"],
            "epochs": result["training_info"]["total_epochs"],
            "clip_lr": trial_cfg["clip_lr"],
            "head_lr": trial_cfg["head_lr"],
            "unfreeze_visual_blocks": trial_cfg["unfreeze_visual_blocks"],
            "dropout": trial_cfg["dropout"],
            "weight_decay": trial_cfg["weight_decay"],
        }
    )

df_search = pd.DataFrame(SEARCH_RESULTS).sort_values(
    ["best_val_macro_f1", "val_loss_at_best_epoch", "epochs"],
    ascending=[False, True, True],
).reset_index(drop=True)

display_cols = [
    "trial_name",
    "best_val_macro_f1",
    "val_loss_at_best_epoch",
    "min_val_loss",
    "epochs",
    "clip_lr",
    "head_lr",
    "unfreeze_visual_blocks",
    "dropout",
    "weight_decay",
]
display(df_search[display_cols])

BEST_CONFIG = next(cfg for cfg in TRIAL_CONFIGS if cfg["name"] == df_search.iloc[0]["trial_name"]).copy()
TOP2_CONFIG_NAMES = df_search.head(2)["trial_name"].tolist()
print("Best config from validation-only search:")
print(BEST_CONFIG)
print("Top 2 configs:", TOP2_CONFIG_NAMES)

=== Trainable parameter summary ===
Trial: trial_a_blocks2
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial trial_a_blocks2 on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.1838 val_loss=1.2499 val_macro_f1=0.6864 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/15: train_loss=1.0637 val_loss=0.6032 val_macro_f1=0.8112 clip_lr=9.89e-06 head_lr=4.95e-05

Epoch 3/15: train_loss=0.6598 val_loss=0.4844 val_macro_f1=0.8394 clip_lr=9.57e-06 head_lr=4.78e-05

Epoch 4/15: train_loss=0.4554 val_loss=0.4727 val_macro_f1=0.8517 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 5/15: train_loss=0.3343 val_loss=0.4961 val_macro_f1=0.8536 clip_lr=8.35e-06 head_lr=4.17e-05

Epoch 6/15: train_loss=0.2440 val_loss=0.5266 val_macro_f1=0.8543 clip_lr=7.50e-06 head_lr=3.75e-05

Epoch 7/15: train_loss=0.1749 val_loss=0.5510 val_macro_f1=0.8627 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 8/15: train_loss=0.1225 val_loss=0.5948 val_macro_f1=0.8539 clip_lr=5.52e-06 head_lr=2.76e-05

Epoch 9/15: train_loss=0.0940 val_loss=0.6146 val_macro_f1=0.8534 clip_lr=4.48e-06 head_lr=2.24e-05

Epoch 10/15: train_loss=0.0725 val_loss=0.6509 val_macro_f1=0.8587 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 11/15: train_loss=0.0557 val_loss=0.6792 val_macro_f1=0.8553 clip_lr=2.50e-06 head_lr=1.25e-05
Early stopping at epoch 11

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_a_blocks2_seed_13.json
Best val macro F1: 0.8627
Test macro F1: 0.8533

=== Trainable parameter summary ===
Trial: trial_b_blocks1
Unfrozen visual blocks: 1
Trainable parameters: 7648654
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_2.weight
   clip_model.visual.transformer.resblocks.11.ln_2.bias
   clip_model.visual.ln_post.weight
   clip_model.visual.ln_post.bias
   clip_model.visual.proj
   classifier.0.weight
   classifier.0.bias
   classifier.3.weight
   classifier.3.bias
   classifier.6.weight
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial trial_b_blocks1 on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.4438 val_loss=1.8910 val_macro_f1=0.4652 clip_lr=5.00e-06 head_lr=5.00e-05

Epoch 2/15: train_loss=1.5093 val_loss=0.8975 val_macro_f1=0.7639 clip_lr=4.95e-06 head_lr=4.95e-05

Epoch 3/15: train_loss=0.9953 val_loss=0.6345 val_macro_f1=0.8058 clip_lr=4.78e-06 head_lr=4.78e-05

Epoch 4/15: train_loss=0.8041 val_loss=0.5468 val_macro_f1=0.8187 clip_lr=4.52e-06 head_lr=4.52e-05

Epoch 5/15: train_loss=0.6910 val_loss=0.5124 val_macro_f1=0.8332 clip_lr=4.17e-06 head_lr=4.17e-05

Epoch 6/15: train_loss=0.6256 val_loss=0.4848 val_macro_f1=0.8341 clip_lr=3.75e-06 head_lr=3.75e-05

Epoch 7/15: train_loss=0.5723 val_loss=0.4615 val_macro_f1=0.8429 clip_lr=3.27e-06 head_lr=3.27e-05

Epoch 8/15: train_loss=0.5268 val_loss=0.4533 val_macro_f1=0.8432 clip_lr=2.76e-06 head_lr=2.76e-05

Epoch 9/15: train_loss=0.4960 val_loss=0.4486 val_macro_f1=0.8457 clip_lr=2.24e-06 head_lr=2.24e-05

Epoch 10/15: train_loss=0.4717 val_loss=0.4417 val_macro_f1=0.8462 clip_lr=1.73e-06 head_lr=1.73e-05

Epoch 11/15: train_loss=0.4478 val_loss=0.4402 val_macro_f1=0.8452 clip_lr=1.25e-06 head_lr=1.25e-05

Epoch 12/15: train_loss=0.4361 val_loss=0.4374 val_macro_f1=0.8487 clip_lr=8.27e-07 head_lr=8.27e-06

Epoch 13/15: train_loss=0.4459 val_loss=0.4401 val_macro_f1=0.8441 clip_lr=4.77e-07 head_lr=4.77e-06

Epoch 14/15: train_loss=0.4290 val_loss=0.4385 val_macro_f1=0.8467 clip_lr=2.16e-07 head_lr=2.16e-06

Epoch 15/15: train_loss=0.4254 val_loss=0.4384 val_macro_f1=0.8461 clip_lr=5.46e-08 head_lr=5.46e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_b_blocks1_seed_13.json
Best val macro F1: 0.8487
Test macro F1: 0.8461

=== Trainable parameter summary ===
Trial: trial_c_more_head_lr
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial trial_c_more_head_lr on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=1.7393 val_loss=0.6710 val_macro_f1=0.7998 clip_lr=1.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=0.6741 val_loss=0.4785 val_macro_f1=0.8341 clip_lr=9.89e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=0.4477 val_loss=0.4482 val_macro_f1=0.8494 clip_lr=9.57e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.3009 val_loss=0.4572 val_macro_f1=0.8562 clip_lr=9.05e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.2161 val_loss=0.4967 val_macro_f1=0.8540 clip_lr=8.35e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.1405 val_loss=0.5443 val_macro_f1=0.8601 clip_lr=7.50e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.0909 val_loss=0.5927 val_macro_f1=0.8580 clip_lr=6.55e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.0541 val_loss=0.6251 val_macro_f1=0.8608 clip_lr=5.52e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.0420 val_loss=0.6499 val_macro_f1=0.8607 clip_lr=4.48e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.0315 val_loss=0.6661 val_macro_f1=0.8619 clip_lr=3.45e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.0206 val_loss=0.6931 val_macro_f1=0.8608 clip_lr=2.50e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.0178 val_loss=0.7029 val_macro_f1=0.8615 clip_lr=1.65e-06 head_lr=1.65e-05

Epoch 13/15: train_loss=0.0167 val_loss=0.7081 val_macro_f1=0.8581 clip_lr=9.55e-07 head_lr=9.55e-06

Epoch 14/15: train_loss=0.0138 val_loss=0.7153 val_macro_f1=0.8611 clip_lr=4.32e-07 head_lr=4.32e-06
Early stopping at epoch 14

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_c_more_head_lr_seed_13.json
Best val macro F1: 0.8619
Test macro F1: 0.8563

=== Trainable parameter summary ===
Trial: trial_d_blocks2_lower_clip_lr
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial trial_d_blocks2_lower_clip_lr on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.2566 val_loss=1.3388 val_macro_f1=0.6429 clip_lr=2.00e-06 head_lr=1.00e-04

Epoch 2/15: train_loss=1.1497 val_loss=0.6770 val_macro_f1=0.7932 clip_lr=1.98e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=0.7982 val_loss=0.5438 val_macro_f1=0.8237 clip_lr=1.91e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.6661 val_loss=0.4961 val_macro_f1=0.8339 clip_lr=1.81e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.5739 val_loss=0.4787 val_macro_f1=0.8357 clip_lr=1.67e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.5220 val_loss=0.4646 val_macro_f1=0.8462 clip_lr=1.50e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.4764 val_loss=0.4535 val_macro_f1=0.8472 clip_lr=1.31e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.4336 val_loss=0.4482 val_macro_f1=0.8506 clip_lr=1.10e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.4050 val_loss=0.4482 val_macro_f1=0.8534 clip_lr=8.95e-07 head_lr=4.48e-05

Epoch 10/15: train_loss=0.3804 val_loss=0.4484 val_macro_f1=0.8565 clip_lr=6.91e-07 head_lr=3.45e-05

Epoch 11/15: train_loss=0.3616 val_loss=0.4489 val_macro_f1=0.8528 clip_lr=5.00e-07 head_lr=2.50e-05

Epoch 12/15: train_loss=0.3493 val_loss=0.4497 val_macro_f1=0.8533 clip_lr=3.31e-07 head_lr=1.65e-05

Epoch 13/15: train_loss=0.3530 val_loss=0.4525 val_macro_f1=0.8542 clip_lr=1.91e-07 head_lr=9.55e-06

Epoch 14/15: train_loss=0.3413 val_loss=0.4516 val_macro_f1=0.8532 clip_lr=8.65e-08 head_lr=4.32e-06
Early stopping at epoch 14

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_d_blocks2_lower_clip_lr_seed_13.json
Best val macro F1: 0.8565
Test macro F1: 0.8443

=== Trainable parameter summary ===
Trial: trial_e_blocks4_low_lr
Unfrozen visual blocks: 4
Trainable parameters: 28912270
   clip_model.visual.transformer.resblocks.8.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.8.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.8.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.8.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.8.ln_1.weight
   clip_model.visual.transformer.resblocks.8.ln_1.bias
   clip_model.visual.transformer.resblocks.8.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.8.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.8.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.8.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.8.ln_2.weight
   clip_model.visual.transformer.resblocks.8.ln_2.bias
   clip_model.visual.transformer.resblocks.9.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.9.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.9.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.9.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.9.ln_1.weight
   clip_model.visual.transformer.resblocks.9.ln_1.bias
   clip_model.visual.transformer.resblocks.9.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.9.mlp.c_fc.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial trial_e_blocks4_low_lr on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.1677 val_loss=1.1534 val_macro_f1=0.6863 clip_lr=2.00e-06 head_lr=1.00e-04

Epoch 2/15: train_loss=1.0025 val_loss=0.6034 val_macro_f1=0.8083 clip_lr=1.98e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=0.6469 val_loss=0.4865 val_macro_f1=0.8370 clip_lr=1.91e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.4882 val_loss=0.4579 val_macro_f1=0.8539 clip_lr=1.81e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.3699 val_loss=0.4645 val_macro_f1=0.8494 clip_lr=1.67e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.3035 val_loss=0.4902 val_macro_f1=0.8497 clip_lr=1.50e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.2446 val_loss=0.4909 val_macro_f1=0.8559 clip_lr=1.31e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.1972 val_loss=0.5135 val_macro_f1=0.8583 clip_lr=1.10e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.1661 val_loss=0.5290 val_macro_f1=0.8568 clip_lr=8.95e-07 head_lr=4.48e-05

Epoch 10/15: train_loss=0.1371 val_loss=0.5362 val_macro_f1=0.8607 clip_lr=6.91e-07 head_lr=3.45e-05

Epoch 11/15: train_loss=0.1201 val_loss=0.5510 val_macro_f1=0.8559 clip_lr=5.00e-07 head_lr=2.50e-05

Epoch 12/15: train_loss=0.1042 val_loss=0.5680 val_macro_f1=0.8559 clip_lr=3.31e-07 head_lr=1.65e-05

Epoch 13/15: train_loss=0.1023 val_loss=0.5755 val_macro_f1=0.8546 clip_lr=1.91e-07 head_lr=9.55e-06

Epoch 14/15: train_loss=0.0977 val_loss=0.5776 val_macro_f1=0.8562 clip_lr=8.65e-08 head_lr=4.32e-06
Early stopping at epoch 14

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_e_blocks4_low_lr_seed_13.json
Best val macro F1: 0.8607
Test macro F1: 0.8518

,trial_name,best_val_macro_f1,val_loss_at_best_epoch,min_val_loss,epochs,clip_lr,head_lr,unfreeze_visual_blocks,dropout,weight_decay
0,trial_a_blocks2,0.862665,0.551011,0.472718,11,0.000010,0.00005,2,0.5,0.0001
1,trial_c_more_head_lr,0.861886,0.666093,0.448189,14,0.000010,0.00010,2,0.4,0.0001
2,trial_e_blocks4_low_lr,0.860674,0.536244,0.457864,14,0.000002,0.00010,4,0.5,0.0001
3,trial_d_blocks2_lower_clip_lr,0.856537,0.448380,0.448153,14,0.000002,0.00010,2,0.5,0.0001
4,trial_b_blocks1,0.848731,0.437365,0.437365,15,0.000005,0.00005,1,0.5,0.0001

Best config from validation-only search:
{'name': 'trial_a_blocks2', 'clip_model': 'ViT-B/32', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'head_lr': 5e-05, 'clip_lr': 1e-05, 'unfreeze_visual_blocks': 2}
Top 2 configs: ['trial_a_blocks2', 'trial_c_more_head_lr']

## 3.5 Shortlist Comparison On Additional Seeds

This section compares the top two trial configurations on four matched seeds (seed 13 plus three additional seeds). Existing seed-13 trial results are reused when available. The final `BEST_CONFIG` is selected from the aggregated validation macro-F1 summary.

In [ ]:
SHORTLIST_CONFIG_NAMES = ["trial_a_blocks2", "trial_c_more_head_lr"]
SHORTLIST_NEW_SEEDS = [14, 17, 53]
SHORTLIST_ALL_SEEDS = [DEFAULT_SEED] + SHORTLIST_NEW_SEEDS  # seed 13 + 3 more

trial_cfg_lookup = {cfg["name"]: cfg for cfg in TRIAL_CONFIGS}
SHORTLIST_CONFIGS = [trial_cfg_lookup[name].copy() for name in SHORTLIST_CONFIG_NAMES]

def load_existing_trial_result(trial_name, seed):
    result_path = METRICS_DIR / "trials" / f"{trial_name}_seed_{seed}.json"
    if result_path.exists():
        with open(result_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return None

SHORTLIST_RUN_RESULTS = []

for trial_cfg in SHORTLIST_CONFIGS:
    for seed in SHORTLIST_ALL_SEEDS:
        existing_result = load_existing_trial_result(trial_cfg["name"], seed)

        if existing_result is not None:
            result = existing_result
            print(f"Reusing existing result: {trial_cfg['name']} seed {seed}")
        else:
            result = run_finetune_trial(trial_cfg, seed=seed, save_as_seed_result=False)

        SHORTLIST_RUN_RESULTS.append(
            {
                "trial_name": trial_cfg["name"],
                "seed": seed,
                "best_val_macro_f1": result["validation_metrics"]["best_val_macro_f1"],
                "val_loss_at_best_epoch": result["validation_metrics"]["val_loss_at_best_epoch"],
                "min_val_loss": result["validation_metrics"]["min_val_loss"],
                "test_macro_f1": result["test_metrics"]["test_macro_f1"],
                "epochs": result["training_info"]["total_epochs"],
                "best_epoch": result["training_info"]["best_epoch"],
                "early_stopped": result["training_info"]["early_stopped"],
                "total_time_minutes": result["training_info"]["total_time_minutes"],
                "clip_lr": trial_cfg["clip_lr"],
                "head_lr": trial_cfg["head_lr"],
                "unfreeze_visual_blocks": trial_cfg["unfreeze_visual_blocks"],
                "dropout": trial_cfg["dropout"],
                "weight_decay": trial_cfg["weight_decay"],
            }
        )

df_shortlist_runs = (
    pd.DataFrame(SHORTLIST_RUN_RESULTS)
    .sort_values(["trial_name", "seed"])
    .reset_index(drop=True)
)

print("\nPer-seed shortlist results:")
display(
    df_shortlist_runs[
        [
            "trial_name",
            "seed",
            "best_val_macro_f1",
            "val_loss_at_best_epoch",
            "test_macro_f1",
            "epochs",
            "best_epoch",
            "early_stopped",
            "total_time_minutes",
            "clip_lr",
            "head_lr",
            "unfreeze_visual_blocks",
        ]
    ]
)

df_shortlist_summary = (
    df_shortlist_runs
    .groupby("trial_name", as_index=False)
    .agg(
        mean_val_macro_f1=("best_val_macro_f1", "mean"),
        std_val_macro_f1=("best_val_macro_f1", "std"),
        mean_val_loss_at_best_epoch=("val_loss_at_best_epoch", "mean"),
        mean_test_macro_f1=("test_macro_f1", "mean"),
        std_test_macro_f1=("test_macro_f1", "std"),
        mean_epochs=("epochs", "mean"),
        mean_best_epoch=("best_epoch", "mean"),
        mean_time_minutes=("total_time_minutes", "mean"),
        clip_lr=("clip_lr", "first"),
        head_lr=("head_lr", "first"),
        unfreeze_visual_blocks=("unfreeze_visual_blocks", "first"),
        dropout=("dropout", "first"),
        weight_decay=("weight_decay", "first"),
    )
)

df_shortlist_summary["std_val_macro_f1"] = df_shortlist_summary["std_val_macro_f1"].fillna(0.0)
df_shortlist_summary["std_test_macro_f1"] = df_shortlist_summary["std_test_macro_f1"].fillna(0.0)

df_shortlist_summary = df_shortlist_summary.sort_values(
    ["mean_val_macro_f1", "std_val_macro_f1", "mean_val_loss_at_best_epoch"],
    ascending=[False, True, True],
).reset_index(drop=True)

print("\nAggregated shortlist summary (selection is validation-only):")
display(
    df_shortlist_summary[
        [
            "trial_name",
            "mean_val_macro_f1",
            "std_val_macro_f1",
            "mean_val_loss_at_best_epoch",
            "mean_test_macro_f1",
            "std_test_macro_f1",
            "mean_epochs",
            "mean_best_epoch",
            "mean_time_minutes",
            "clip_lr",
            "head_lr",
            "unfreeze_visual_blocks",
        ]
    ]
)

BEST_CONFIG = next(
    cfg for cfg in TRIAL_CONFIGS if cfg["name"] == df_shortlist_summary.iloc[0]["trial_name"]
).copy()

print("\nSelected BEST_CONFIG after shortlist:")
print(BEST_CONFIG)
print(f"Section 4 will now rerun this config cleanly on DEFAULT_SEED={DEFAULT_SEED}.")

Reusing existing result: trial_a_blocks2 seed 13

=== Trainable parameter summary ===
Trial: trial_a_blocks2
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9233 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
Dataset initialized with 1982 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg

======================================================================
Running trial trial_a_blocks2 on seed 14
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_14
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.1921 val_loss=1.2509 val_macro_f1=0.7098 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/15: train_loss=1.0485 val_loss=0.6049 val_macro_f1=0.8045 clip_lr=9.89e-06 head_lr=4.95e-05

Epoch 3/15: train_loss=0.6561 val_loss=0.4930 val_macro_f1=0.8271 clip_lr=9.57e-06 head_lr=4.78e-05

Epoch 4/15: train_loss=0.4477 val_loss=0.4511 val_macro_f1=0.8518 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 5/15: train_loss=0.3333 val_loss=0.4594 val_macro_f1=0.8587 clip_lr=8.35e-06 head_lr=4.17e-05

Epoch 6/15: train_loss=0.2370 val_loss=0.4688 val_macro_f1=0.8544 clip_lr=7.50e-06 head_lr=3.75e-05

Epoch 7/15: train_loss=0.1701 val_loss=0.5039 val_macro_f1=0.8623 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 8/15: train_loss=0.1264 val_loss=0.5199 val_macro_f1=0.8629 clip_lr=5.52e-06 head_lr=2.76e-05

Epoch 9/15: train_loss=0.0875 val_loss=0.5708 val_macro_f1=0.8594 clip_lr=4.48e-06 head_lr=2.24e-05

Epoch 10/15: train_loss=0.0690 val_loss=0.5987 val_macro_f1=0.8626 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 11/15: train_loss=0.0594 val_loss=0.6039 val_macro_f1=0.8620 clip_lr=2.50e-06 head_lr=1.25e-05

Epoch 12/15: train_loss=0.0502 val_loss=0.6017 val_macro_f1=0.8645 clip_lr=1.65e-06 head_lr=8.27e-06

Epoch 13/15: train_loss=0.0456 val_loss=0.6137 val_macro_f1=0.8628 clip_lr=9.55e-07 head_lr=4.77e-06

Epoch 14/15: train_loss=0.0408 val_loss=0.6180 val_macro_f1=0.8652 clip_lr=4.32e-07 head_lr=2.16e-06

Epoch 15/15: train_loss=0.0374 val_loss=0.6183 val_macro_f1=0.8628 clip_lr=1.09e-07 head_lr=5.46e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_a_blocks2_seed_14.json
Best val macro F1: 0.8652
Test macro F1: 0.8483

=== Trainable parameter summary ===
Trial: trial_a_blocks2
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial trial_a_blocks2 on seed 17
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_17
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.1953 val_loss=1.2677 val_macro_f1=0.6822 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/15: train_loss=1.0501 val_loss=0.6087 val_macro_f1=0.8022 clip_lr=9.89e-06 head_lr=4.95e-05

Epoch 3/15: train_loss=0.6466 val_loss=0.5348 val_macro_f1=0.8217 clip_lr=9.57e-06 head_lr=4.78e-05

Epoch 4/15: train_loss=0.4295 val_loss=0.4869 val_macro_f1=0.8436 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 5/15: train_loss=0.3073 val_loss=0.5180 val_macro_f1=0.8467 clip_lr=8.35e-06 head_lr=4.17e-05

Epoch 6/15: train_loss=0.2172 val_loss=0.5525 val_macro_f1=0.8513 clip_lr=7.50e-06 head_lr=3.75e-05

Epoch 7/15: train_loss=0.1744 val_loss=0.5797 val_macro_f1=0.8464 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 8/15: train_loss=0.1221 val_loss=0.6128 val_macro_f1=0.8451 clip_lr=5.52e-06 head_lr=2.76e-05

Epoch 9/15: train_loss=0.0886 val_loss=0.6245 val_macro_f1=0.8550 clip_lr=4.48e-06 head_lr=2.24e-05

Epoch 10/15: train_loss=0.0678 val_loss=0.6531 val_macro_f1=0.8507 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 11/15: train_loss=0.0547 val_loss=0.6779 val_macro_f1=0.8468 clip_lr=2.50e-06 head_lr=1.25e-05

Epoch 12/15: train_loss=0.0490 val_loss=0.6763 val_macro_f1=0.8541 clip_lr=1.65e-06 head_lr=8.27e-06

Epoch 13/15: train_loss=0.0431 val_loss=0.6886 val_macro_f1=0.8497 clip_lr=9.55e-07 head_lr=4.77e-06
Early stopping at epoch 13

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_a_blocks2_seed_17.json
Best val macro F1: 0.8550
Test macro F1: 0.8402

=== Trainable parameter summary ===
Trial: trial_a_blocks2
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
Dataset initialized with 1977 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg

======================================================================
Running trial trial_a_blocks2 on seed 53
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_53
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.1852 val_loss=1.2375 val_macro_f1=0.7168 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/15: train_loss=1.0391 val_loss=0.6245 val_macro_f1=0.7875 clip_lr=9.89e-06 head_lr=4.95e-05

Epoch 3/15: train_loss=0.6220 val_loss=0.5246 val_macro_f1=0.8280 clip_lr=9.57e-06 head_lr=4.78e-05

Epoch 4/15: train_loss=0.4399 val_loss=0.5285 val_macro_f1=0.8341 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 5/15: train_loss=0.3117 val_loss=0.5418 val_macro_f1=0.8378 clip_lr=8.35e-06 head_lr=4.17e-05

Epoch 6/15: train_loss=0.2247 val_loss=0.5644 val_macro_f1=0.8398 clip_lr=7.50e-06 head_lr=3.75e-05

Epoch 7/15: train_loss=0.1603 val_loss=0.6189 val_macro_f1=0.8345 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 8/15: train_loss=0.1173 val_loss=0.6534 val_macro_f1=0.8371 clip_lr=5.52e-06 head_lr=2.76e-05

Epoch 9/15: train_loss=0.0946 val_loss=0.7127 val_macro_f1=0.8375 clip_lr=4.48e-06 head_lr=2.24e-05

Epoch 10/15: train_loss=0.0688 val_loss=0.7078 val_macro_f1=0.8440 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 11/15: train_loss=0.0546 val_loss=0.7312 val_macro_f1=0.8366 clip_lr=2.50e-06 head_lr=1.25e-05

Epoch 12/15: train_loss=0.0491 val_loss=0.7343 val_macro_f1=0.8419 clip_lr=1.65e-06 head_lr=8.27e-06

Epoch 13/15: train_loss=0.0405 val_loss=0.7507 val_macro_f1=0.8417 clip_lr=9.55e-07 head_lr=4.77e-06

Epoch 14/15: train_loss=0.0373 val_loss=0.7530 val_macro_f1=0.8428 clip_lr=4.32e-07 head_lr=2.16e-06
Early stopping at epoch 14

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_a_blocks2_seed_53.json
Best val macro F1: 0.8440
Test macro F1: 0.8561
Reusing existing result: trial_c_more_head_lr seed 13

=== Trainable parameter summary ===
Trial: trial_c_more_head_lr
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9233 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
Dataset initialized with 1982 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg

======================================================================
Running trial trial_c_more_head_lr on seed 14
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_14
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=1.7431 val_loss=0.6799 val_macro_f1=0.7796 clip_lr=1.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=0.6732 val_loss=0.5001 val_macro_f1=0.8268 clip_lr=9.89e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=0.4483 val_loss=0.4425 val_macro_f1=0.8477 clip_lr=9.57e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.3006 val_loss=0.4464 val_macro_f1=0.8495 clip_lr=9.05e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.2086 val_loss=0.4766 val_macro_f1=0.8597 clip_lr=8.35e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.1394 val_loss=0.4677 val_macro_f1=0.8644 clip_lr=7.50e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.0840 val_loss=0.5372 val_macro_f1=0.8598 clip_lr=6.55e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.0577 val_loss=0.5515 val_macro_f1=0.8641 clip_lr=5.52e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.0381 val_loss=0.5878 val_macro_f1=0.8611 clip_lr=4.48e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.0288 val_loss=0.5869 val_macro_f1=0.8658 clip_lr=3.45e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.0222 val_loss=0.6117 val_macro_f1=0.8644 clip_lr=2.50e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.0187 val_loss=0.6193 val_macro_f1=0.8624 clip_lr=1.65e-06 head_lr=1.65e-05

Epoch 13/15: train_loss=0.0140 val_loss=0.6320 val_macro_f1=0.8670 clip_lr=9.55e-07 head_lr=9.55e-06

Epoch 14/15: train_loss=0.0145 val_loss=0.6312 val_macro_f1=0.8648 clip_lr=4.32e-07 head_lr=4.32e-06

Epoch 15/15: train_loss=0.0128 val_loss=0.6320 val_macro_f1=0.8653 clip_lr=1.09e-07 head_lr=1.09e-06

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_c_more_head_lr_seed_14.json
Best val macro F1: 0.8670
Test macro F1: 0.8541

=== Trainable parameter summary ===
Trial: trial_c_more_head_lr
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial trial_c_more_head_lr on seed 17
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_17
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=1.7486 val_loss=0.7174 val_macro_f1=0.7800 clip_lr=1.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=0.6696 val_loss=0.5054 val_macro_f1=0.8255 clip_lr=9.89e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=0.4335 val_loss=0.4789 val_macro_f1=0.8444 clip_lr=9.57e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.2898 val_loss=0.4827 val_macro_f1=0.8471 clip_lr=9.05e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.2004 val_loss=0.5232 val_macro_f1=0.8512 clip_lr=8.35e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.1286 val_loss=0.5689 val_macro_f1=0.8535 clip_lr=7.50e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.0926 val_loss=0.5966 val_macro_f1=0.8497 clip_lr=6.55e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.0581 val_loss=0.6403 val_macro_f1=0.8440 clip_lr=5.52e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.0410 val_loss=0.6639 val_macro_f1=0.8500 clip_lr=4.48e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.0290 val_loss=0.6807 val_macro_f1=0.8526 clip_lr=3.45e-06 head_lr=3.45e-05
Early stopping at epoch 10

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_c_more_head_lr_seed_17.json
Best val macro F1: 0.8535
Test macro F1: 0.8445

=== Trainable parameter summary ===
Trial: trial_c_more_head_lr
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
Dataset initialized with 1977 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg

======================================================================
Running trial trial_c_more_head_lr on seed 53
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_53
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=1.7239 val_loss=0.7011 val_macro_f1=0.7765 clip_lr=1.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=0.6573 val_loss=0.5322 val_macro_f1=0.8116 clip_lr=9.89e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=0.4224 val_loss=0.5126 val_macro_f1=0.8285 clip_lr=9.57e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.2817 val_loss=0.5310 val_macro_f1=0.8310 clip_lr=9.05e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.1943 val_loss=0.5613 val_macro_f1=0.8364 clip_lr=8.35e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.1294 val_loss=0.5962 val_macro_f1=0.8388 clip_lr=7.50e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.0817 val_loss=0.6526 val_macro_f1=0.8405 clip_lr=6.55e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.0550 val_loss=0.7282 val_macro_f1=0.8348 clip_lr=5.52e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.0404 val_loss=0.7467 val_macro_f1=0.8406 clip_lr=4.48e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.0251 val_loss=0.7496 val_macro_f1=0.8376 clip_lr=3.45e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.0193 val_loss=0.7756 val_macro_f1=0.8342 clip_lr=2.50e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.0146 val_loss=0.7867 val_macro_f1=0.8415 clip_lr=1.65e-06 head_lr=1.65e-05

Epoch 13/15: train_loss=0.0124 val_loss=0.7896 val_macro_f1=0.8368 clip_lr=9.55e-07 head_lr=9.55e-06

Epoch 14/15: train_loss=0.0103 val_loss=0.7993 val_macro_f1=0.8412 clip_lr=4.32e-07 head_lr=4.32e-06

Epoch 15/15: train_loss=0.0111 val_loss=0.8022 val_macro_f1=0.8423 clip_lr=1.09e-07 head_lr=1.09e-06

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/trials/trial_c_more_head_lr_seed_53.json
Best val macro F1: 0.8423
Test macro F1: 0.8511

Per-seed shortlist results:

,trial_name,seed,best_val_macro_f1,val_loss_at_best_epoch,test_macro_f1,epochs,best_epoch,early_stopped,total_time_minutes,clip_lr,head_lr,unfreeze_visual_blocks
0,trial_a_blocks2,13,0.862665,0.551011,0.853308,11,7,True,1.835367,0.00001,0.00005,2
1,trial_a_blocks2,14,0.865193,0.617986,0.848306,15,14,False,2.536229,0.00001,0.00005,2
2,trial_a_blocks2,17,0.854974,0.624486,0.840151,13,9,True,2.202599,0.00001,0.00005,2
3,trial_a_blocks2,53,0.843979,0.707818,0.856102,14,10,True,2.394369,0.00001,0.00005,2
4,trial_c_more_head_lr,13,0.861886,0.666093,0.856343,14,10,True,2.343153,0.00001,0.00010,2
5,trial_c_more_head_lr,14,0.867044,0.632039,0.854144,15,13,False,2.553466,0.00001,0.00010,2
6,trial_c_more_head_lr,17,0.853495,0.568908,0.844461,10,6,True,1.703112,0.00001,0.00010,2
7,trial_c_more_head_lr,53,0.842333,0.802206,0.851123,15,15,False,2.567267,0.00001,0.00010,2

Aggregated shortlist summary (selection is validation-only):

,trial_name,mean_val_macro_f1,std_val_macro_f1,mean_val_loss_at_best_epoch,mean_test_macro_f1,std_test_macro_f1,mean_epochs,mean_best_epoch,mean_time_minutes,clip_lr,head_lr,unfreeze_visual_blocks
0,trial_a_blocks2,0.856703,0.009531,0.625325,0.849467,0.006998,13.25,10.0,2.242141,0.00001,0.00005,2
1,trial_c_more_head_lr,0.856190,0.010794,0.667312,0.851518,0.005168,13.50,11.0,2.291749,0.00001,0.00010,2

Selected BEST_CONFIG after shortlist:
{'name': 'trial_a_blocks2', 'clip_model': 'ViT-B/32', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'head_lr': 5e-05, 'clip_lr': 1e-05, 'unfreeze_visual_blocks': 2}
Section 4 will now rerun this config cleanly on DEFAULT_SEED=13.

## 4. Clean Rerun Of The Selected Configuration

This section reruns the selected partial CLIP configuration cleanly on the default seed after the search and shortlist stages, producing the final one-seed result before the full 30-seed robustness run.

In [6]:
if "BEST_CONFIG" not in globals():
    BEST_CONFIG = TRIAL_CONFIGS[0].copy()

BEST_CONFIG = BEST_CONFIG.copy()
BEST_CONFIG["name"] = "selected_config"
BEST_CONFIG["max_epochs"] = 20
BEST_CONFIG["patience"] = 5

print("Final config to rerun:")
print(BEST_CONFIG)

final_result = run_finetune_trial(BEST_CONFIG, seed=DEFAULT_SEED, save_as_seed_result=True)

result_path = METRICS_DIR / "experiments" / f"seed_{DEFAULT_SEED}_results.json"
print("\nFinal result JSON:", result_path)
print("Best val macro F1:", final_result["validation_metrics"]["best_val_macro_f1"])
print("Test macro F1:", final_result["test_metrics"]["test_macro_f1"])
print("Trainable params:", final_result["training_info"]["trainable_parameter_count"])

Final config to rerun:
{'name': 'selected_config', 'clip_model': 'ViT-B/32', 'batch_size': 32, 'max_epochs': 20, 'patience': 5, 'dropout': 0.5, 'weight_decay': 0.0001, 'head_lr': 5e-05, 'clip_lr': 1e-05, 'unfreeze_visual_blocks': 2}

=== Trainable parameter summary ===
Trial: selected_config
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial selected_config on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1838 val_loss=1.2499 val_macro_f1=0.6864 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0623 val_loss=0.6007 val_macro_f1=0.8119 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6574 val_loss=0.4845 val_macro_f1=0.8388 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4523 val_loss=0.4727 val_macro_f1=0.8520 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3312 val_loss=0.5011 val_macro_f1=0.8537 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2393 val_loss=0.5337 val_macro_f1=0.8534 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1679 val_loss=0.5578 val_macro_f1=0.8642 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1152 val_loss=0.6167 val_macro_f1=0.8514 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0831 val_loss=0.6532 val_macro_f1=0.8534 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0631 val_loss=0.6799 val_macro_f1=0.8588 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0463 val_loss=0.7391 val_macro_f1=0.8537 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0333 val_loss=0.7707 val_macro_f1=0.8537 clip_lr=4.22e-06 head_lr=2.11e-05
Early stopping at epoch 12

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/experiments/seed_13_results.json
Best val macro F1: 0.8642
Test macro F1: 0.8565

Final result JSON: /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_pilot/metrics/experiments/seed_13_results.json
Best val macro F1: 0.8641769630481492
Test macro F1: 0.8564586192028225
Trainable params: 14736526

## 5. Full 30-Seed Robustness Run

This section runs the final selected partial CLIP configuration across all 30 matched seeds. It saves per-seed JSON results, aggregated summary tables, statistical summaries, learning curves, and comparison plots under `experiments/imageonly_clip_finetuned_robustness/`.

In [8]:
import re

try:
    from scipy import stats as scipy_stats
except Exception:
    scipy_stats = None

if "BEST_CONFIG" not in globals():
    raise RuntimeError("Run section 4 first so BEST_CONFIG is defined.")

if "all_styles" not in globals() or "style_to_idx" not in globals() or "num_classes" not in globals():
    all_styles, style_to_idx, num_classes = load_style_metadata(DATASET_CSV)

ROBUSTNESS_OUTPUT_ROOT = PROJECT_ROOT / "experiments" / "imageonly_clip_finetuned_robustness"
ROBUSTNESS_METRICS_DIR = ROBUSTNESS_OUTPUT_ROOT / "metrics"

# Use root-level folders so the layout is closer to older robustness notebook outputs.
ROBUSTNESS_ARTIFACTS_DIR = ROBUSTNESS_OUTPUT_ROOT
(ROBUSTNESS_METRICS_DIR / "trials").mkdir(parents=True, exist_ok=True)
(ROBUSTNESS_METRICS_DIR / "experiments").mkdir(parents=True, exist_ok=True)
(ROBUSTNESS_ARTIFACTS_DIR / "models").mkdir(parents=True, exist_ok=True)
(ROBUSTNESS_ARTIFACTS_DIR / "learning_curves").mkdir(parents=True, exist_ok=True)
(ROBUSTNESS_ARTIFACTS_DIR / "comparison_plots").mkdir(parents=True, exist_ok=True)

SEEDS_FILE = PROJECT_ROOT / "experiments" / "phase3_robustness" / "metrics" / "seeds_list.txt"

def load_robustness_seeds():
    if SEEDS_FILE.exists():
        text = SEEDS_FILE.read_text(encoding="utf-8")
        seeds = [int(x) for x in re.findall(r"Seed\s+(\d+)", text)]
        if seeds:
            return seeds

    seeds = []
    for p in sorted(SPLITS_ROOT.glob("seed_*")):
        if p.is_dir() and (p / "train.csv").exists() and (p / "val.csv").exists() and (p / "test.csv").exists():
            try:
                seeds.append(int(p.name.split("_")[1]))
            except Exception:
                pass
    return seeds

def calculate_stats(values, name):
    arr = np.array(values, dtype=float)
    mean_val = float(np.mean(arr))
    std_val = float(np.std(arr))
    min_val = float(np.min(arr))
    max_val = float(np.max(arr))
    median_val = float(np.median(arr))
    q25 = float(np.percentile(arr, 25))
    q75 = float(np.percentile(arr, 75))
    cv = float((std_val / mean_val * 100.0) if mean_val != 0 else 0.0)

    if len(arr) > 1 and scipy_stats is not None:
        ci = scipy_stats.t.interval(0.95, len(arr) - 1, loc=mean_val, scale=scipy_stats.sem(arr))
        ci_lower = float(ci[0])
        ci_upper = float(ci[1])
    else:
        ci_lower = mean_val
        ci_upper = mean_val

    return {
        "metric": name,
        "mean": mean_val,
        "std": std_val,
        "min": min_val,
        "max": max_val,
        "median": median_val,
        "q25": q25,
        "q75": q75,
        "cv_percent": cv,
        "ci_95_lower": ci_lower,
        "ci_95_upper": ci_upper,
        "n": int(len(arr)),
    }

def safe_to_excel(df, path):
    try:
        df.to_excel(path, index=False)
        print(f"Saved Excel: {path}")
    except Exception as exc:
        print(f"Could not save Excel file {path}: {exc}")

def fmt_mean_std(mean_val, std_val, digits=4):
    return f"{mean_val:.{digits}f} +/- {std_val:.{digits}f}"

def fmt_ci(stat_obj, digits=4):
    return f"[{stat_obj['ci_95_lower']:.{digits}f}, {stat_obj['ci_95_upper']:.{digits}f}]"

def write_robustness_seeds_list(metrics_dir, seeds):
    path = metrics_dir / "seeds_list.txt"
    with open(path, "w", encoding="utf-8") as f:
        f.write("Fine-tuned image-only robustness seeds\n")
        f.write("=" * 50 + "\n")
        f.write(f"Total seeds: {len(seeds)}\n\n")
        for idx, seed in enumerate(seeds, 1):
            f.write(f"{idx:2d}. Seed {seed}\n")

def build_per_class_tables(all_results, all_styles):
    summary_rows = []
    per_class_stats = {}
    detailed_tables = {
        "f1": [],
        "precision": [],
        "recall": [],
        "accuracy": [],
    }

    for style in all_styles:
        style_metrics = {
            "f1": [],
            "precision": [],
            "recall": [],
            "accuracy": [],
        }

        for result in all_results:
            test_pc = result["test_metrics"].get("per_class_metrics", {})
            if not test_pc:
                continue
            for metric_name in style_metrics:
                metric_dict = test_pc.get(metric_name, {})
                if style in metric_dict:
                    style_metrics[metric_name].append(float(metric_dict[style]))

        if not style_metrics["f1"]:
            continue

        style_stat_block = {
            metric_name: calculate_stats(values, f"{style} - Test {metric_name.title()}")
            for metric_name, values in style_metrics.items()
        }
        per_class_stats[style] = style_stat_block

        summary_rows.append(
            {
                "Style": style,
                "Test_F1_Mean": style_stat_block["f1"]["mean"],
                "Test_F1_Std": style_stat_block["f1"]["std"],
                "Test_Precision_Mean": style_stat_block["precision"]["mean"],
                "Test_Precision_Std": style_stat_block["precision"]["std"],
                "Test_Recall_Mean": style_stat_block["recall"]["mean"],
                "Test_Recall_Std": style_stat_block["recall"]["std"],
                "Test_Accuracy_Mean": style_stat_block["accuracy"]["mean"],
                "Test_Accuracy_Std": style_stat_block["accuracy"]["std"],
            }
        )

        for metric_name in ["f1", "precision", "recall", "accuracy"]:
            stat_obj = style_stat_block[metric_name]
            detailed_tables[metric_name].append(
                {
                    "Style": style,
                    "Mean": stat_obj["mean"],
                    "Std": stat_obj["std"],
                    "Min": stat_obj["min"],
                    "Max": stat_obj["max"],
                    "95% CI Lower": stat_obj["ci_95_lower"],
                    "95% CI Upper": stat_obj["ci_95_upper"],
                    "N": stat_obj["n"],
                }
            )

    df_per_class_summary = pd.DataFrame(summary_rows).sort_values("Style").reset_index(drop=True)
    detailed_tables = {
        metric_name: pd.DataFrame(rows).sort_values("Style").reset_index(drop=True)
        for metric_name, rows in detailed_tables.items()
    }
    return df_per_class_summary, per_class_stats, detailed_tables

In [9]:
def save_robustness_plots(all_results, df_summary, df_per_class_summary):
    if len(all_results) == 0:
        return

    plot_dir = ROBUSTNESS_ARTIFACTS_DIR / "comparison_plots"
    plot_dir.mkdir(parents=True, exist_ok=True)

    results_sorted = sorted(all_results, key=lambda x: x["seed_value"])
    seeds = [r["seed_value"] for r in results_sorted]
    test_f1s = [r["test_metrics"]["test_macro_f1"] for r in results_sorted]
    test_accs = [r["test_metrics"]["test_accuracy"] for r in results_sorted]
    val_f1s = [r["validation_metrics"]["best_val_macro_f1"] for r in results_sorted]
    train_times = [r["training_info"]["total_time_minutes"] for r in results_sorted]

    # 1. Robustness summary plot
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    axes[0, 0].plot(seeds, test_f1s, marker="o", linewidth=2, color="tab:blue")
    axes[0, 0].axhline(np.mean(test_f1s), color="red", linestyle="--", label=f"Mean={np.mean(test_f1s):.4f}")
    axes[0, 0].set_title("Test Macro F1 Across Seeds")
    axes[0, 0].set_xlabel("Seed")
    axes[0, 0].set_ylabel("Macro F1")
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].legend()

    axes[0, 1].plot(seeds, test_accs, marker="o", linewidth=2, color="tab:green")
    axes[0, 1].axhline(np.mean(test_accs), color="red", linestyle="--", label=f"Mean={np.mean(test_accs):.2f}")
    axes[0, 1].set_title("Test Accuracy Across Seeds")
    axes[0, 1].set_xlabel("Seed")
    axes[0, 1].set_ylabel("Accuracy")
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].legend()

    axes[1, 0].boxplot([val_f1s, test_f1s], labels=["Best Val Macro F1", "Test Macro F1"])
    axes[1, 0].set_title("Validation vs Test Macro F1")
    axes[1, 0].grid(True, alpha=0.3)

    axes[1, 1].plot(seeds, train_times, marker="o", linewidth=2, color="tab:purple")
    axes[1, 1].axhline(np.mean(train_times), color="red", linestyle="--", label=f"Mean={np.mean(train_times):.2f} min")
    axes[1, 1].set_title("Training Time Across Seeds")
    axes[1, 1].set_xlabel("Seed")
    axes[1, 1].set_ylabel("Minutes")
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].legend()

    plt.tight_layout()
    robustness_plot_path = plot_dir / "robustness_analysis.png"
    plt.savefig(robustness_plot_path, dpi=300, bbox_inches="tight")
    plt.close()

    # 2. Learning curve overlay (up to first 5 completed seeds)
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    overlay_results = results_sorted[: min(5, len(results_sorted))]

    for result in overlay_results:
        seed = result["seed_value"]
        curves = result.get("training_curves", {})
        val_curve = curves.get("val_macro_f1s", [])
        val_loss_curve = curves.get("val_losses", [])
        if val_curve:
            axes[0].plot(range(1, len(val_curve) + 1), val_curve, linewidth=2, label=f"Seed {seed}")
        if val_loss_curve:
            axes[1].plot(range(1, len(val_loss_curve) + 1), val_loss_curve, linewidth=2, label=f"Seed {seed}")

    axes[0].set_title("Validation Macro F1 Overlay")
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Macro F1")
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()

    axes[1].set_title("Validation Loss Overlay")
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Loss")
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()

    plt.tight_layout()
    overlay_path = plot_dir / "learning_curves_overlay.png"
    plt.savefig(overlay_path, dpi=300, bbox_inches="tight")
    plt.close()

    # 3. Per-class F1 summary plot
    if len(df_per_class_summary) > 0:
        df_plot = df_per_class_summary.sort_values("Test_F1_Mean", ascending=True)

        plt.figure(figsize=(10, max(6, len(df_plot) * 0.45)))
        plt.barh(
            df_plot["Style"],
            df_plot["Test_F1_Mean"],
            xerr=df_plot["Test_F1_Std"],
            color="steelblue",
            alpha=0.85,
            ecolor="black",
            capsize=4,
        )
        plt.xlabel("Test F1 Mean")
        plt.title("Per-Class Test F1 Summary")
        plt.grid(True, axis="x", alpha=0.3)
        plt.tight_layout()

        per_class_plot_path = ROBUSTNESS_OUTPUT_ROOT / "per_class_analysis_summary.png"
        plt.savefig(per_class_plot_path, dpi=300, bbox_inches="tight")
        plt.close()

    

def save_robustness_outputs(all_results, failed_seeds, seeds, metrics_dir, all_styles):
    summary = {
        "total_seeds": len(seeds),
        "successful_experiments": len(all_results),
        "failed_experiments": len(failed_seeds),
        "failed_seeds": failed_seeds,
        "completed_seeds": [result["seed_value"] for result in all_results],
        "experiment_root": str(ROBUSTNESS_OUTPUT_ROOT),
    }
    with open(metrics_dir / "experiments_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    if not all_results:
        return

    summary_rows = []
    for result in all_results:
        validation_metrics = result["validation_metrics"]
        test_metrics = result["test_metrics"]
        overfit_metrics = result["overfitting_analysis"]
        training_info = result["training_info"]

        summary_rows.append(
            {
                "Seed": result["seed_value"],
                "Best_Epoch": training_info["best_epoch"],
                "Early_Stopped": training_info["early_stopped"],
                "Best_Val_Macro_F1": validation_metrics["best_val_macro_f1"],
                "Best_Val_Accuracy": validation_metrics["best_val_accuracy"],
                "Val_Loss_At_Best_Epoch": validation_metrics.get(
                    "val_loss_at_best_epoch",
                    validation_metrics.get("best_val_loss")
                ),
                "Min_Val_Loss": validation_metrics.get(
                    "min_val_loss",
                    validation_metrics.get("best_val_loss")
                ),
                "Test_Macro_F1": test_metrics["test_macro_f1"],
                "Test_Accuracy": test_metrics["test_accuracy"],
                "Test_Macro_Precision": test_metrics["test_macro_precision"],
                "Test_Macro_Recall": test_metrics["test_macro_recall"],
                "Overfitting": overfit_metrics["overfitting_detected"],
                "Training_Time_Min": training_info["total_time_minutes"],
                "Trainable_Params": training_info["trainable_parameter_count"],
            }
        )

    df_summary = pd.DataFrame(summary_rows).sort_values("Seed").reset_index(drop=True)
    df_summary.to_csv(metrics_dir / "summary_table.csv", index=False)
    safe_to_excel(df_summary, metrics_dir / "summary_table.xlsx")

    overall_stats = [
        calculate_stats(df_summary["Test_Macro_F1"].tolist(), "Test Macro F1"),
        calculate_stats(df_summary["Test_Accuracy"].tolist(), "Test Accuracy"),
        calculate_stats(df_summary["Test_Macro_Precision"].tolist(), "Test Macro Precision"),
        calculate_stats(df_summary["Test_Macro_Recall"].tolist(), "Test Macro Recall"),
        calculate_stats(df_summary["Best_Val_Macro_F1"].tolist(), "Best Val Macro F1"),
        calculate_stats(df_summary["Best_Val_Accuracy"].tolist(), "Best Val Accuracy"),
        calculate_stats(df_summary["Val_Loss_At_Best_Epoch"].tolist(), "Val Loss At Best Epoch"),
        calculate_stats(df_summary["Min_Val_Loss"].tolist(), "Min Val Loss"),
        calculate_stats(df_summary["Training_Time_Min"].tolist(), "Training Time (min)"),
    ]

    with open(metrics_dir / "overall_metrics_statistics.json", "w", encoding="utf-8") as f:
        json.dump({"overall_metrics": overall_stats}, f, indent=2)
    pd.DataFrame(overall_stats).to_csv(metrics_dir / "overall_metrics_summary.csv", index=False)

    overfitting_count = int(df_summary["Overfitting"].sum())
    statistical_analysis = {
        "summary_statistics": overall_stats,
        "overfitting_count": overfitting_count,
        "overfitting_percentage": float(100.0 * overfitting_count / len(df_summary)),
        "total_experiments": int(len(df_summary)),
    }
    with open(metrics_dir / "statistical_analysis.json", "w", encoding="utf-8") as f:
        json.dump(statistical_analysis, f, indent=2)

    # Report-friendly overall table
    overall_report_rows = []
    for stat_obj in overall_stats:
        digits = 4 if "Accuracy" not in stat_obj["metric"] and "Time" not in stat_obj["metric"] else 4
        overall_report_rows.append(
            {
                "Metric": stat_obj["metric"],
                "Mean +/- Std": fmt_mean_std(stat_obj["mean"], stat_obj["std"], digits=digits),
                "95% CI": fmt_ci(stat_obj, digits=digits),
                "Min": round(stat_obj["min"], digits),
                "Max": round(stat_obj["max"], digits),
                "CV %": round(stat_obj["cv_percent"], 2),
            }
        )
    pd.DataFrame(overall_report_rows).to_csv(metrics_dir / "comprehensive_report_overall.csv", index=False)

    # Per-class outputs
    df_per_class_summary, per_class_stats, detailed_tables = build_per_class_tables(all_results, all_styles)
    with open(metrics_dir / "per_class_metrics_statistics.json", "w", encoding="utf-8") as f:
        json.dump(per_class_stats, f, indent=2)

    if len(df_per_class_summary) > 0:
        df_per_class_summary.to_csv(metrics_dir / "per_class_metrics_summary.csv", index=False)
        safe_to_excel(df_per_class_summary, metrics_dir / "per_class_metrics_summary.xlsx")

        detailed_tables["f1"].to_csv(metrics_dir / "per_class_metrics_f1_summary.csv", index=False)
        detailed_tables["precision"].to_csv(metrics_dir / "per_class_metrics_precision_summary.csv", index=False)
        detailed_tables["recall"].to_csv(metrics_dir / "per_class_metrics_recall_summary.csv", index=False)
        detailed_tables["accuracy"].to_csv(metrics_dir / "per_class_metrics_accuracy_summary.csv", index=False)

        # Report-friendly per-class table
        per_class_report_rows = []
        for style in sorted(per_class_stats.keys()):
            f1_stat = per_class_stats[style]["f1"]
            precision_stat = per_class_stats[style]["precision"]
            recall_stat = per_class_stats[style]["recall"]
            per_class_report_rows.append(
                {
                    "Style": style,
                    "F1-Score": fmt_mean_std(f1_stat["mean"], f1_stat["std"], digits=4),
                    "Precision": fmt_mean_std(precision_stat["mean"], precision_stat["std"], digits=4),
                    "Recall": fmt_mean_std(recall_stat["mean"], recall_stat["std"], digits=4),
                    "95% CI (F1)": fmt_ci(f1_stat, digits=4),
                }
            )
        pd.DataFrame(per_class_report_rows).to_csv(metrics_dir / "comprehensive_report_per_class.csv", index=False)

    save_robustness_plots(all_results, df_summary, df_per_class_summary)

In [ ]:


ROBUSTNESS_CONFIG = BEST_CONFIG.copy()
ROBUSTNESS_CONFIG["name"] = "selected_config_30_seed"

# Prevent accidental mixing of results from different configs.
selected_config_path = ROBUSTNESS_METRICS_DIR / "selected_config.json"
config_keys_to_compare = [
    "clip_model",
    "batch_size",
    "max_epochs",
    "patience",
    "dropout",
    "weight_decay",
    "head_lr",
    "clip_lr",
    "unfreeze_visual_blocks",
]
if selected_config_path.exists():
    previous_config = json.loads(selected_config_path.read_text(encoding="utf-8"))
    old_core = {k: previous_config.get(k) for k in config_keys_to_compare}
    new_core = {k: ROBUSTNESS_CONFIG.get(k) for k in config_keys_to_compare}
    if old_core != new_core:
        raise RuntimeError(
            "The robustness output folder already contains results from a different config. "
            "Use a new output folder or remove the old robustness results first."
        )

with open(selected_config_path, "w", encoding="utf-8") as f:
    json.dump(ROBUSTNESS_CONFIG, f, indent=2)

ROBUSTNESS_SEEDS = load_robustness_seeds()
write_robustness_seeds_list(ROBUSTNESS_METRICS_DIR, ROBUSTNESS_SEEDS)

print("Running final 30-seed robustness with config:")
print(ROBUSTNESS_CONFIG)
print(f"Total seeds found: {len(ROBUSTNESS_SEEDS)}")
print(f"Output root: {ROBUSTNESS_OUTPUT_ROOT}")

ORIG_OUTPUT_ROOT = OUTPUT_ROOT
ORIG_METRICS_DIR = METRICS_DIR
ORIG_ARTIFACTS_DIR = ARTIFACTS_DIR

all_results = []
failed_seeds = []

try:
    OUTPUT_ROOT = ROBUSTNESS_OUTPUT_ROOT
    METRICS_DIR = ROBUSTNESS_METRICS_DIR
    ARTIFACTS_DIR = ROBUSTNESS_ARTIFACTS_DIR

    for seed_idx, seed in enumerate(ROBUSTNESS_SEEDS, start=1):
        result_path = METRICS_DIR / "experiments" / f"seed_{seed}_results.json"

        try:
            if result_path.exists():
                print(f"[{seed_idx}/{len(ROBUSTNESS_SEEDS)}] Reusing saved result for seed {seed}")
                with open(result_path, "r", encoding="utf-8") as f:
                    result = json.load(f)
            else:
                print(f"[{seed_idx}/{len(ROBUSTNESS_SEEDS)}] Running seed {seed}")
                result = run_finetune_trial(ROBUSTNESS_CONFIG, seed=seed, save_as_seed_result=True)

            all_results.append(result)

        except Exception as exc:
            print(f"[{seed_idx}/{len(ROBUSTNESS_SEEDS)}] Seed {seed} failed: {exc}")
            failed_seeds.append({"seed": seed, "error": str(exc)})

        # Refresh summary outputs after each seed so the run is safely resumable.
        save_robustness_outputs(
            all_results=all_results,
            failed_seeds=failed_seeds,
            seeds=ROBUSTNESS_SEEDS,
            metrics_dir=ROBUSTNESS_METRICS_DIR,
            all_styles=all_styles,
        )

finally:
    OUTPUT_ROOT = ORIG_OUTPUT_ROOT
    METRICS_DIR = ORIG_METRICS_DIR
    ARTIFACTS_DIR = ORIG_ARTIFACTS_DIR

Running final 30-seed robustness with config:
{'name': 'selected_config_30_seed', 'clip_model': 'ViT-B/32', 'batch_size': 32, 'max_epochs': 20, 'patience': 5, 'dropout': 0.5, 'weight_decay': 0.0001, 'head_lr': 5e-05, 'clip_lr': 1e-05, 'unfreeze_visual_blocks': 2}
Total seeds found: 30
Output root: /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness
[1/30] Running seed 13

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial selected_config_30_seed on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1838 val_loss=1.2499 val_macro_f1=0.6864 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0623 val_loss=0.6007 val_macro_f1=0.8119 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6574 val_loss=0.4845 val_macro_f1=0.8388 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4523 val_loss=0.4727 val_macro_f1=0.8520 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3312 val_loss=0.5011 val_macro_f1=0.8537 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2393 val_loss=0.5337 val_macro_f1=0.8534 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1679 val_loss=0.5578 val_macro_f1=0.8642 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1152 val_loss=0.6167 val_macro_f1=0.8514 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0831 val_loss=0.6532 val_macro_f1=0.8534 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0631 val_loss=0.6799 val_macro_f1=0.8588 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0463 val_loss=0.7391 val_macro_f1=0.8537 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0333 val_loss=0.7707 val_macro_f1=0.8537 clip_lr=4.22e-06 head_lr=2.11e-05
Early stopping at epoch 12

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_13_results.json
Best val macro F1: 0.8642
Test macro F1: 0.8565
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[2/30] Running seed 14

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9233 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
Dataset initialized with 1982 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg

======================================================================
Running trial selected_config_30_seed on seed 14
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_14
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1921 val_loss=1.2509 val_macro_f1=0.7098 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0475 val_loss=0.6028 val_macro_f1=0.8055 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6548 val_loss=0.4945 val_macro_f1=0.8258 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4452 val_loss=0.4547 val_macro_f1=0.8501 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3299 val_loss=0.4646 val_macro_f1=0.8567 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2325 val_loss=0.4778 val_macro_f1=0.8540 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1641 val_loss=0.5194 val_macro_f1=0.8594 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1188 val_loss=0.5402 val_macro_f1=0.8632 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0783 val_loss=0.5865 val_macro_f1=0.8603 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0595 val_loss=0.6461 val_macro_f1=0.8588 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0487 val_loss=0.6454 val_macro_f1=0.8624 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0393 val_loss=0.6466 val_macro_f1=0.8689 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0302 val_loss=0.6955 val_macro_f1=0.8592 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0264 val_loss=0.7132 val_macro_f1=0.8636 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0215 val_loss=0.7062 val_macro_f1=0.8662 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0203 val_loss=0.7321 val_macro_f1=0.8671 clip_lr=1.46e-06 head_lr=7.32e-06

Epoch 17/20: train_loss=0.0185 val_loss=0.7233 val_macro_f1=0.8646 clip_lr=9.55e-07 head_lr=4.77e-06
Early stopping at epoch 17

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_14_results.json
Best val macro F1: 0.8689
Test macro F1: 0.8448
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[3/30] Running seed 16

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1976 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
Dataset initialized with 1982 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial selected_config_30_seed on seed 16
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_16
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1944 val_loss=1.2837 val_macro_f1=0.6972 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0455 val_loss=0.6277 val_macro_f1=0.7892 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6286 val_loss=0.5461 val_macro_f1=0.8132 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4446 val_loss=0.5258 val_macro_f1=0.8374 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3133 val_loss=0.5656 val_macro_f1=0.8234 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2291 val_loss=0.5687 val_macro_f1=0.8357 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1553 val_loss=0.6389 val_macro_f1=0.8369 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1130 val_loss=0.6598 val_macro_f1=0.8397 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0845 val_loss=0.6888 val_macro_f1=0.8434 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0589 val_loss=0.7435 val_macro_f1=0.8400 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0457 val_loss=0.7664 val_macro_f1=0.8398 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0357 val_loss=0.8077 val_macro_f1=0.8402 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0274 val_loss=0.8144 val_macro_f1=0.8470 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0226 val_loss=0.8447 val_macro_f1=0.8440 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0198 val_loss=0.8693 val_macro_f1=0.8401 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0185 val_loss=0.8742 val_macro_f1=0.8424 clip_lr=1.46e-06 head_lr=7.32e-06

Epoch 17/20: train_loss=0.0157 val_loss=0.8763 val_macro_f1=0.8434 clip_lr=9.55e-07 head_lr=4.77e-06

Epoch 18/20: train_loss=0.0159 val_loss=0.8824 val_macro_f1=0.8438 clip_lr=5.45e-07 head_lr=2.72e-06
Early stopping at epoch 18

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_16_results.json
Best val macro F1: 0.8470
Test macro F1: 0.8392
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[4/30] Running seed 17

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial selected_config_30_seed on seed 17
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_17
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1953 val_loss=1.2677 val_macro_f1=0.6822 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0491 val_loss=0.6077 val_macro_f1=0.8053 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6446 val_loss=0.5345 val_macro_f1=0.8243 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4270 val_loss=0.4855 val_macro_f1=0.8461 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3040 val_loss=0.5202 val_macro_f1=0.8458 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2133 val_loss=0.5639 val_macro_f1=0.8520 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1701 val_loss=0.5881 val_macro_f1=0.8475 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1148 val_loss=0.6306 val_macro_f1=0.8448 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0799 val_loss=0.6581 val_macro_f1=0.8505 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0598 val_loss=0.7002 val_macro_f1=0.8497 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0450 val_loss=0.7283 val_macro_f1=0.8485 clip_lr=5.00e-06 head_lr=2.50e-05
Early stopping at epoch 11

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_17_results.json
Best val macro F1: 0.8520
Test macro F1: 0.8422
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[5/30] Running seed 45

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9242 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
Dataset initialized with 1976 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png

======================================================================
Running trial selected_config_30_seed on seed 45
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_45
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1833 val_loss=1.2376 val_macro_f1=0.7068 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0395 val_loss=0.5907 val_macro_f1=0.8174 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6449 val_loss=0.4936 val_macro_f1=0.8419 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4481 val_loss=0.4509 val_macro_f1=0.8596 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3193 val_loss=0.5029 val_macro_f1=0.8472 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2251 val_loss=0.5107 val_macro_f1=0.8521 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1709 val_loss=0.5260 val_macro_f1=0.8580 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1124 val_loss=0.5506 val_macro_f1=0.8668 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0793 val_loss=0.6223 val_macro_f1=0.8562 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0605 val_loss=0.6288 val_macro_f1=0.8684 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0465 val_loss=0.6392 val_macro_f1=0.8635 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0384 val_loss=0.6917 val_macro_f1=0.8583 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0291 val_loss=0.6885 val_macro_f1=0.8629 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0264 val_loss=0.7214 val_macro_f1=0.8606 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0222 val_loss=0.7205 val_macro_f1=0.8646 clip_lr=2.06e-06 head_lr=1.03e-05
Early stopping at epoch 15

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_45_results.json
Best val macro F1: 0.8684
Test macro F1: 0.8515
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[6/30] Running seed 48

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9235 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
Dataset initialized with 1980 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg

======================================================================
Running trial selected_config_30_seed on seed 48
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_48
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1974 val_loss=1.2629 val_macro_f1=0.6835 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0399 val_loss=0.5872 val_macro_f1=0.8065 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6438 val_loss=0.5095 val_macro_f1=0.8188 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4500 val_loss=0.4695 val_macro_f1=0.8464 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3297 val_loss=0.4779 val_macro_f1=0.8547 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2223 val_loss=0.5230 val_macro_f1=0.8548 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1673 val_loss=0.5256 val_macro_f1=0.8579 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1218 val_loss=0.6060 val_macro_f1=0.8524 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0876 val_loss=0.6088 val_macro_f1=0.8548 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0669 val_loss=0.6428 val_macro_f1=0.8512 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0464 val_loss=0.6663 val_macro_f1=0.8519 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0393 val_loss=0.6669 val_macro_f1=0.8610 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0287 val_loss=0.7133 val_macro_f1=0.8540 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0247 val_loss=0.7308 val_macro_f1=0.8525 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0184 val_loss=0.7522 val_macro_f1=0.8585 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0173 val_loss=0.7720 val_macro_f1=0.8536 clip_lr=1.46e-06 head_lr=7.32e-06

Epoch 17/20: train_loss=0.0172 val_loss=0.7660 val_macro_f1=0.8547 clip_lr=9.55e-07 head_lr=4.77e-06
Early stopping at epoch 17

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_48_results.json
Best val macro F1: 0.8610
Test macro F1: 0.8603
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[7/30] Running seed 53

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
Dataset initialized with 1977 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg

======================================================================
Running trial selected_config_30_seed on seed 53
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_53
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1852 val_loss=1.2375 val_macro_f1=0.7168 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0382 val_loss=0.6234 val_macro_f1=0.7904 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6204 val_loss=0.5244 val_macro_f1=0.8305 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4378 val_loss=0.5304 val_macro_f1=0.8350 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3083 val_loss=0.5457 val_macro_f1=0.8377 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2216 val_loss=0.5706 val_macro_f1=0.8403 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1535 val_loss=0.6288 val_macro_f1=0.8340 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1097 val_loss=0.6787 val_macro_f1=0.8357 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0867 val_loss=0.7568 val_macro_f1=0.8342 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0631 val_loss=0.7482 val_macro_f1=0.8386 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0442 val_loss=0.8044 val_macro_f1=0.8379 clip_lr=5.00e-06 head_lr=2.50e-05
Early stopping at epoch 11

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_53_results.json
Best val macro F1: 0.8403
Test macro F1: 0.8581
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[8/30] Running seed 58

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg

======================================================================
Running trial selected_config_30_seed on seed 58
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_58
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1835 val_loss=1.2683 val_macro_f1=0.7191 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0444 val_loss=0.6193 val_macro_f1=0.7906 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6518 val_loss=0.5072 val_macro_f1=0.8163 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4435 val_loss=0.4827 val_macro_f1=0.8409 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3240 val_loss=0.4965 val_macro_f1=0.8486 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2295 val_loss=0.5801 val_macro_f1=0.8320 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1671 val_loss=0.5600 val_macro_f1=0.8445 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1222 val_loss=0.6022 val_macro_f1=0.8499 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0874 val_loss=0.6232 val_macro_f1=0.8460 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0659 val_loss=0.6478 val_macro_f1=0.8516 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0486 val_loss=0.7051 val_macro_f1=0.8447 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0396 val_loss=0.7058 val_macro_f1=0.8471 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0295 val_loss=0.7260 val_macro_f1=0.8485 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0255 val_loss=0.7319 val_macro_f1=0.8495 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0214 val_loss=0.7683 val_macro_f1=0.8457 clip_lr=2.06e-06 head_lr=1.03e-05
Early stopping at epoch 15

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_58_results.json
Best val macro F1: 0.8516
Test macro F1: 0.8621
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[9/30] Running seed 72

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9232 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1983 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg

======================================================================
Running trial selected_config_30_seed on seed 72
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_72
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.2051 val_loss=1.2737 val_macro_f1=0.7082 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0475 val_loss=0.6102 val_macro_f1=0.8127 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6331 val_loss=0.4939 val_macro_f1=0.8347 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4395 val_loss=0.5253 val_macro_f1=0.8300 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3140 val_loss=0.5010 val_macro_f1=0.8449 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2241 val_loss=0.5702 val_macro_f1=0.8409 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1622 val_loss=0.5788 val_macro_f1=0.8463 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1190 val_loss=0.6181 val_macro_f1=0.8497 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0786 val_loss=0.6780 val_macro_f1=0.8492 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0606 val_loss=0.7250 val_macro_f1=0.8432 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0451 val_loss=0.7617 val_macro_f1=0.8433 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0365 val_loss=0.7622 val_macro_f1=0.8494 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0287 val_loss=0.7987 val_macro_f1=0.8491 clip_lr=3.45e-06 head_lr=1.73e-05
Early stopping at epoch 13

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_72_results.json
Best val macro F1: 0.8497
Test macro F1: 0.8420
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[10/30] Running seed 102

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9233 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
Dataset initialized with 1983 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg

======================================================================
Running trial selected_config_30_seed on seed 102
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_102
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.2017 val_loss=1.2618 val_macro_f1=0.6888 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0581 val_loss=0.5908 val_macro_f1=0.8141 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6492 val_loss=0.4796 val_macro_f1=0.8334 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4576 val_loss=0.4584 val_macro_f1=0.8477 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3177 val_loss=0.4795 val_macro_f1=0.8488 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2359 val_loss=0.5006 val_macro_f1=0.8508 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1584 val_loss=0.5232 val_macro_f1=0.8582 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1126 val_loss=0.5566 val_macro_f1=0.8565 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0783 val_loss=0.6433 val_macro_f1=0.8521 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0562 val_loss=0.6662 val_macro_f1=0.8554 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0469 val_loss=0.6764 val_macro_f1=0.8606 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0348 val_loss=0.7068 val_macro_f1=0.8608 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0263 val_loss=0.7366 val_macro_f1=0.8575 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0217 val_loss=0.7304 val_macro_f1=0.8619 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0189 val_loss=0.7428 val_macro_f1=0.8629 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0178 val_loss=0.7509 val_macro_f1=0.8630 clip_lr=1.46e-06 head_lr=7.32e-06

Epoch 17/20: train_loss=0.0168 val_loss=0.7635 val_macro_f1=0.8585 clip_lr=9.55e-07 head_lr=4.77e-06

Epoch 18/20: train_loss=0.0151 val_loss=0.7646 val_macro_f1=0.8577 clip_lr=5.45e-07 head_lr=2.72e-06

Epoch 19/20: train_loss=0.0134 val_loss=0.7681 val_macro_f1=0.8598 clip_lr=2.45e-07 head_lr=1.22e-06

Epoch 20/20: train_loss=0.0154 val_loss=0.7697 val_macro_f1=0.8612 clip_lr=6.16e-08 head_lr=3.08e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_102_results.json
Best val macro F1: 0.8630
Test macro F1: 0.8673
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[11/30] Running seed 112

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
Dataset initialized with 1984 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg

======================================================================
Running trial selected_config_30_seed on seed 112
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_112
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1896 val_loss=1.2700 val_macro_f1=0.7059 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0607 val_loss=0.5825 val_macro_f1=0.8286 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6408 val_loss=0.5204 val_macro_f1=0.8337 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4518 val_loss=0.4769 val_macro_f1=0.8438 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3200 val_loss=0.5082 val_macro_f1=0.8482 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2252 val_loss=0.5305 val_macro_f1=0.8522 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1570 val_loss=0.5620 val_macro_f1=0.8522 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1140 val_loss=0.5948 val_macro_f1=0.8516 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0854 val_loss=0.6557 val_macro_f1=0.8487 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0551 val_loss=0.6899 val_macro_f1=0.8517 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0426 val_loss=0.7014 val_macro_f1=0.8531 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0337 val_loss=0.7339 val_macro_f1=0.8514 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0252 val_loss=0.7637 val_macro_f1=0.8566 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0233 val_loss=0.7824 val_macro_f1=0.8525 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0178 val_loss=0.8053 val_macro_f1=0.8532 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0159 val_loss=0.8245 val_macro_f1=0.8549 clip_lr=1.46e-06 head_lr=7.32e-06

Epoch 17/20: train_loss=0.0159 val_loss=0.8297 val_macro_f1=0.8542 clip_lr=9.55e-07 head_lr=4.77e-06

Epoch 18/20: train_loss=0.0146 val_loss=0.8472 val_macro_f1=0.8537 clip_lr=5.45e-07 head_lr=2.72e-06
Early stopping at epoch 18

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_112_results.json
Best val macro F1: 0.8566
Test macro F1: 0.8633
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[12/30] Running seed 115

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg

======================================================================
Running trial selected_config_30_seed on seed 115
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_115
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.2162 val_loss=1.2643 val_macro_f1=0.7265 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0540 val_loss=0.6072 val_macro_f1=0.8096 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6426 val_loss=0.5068 val_macro_f1=0.8388 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4518 val_loss=0.4900 val_macro_f1=0.8498 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3176 val_loss=0.5339 val_macro_f1=0.8485 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2241 val_loss=0.5545 val_macro_f1=0.8494 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1607 val_loss=0.5815 val_macro_f1=0.8431 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1062 val_loss=0.6345 val_macro_f1=0.8491 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0784 val_loss=0.6628 val_macro_f1=0.8482 clip_lr=6.55e-06 head_lr=3.27e-05
Early stopping at epoch 9

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_115_results.json
Best val macro F1: 0.8498
Test macro F1: 0.8400
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[13/30] Running seed 120

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial selected_config_30_seed on seed 120
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_120
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1877 val_loss=1.2286 val_macro_f1=0.7313 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0364 val_loss=0.5977 val_macro_f1=0.8165 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6232 val_loss=0.4807 val_macro_f1=0.8426 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4282 val_loss=0.5128 val_macro_f1=0.8372 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3079 val_loss=0.5134 val_macro_f1=0.8448 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2172 val_loss=0.5458 val_macro_f1=0.8452 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1578 val_loss=0.5494 val_macro_f1=0.8485 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1058 val_loss=0.6195 val_macro_f1=0.8418 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0805 val_loss=0.6104 val_macro_f1=0.8534 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0573 val_loss=0.6513 val_macro_f1=0.8513 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0433 val_loss=0.6769 val_macro_f1=0.8553 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0340 val_loss=0.7206 val_macro_f1=0.8496 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0300 val_loss=0.7372 val_macro_f1=0.8538 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0236 val_loss=0.7533 val_macro_f1=0.8561 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0184 val_loss=0.7678 val_macro_f1=0.8551 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0173 val_loss=0.7700 val_macro_f1=0.8535 clip_lr=1.46e-06 head_lr=7.32e-06

Epoch 17/20: train_loss=0.0150 val_loss=0.7681 val_macro_f1=0.8570 clip_lr=9.55e-07 head_lr=4.77e-06

Epoch 18/20: train_loss=0.0149 val_loss=0.7828 val_macro_f1=0.8565 clip_lr=5.45e-07 head_lr=2.72e-06

Epoch 19/20: train_loss=0.0153 val_loss=0.7856 val_macro_f1=0.8548 clip_lr=2.45e-07 head_lr=1.22e-06

Epoch 20/20: train_loss=0.0142 val_loss=0.7848 val_macro_f1=0.8566 clip_lr=6.16e-08 head_lr=3.08e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_120_results.json
Best val macro F1: 0.8570
Test macro F1: 0.8442
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[14/30] Running seed 126

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9236 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
Dataset initialized with 1980 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg

======================================================================
Running trial selected_config_30_seed on seed 126
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_126
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.2056 val_loss=1.2792 val_macro_f1=0.7045 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0504 val_loss=0.6602 val_macro_f1=0.7908 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6285 val_loss=0.5253 val_macro_f1=0.8294 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4466 val_loss=0.5174 val_macro_f1=0.8372 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3092 val_loss=0.5181 val_macro_f1=0.8430 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2318 val_loss=0.5953 val_macro_f1=0.8339 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1668 val_loss=0.6212 val_macro_f1=0.8393 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1254 val_loss=0.6508 val_macro_f1=0.8408 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0864 val_loss=0.6675 val_macro_f1=0.8423 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0604 val_loss=0.6974 val_macro_f1=0.8431 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0455 val_loss=0.7153 val_macro_f1=0.8515 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0417 val_loss=0.7260 val_macro_f1=0.8493 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0318 val_loss=0.7949 val_macro_f1=0.8449 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0239 val_loss=0.7824 val_macro_f1=0.8496 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0207 val_loss=0.7908 val_macro_f1=0.8523 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0186 val_loss=0.8031 val_macro_f1=0.8545 clip_lr=1.46e-06 head_lr=7.32e-06

Epoch 17/20: train_loss=0.0185 val_loss=0.8208 val_macro_f1=0.8516 clip_lr=9.55e-07 head_lr=4.77e-06

Epoch 18/20: train_loss=0.0148 val_loss=0.8188 val_macro_f1=0.8552 clip_lr=5.45e-07 head_lr=2.72e-06

Epoch 19/20: train_loss=0.0170 val_loss=0.8224 val_macro_f1=0.8538 clip_lr=2.45e-07 head_lr=1.22e-06

Epoch 20/20: train_loss=0.0155 val_loss=0.8233 val_macro_f1=0.8545 clip_lr=6.16e-08 head_lr=3.08e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_126_results.json
Best val macro F1: 0.8552
Test macro F1: 0.8486
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[15/30] Running seed 141

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9240 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
Dataset initialized with 1976 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg

======================================================================
Running trial selected_config_30_seed on seed 141
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_141
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1987 val_loss=1.2583 val_macro_f1=0.6960 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0394 val_loss=0.6227 val_macro_f1=0.7919 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6357 val_loss=0.5307 val_macro_f1=0.8321 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4529 val_loss=0.5053 val_macro_f1=0.8429 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3303 val_loss=0.5255 val_macro_f1=0.8509 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2238 val_loss=0.5577 val_macro_f1=0.8510 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1694 val_loss=0.6015 val_macro_f1=0.8548 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1254 val_loss=0.6372 val_macro_f1=0.8483 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0771 val_loss=0.6563 val_macro_f1=0.8524 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0630 val_loss=0.7128 val_macro_f1=0.8469 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0457 val_loss=0.7150 val_macro_f1=0.8519 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0316 val_loss=0.7731 val_macro_f1=0.8504 clip_lr=4.22e-06 head_lr=2.11e-05
Early stopping at epoch 12

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_141_results.json
Best val macro F1: 0.8548
Test macro F1: 0.8521
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[16/30] Running seed 215

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9235 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
Dataset initialized with 1983 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg

======================================================================
Running trial selected_config_30_seed on seed 215
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_215
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1939 val_loss=1.2725 val_macro_f1=0.6535 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0450 val_loss=0.6334 val_macro_f1=0.7842 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6393 val_loss=0.5199 val_macro_f1=0.8340 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4496 val_loss=0.4957 val_macro_f1=0.8471 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3196 val_loss=0.5210 val_macro_f1=0.8390 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2374 val_loss=0.5445 val_macro_f1=0.8499 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1639 val_loss=0.5937 val_macro_f1=0.8419 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1213 val_loss=0.5978 val_macro_f1=0.8526 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0808 val_loss=0.6339 val_macro_f1=0.8568 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0639 val_loss=0.6681 val_macro_f1=0.8605 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0451 val_loss=0.7089 val_macro_f1=0.8597 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0363 val_loss=0.7232 val_macro_f1=0.8552 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0293 val_loss=0.7466 val_macro_f1=0.8555 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0224 val_loss=0.7552 val_macro_f1=0.8585 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0213 val_loss=0.7833 val_macro_f1=0.8498 clip_lr=2.06e-06 head_lr=1.03e-05
Early stopping at epoch 15

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_215_results.json
Best val macro F1: 0.8605
Test macro F1: 0.8552
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[17/30] Running seed 217

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9235 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
Dataset initialized with 1981 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg

======================================================================
Running trial selected_config_30_seed on seed 217
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_217
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1931 val_loss=1.2715 val_macro_f1=0.6706 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0557 val_loss=0.6348 val_macro_f1=0.8056 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6432 val_loss=0.5122 val_macro_f1=0.8403 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4464 val_loss=0.4728 val_macro_f1=0.8492 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3231 val_loss=0.4918 val_macro_f1=0.8547 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2301 val_loss=0.5556 val_macro_f1=0.8469 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1648 val_loss=0.5374 val_macro_f1=0.8623 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1125 val_loss=0.6139 val_macro_f1=0.8482 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0944 val_loss=0.6157 val_macro_f1=0.8603 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0630 val_loss=0.6477 val_macro_f1=0.8620 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0470 val_loss=0.6833 val_macro_f1=0.8540 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0358 val_loss=0.7086 val_macro_f1=0.8598 clip_lr=4.22e-06 head_lr=2.11e-05
Early stopping at epoch 12

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_217_results.json
Best val macro F1: 0.8623
Test macro F1: 0.8535
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[18/30] Running seed 259

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9235 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
Dataset initialized with 1980 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg

======================================================================
Running trial selected_config_30_seed on seed 259
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_259
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.2101 val_loss=1.2472 val_macro_f1=0.7326 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0413 val_loss=0.5638 val_macro_f1=0.8258 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6292 val_loss=0.5019 val_macro_f1=0.8277 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4415 val_loss=0.4974 val_macro_f1=0.8374 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3249 val_loss=0.5074 val_macro_f1=0.8407 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2281 val_loss=0.5171 val_macro_f1=0.8571 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1579 val_loss=0.5491 val_macro_f1=0.8587 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1188 val_loss=0.5970 val_macro_f1=0.8444 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0825 val_loss=0.5933 val_macro_f1=0.8594 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0547 val_loss=0.6392 val_macro_f1=0.8553 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0389 val_loss=0.6793 val_macro_f1=0.8571 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0361 val_loss=0.6989 val_macro_f1=0.8495 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0278 val_loss=0.7022 val_macro_f1=0.8586 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0230 val_loss=0.7358 val_macro_f1=0.8553 clip_lr=2.73e-06 head_lr=1.37e-05
Early stopping at epoch 14

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_259_results.json
Best val macro F1: 0.8594
Test macro F1: 0.8461
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[19/30] Running seed 280

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9236 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
Dataset initialized with 1979 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1981 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg

======================================================================
Running trial selected_config_30_seed on seed 280
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_280
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1988 val_loss=1.2705 val_macro_f1=0.6946 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0460 val_loss=0.6175 val_macro_f1=0.8036 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6251 val_loss=0.5071 val_macro_f1=0.8259 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4381 val_loss=0.4989 val_macro_f1=0.8371 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3099 val_loss=0.5087 val_macro_f1=0.8437 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2183 val_loss=0.5545 val_macro_f1=0.8438 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1548 val_loss=0.6357 val_macro_f1=0.8442 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1126 val_loss=0.6239 val_macro_f1=0.8488 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0737 val_loss=0.6776 val_macro_f1=0.8487 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0598 val_loss=0.7042 val_macro_f1=0.8445 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0442 val_loss=0.7515 val_macro_f1=0.8398 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0342 val_loss=0.7963 val_macro_f1=0.8377 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0286 val_loss=0.7945 val_macro_f1=0.8473 clip_lr=3.45e-06 head_lr=1.73e-05
Early stopping at epoch 13

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_280_results.json
Best val macro F1: 0.8488
Test macro F1: 0.8438
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[20/30] Running seed 288

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg

======================================================================
Running trial selected_config_30_seed on seed 288
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_288
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1994 val_loss=1.2586 val_macro_f1=0.6578 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0567 val_loss=0.5913 val_macro_f1=0.8077 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6432 val_loss=0.5029 val_macro_f1=0.8268 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4498 val_loss=0.4774 val_macro_f1=0.8420 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3219 val_loss=0.4726 val_macro_f1=0.8574 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2324 val_loss=0.5212 val_macro_f1=0.8537 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1704 val_loss=0.5827 val_macro_f1=0.8456 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1262 val_loss=0.5889 val_macro_f1=0.8508 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0897 val_loss=0.6238 val_macro_f1=0.8523 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0675 val_loss=0.6269 val_macro_f1=0.8580 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0472 val_loss=0.6693 val_macro_f1=0.8566 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0388 val_loss=0.6833 val_macro_f1=0.8564 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0278 val_loss=0.6928 val_macro_f1=0.8558 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0259 val_loss=0.7251 val_macro_f1=0.8555 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0196 val_loss=0.7367 val_macro_f1=0.8576 clip_lr=2.06e-06 head_lr=1.03e-05
Early stopping at epoch 15

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_288_results.json
Best val macro F1: 0.8580
Test macro F1: 0.8545
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[21/30] Running seed 303

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9237 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg

======================================================================
Running trial selected_config_30_seed on seed 303
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_303
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1977 val_loss=1.2699 val_macro_f1=0.7236 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0631 val_loss=0.6170 val_macro_f1=0.8033 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6450 val_loss=0.5148 val_macro_f1=0.8242 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4414 val_loss=0.4655 val_macro_f1=0.8518 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3212 val_loss=0.4969 val_macro_f1=0.8519 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2243 val_loss=0.5440 val_macro_f1=0.8520 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1565 val_loss=0.5518 val_macro_f1=0.8580 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1169 val_loss=0.5930 val_macro_f1=0.8510 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0839 val_loss=0.6318 val_macro_f1=0.8468 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0588 val_loss=0.7159 val_macro_f1=0.8415 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0429 val_loss=0.7472 val_macro_f1=0.8430 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0316 val_loss=0.7353 val_macro_f1=0.8553 clip_lr=4.22e-06 head_lr=2.11e-05
Early stopping at epoch 12

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_303_results.json
Best val macro F1: 0.8580
Test macro F1: 0.8553
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[22/30] Running seed 309

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9236 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1982 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg

======================================================================
Running trial selected_config_30_seed on seed 309
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_309
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1937 val_loss=1.2733 val_macro_f1=0.6775 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0382 val_loss=0.6089 val_macro_f1=0.8145 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6360 val_loss=0.5201 val_macro_f1=0.8303 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4536 val_loss=0.4886 val_macro_f1=0.8515 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3151 val_loss=0.5123 val_macro_f1=0.8500 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2369 val_loss=0.5137 val_macro_f1=0.8492 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1671 val_loss=0.5697 val_macro_f1=0.8552 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1178 val_loss=0.5989 val_macro_f1=0.8493 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0803 val_loss=0.6379 val_macro_f1=0.8581 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0648 val_loss=0.6611 val_macro_f1=0.8572 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0475 val_loss=0.6992 val_macro_f1=0.8583 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0347 val_loss=0.7492 val_macro_f1=0.8551 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0246 val_loss=0.7547 val_macro_f1=0.8567 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0233 val_loss=0.7606 val_macro_f1=0.8582 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0209 val_loss=0.7783 val_macro_f1=0.8576 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0185 val_loss=0.7952 val_macro_f1=0.8621 clip_lr=1.46e-06 head_lr=7.32e-06

Epoch 17/20: train_loss=0.0160 val_loss=0.7933 val_macro_f1=0.8598 clip_lr=9.55e-07 head_lr=4.77e-06

Epoch 18/20: train_loss=0.0145 val_loss=0.8007 val_macro_f1=0.8605 clip_lr=5.45e-07 head_lr=2.72e-06

Epoch 19/20: train_loss=0.0144 val_loss=0.8037 val_macro_f1=0.8604 clip_lr=2.45e-07 head_lr=1.22e-06

Epoch 20/20: train_loss=0.0139 val_loss=0.8035 val_macro_f1=0.8603 clip_lr=6.16e-08 head_lr=3.08e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_309_results.json
Best val macro F1: 0.8621
Test macro F1: 0.8454
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[23/30] Running seed 328

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
Dataset initialized with 1979 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg

======================================================================
Running trial selected_config_30_seed on seed 328
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_328
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.2000 val_loss=1.2597 val_macro_f1=0.7293 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0419 val_loss=0.6148 val_macro_f1=0.8077 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6397 val_loss=0.5031 val_macro_f1=0.8363 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4513 val_loss=0.4771 val_macro_f1=0.8439 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3258 val_loss=0.5016 val_macro_f1=0.8525 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2276 val_loss=0.5111 val_macro_f1=0.8471 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1641 val_loss=0.5465 val_macro_f1=0.8462 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1142 val_loss=0.5667 val_macro_f1=0.8510 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0888 val_loss=0.6083 val_macro_f1=0.8589 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0666 val_loss=0.6293 val_macro_f1=0.8516 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0469 val_loss=0.6433 val_macro_f1=0.8561 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0405 val_loss=0.6802 val_macro_f1=0.8539 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0300 val_loss=0.7113 val_macro_f1=0.8524 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0279 val_loss=0.7212 val_macro_f1=0.8566 clip_lr=2.73e-06 head_lr=1.37e-05
Early stopping at epoch 14

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_328_results.json
Best val macro F1: 0.8589
Test macro F1: 0.8554
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[24/30] Running seed 333

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
Dataset initialized with 1977 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg

======================================================================
Running trial selected_config_30_seed on seed 333
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_333
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1929 val_loss=1.2588 val_macro_f1=0.6833 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0455 val_loss=0.6271 val_macro_f1=0.7981 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6332 val_loss=0.5104 val_macro_f1=0.8265 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4359 val_loss=0.5099 val_macro_f1=0.8356 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3066 val_loss=0.5285 val_macro_f1=0.8352 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2201 val_loss=0.5752 val_macro_f1=0.8396 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1588 val_loss=0.6094 val_macro_f1=0.8456 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1167 val_loss=0.5984 val_macro_f1=0.8496 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0800 val_loss=0.6795 val_macro_f1=0.8483 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0648 val_loss=0.6890 val_macro_f1=0.8462 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0474 val_loss=0.7239 val_macro_f1=0.8497 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0379 val_loss=0.7252 val_macro_f1=0.8552 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0291 val_loss=0.7728 val_macro_f1=0.8533 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0245 val_loss=0.7930 val_macro_f1=0.8489 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0217 val_loss=0.7993 val_macro_f1=0.8507 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0204 val_loss=0.8403 val_macro_f1=0.8461 clip_lr=1.46e-06 head_lr=7.32e-06

Epoch 17/20: train_loss=0.0175 val_loss=0.8080 val_macro_f1=0.8549 clip_lr=9.55e-07 head_lr=4.77e-06
Early stopping at epoch 17

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_333_results.json
Best val macro F1: 0.8552
Test macro F1: 0.8492
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[25/30] Running seed 347

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
Dataset initialized with 1979 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG

======================================================================
Running trial selected_config_30_seed on seed 347
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_347
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1835 val_loss=1.2443 val_macro_f1=0.7171 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0386 val_loss=0.6210 val_macro_f1=0.8062 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6486 val_loss=0.5305 val_macro_f1=0.8282 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4436 val_loss=0.4925 val_macro_f1=0.8435 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3125 val_loss=0.5364 val_macro_f1=0.8424 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2347 val_loss=0.5438 val_macro_f1=0.8447 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1577 val_loss=0.6026 val_macro_f1=0.8413 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1153 val_loss=0.6537 val_macro_f1=0.8425 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0848 val_loss=0.6670 val_macro_f1=0.8427 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0582 val_loss=0.6904 val_macro_f1=0.8469 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0411 val_loss=0.7271 val_macro_f1=0.8454 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0336 val_loss=0.7777 val_macro_f1=0.8438 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0241 val_loss=0.8140 val_macro_f1=0.8450 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0213 val_loss=0.8472 val_macro_f1=0.8428 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0174 val_loss=0.8385 val_macro_f1=0.8460 clip_lr=2.06e-06 head_lr=1.03e-05
Early stopping at epoch 15

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_347_results.json
Best val macro F1: 0.8469
Test macro F1: 0.8480
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[26/30] Running seed 360

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
Dataset initialized with 1981 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg

======================================================================
Running trial selected_config_30_seed on seed 360
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_360
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1941 val_loss=1.2727 val_macro_f1=0.7048 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0458 val_loss=0.6334 val_macro_f1=0.7928 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6409 val_loss=0.5293 val_macro_f1=0.8363 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4516 val_loss=0.4992 val_macro_f1=0.8426 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3168 val_loss=0.5248 val_macro_f1=0.8443 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2305 val_loss=0.5517 val_macro_f1=0.8416 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1589 val_loss=0.5931 val_macro_f1=0.8478 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1216 val_loss=0.6033 val_macro_f1=0.8473 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0808 val_loss=0.6685 val_macro_f1=0.8521 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0644 val_loss=0.7285 val_macro_f1=0.8391 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0489 val_loss=0.7203 val_macro_f1=0.8521 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0388 val_loss=0.7700 val_macro_f1=0.8474 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0319 val_loss=0.8200 val_macro_f1=0.8445 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0260 val_loss=0.8127 val_macro_f1=0.8511 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0224 val_loss=0.7956 val_macro_f1=0.8512 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0197 val_loss=0.8079 val_macro_f1=0.8515 clip_lr=1.46e-06 head_lr=7.32e-06
Early stopping at epoch 16

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_360_results.json
Best val macro F1: 0.8521
Test macro F1: 0.8495
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[27/30] Running seed 367

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9237 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg

======================================================================
Running trial selected_config_30_seed on seed 367
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_367
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1969 val_loss=1.2616 val_macro_f1=0.7140 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0412 val_loss=0.5959 val_macro_f1=0.7974 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6271 val_loss=0.5117 val_macro_f1=0.8250 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4418 val_loss=0.4931 val_macro_f1=0.8393 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3177 val_loss=0.4889 val_macro_f1=0.8471 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2296 val_loss=0.5345 val_macro_f1=0.8458 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1622 val_loss=0.5860 val_macro_f1=0.8453 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1143 val_loss=0.6064 val_macro_f1=0.8483 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0823 val_loss=0.6437 val_macro_f1=0.8533 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0542 val_loss=0.7254 val_macro_f1=0.8485 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0417 val_loss=0.7544 val_macro_f1=0.8498 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0343 val_loss=0.7650 val_macro_f1=0.8526 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0244 val_loss=0.7798 val_macro_f1=0.8511 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0231 val_loss=0.8159 val_macro_f1=0.8510 clip_lr=2.73e-06 head_lr=1.37e-05
Early stopping at epoch 14

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_367_results.json
Best val macro F1: 0.8533
Test macro F1: 0.8424
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[28/30] Running seed 378

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9237 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1979 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
Dataset initialized with 1980 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg

======================================================================
Running trial selected_config_30_seed on seed 378
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_378
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.2021 val_loss=1.2875 val_macro_f1=0.7041 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0386 val_loss=0.6017 val_macro_f1=0.8042 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6293 val_loss=0.5052 val_macro_f1=0.8313 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4442 val_loss=0.5048 val_macro_f1=0.8414 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3187 val_loss=0.5370 val_macro_f1=0.8451 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2210 val_loss=0.5164 val_macro_f1=0.8523 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1506 val_loss=0.5886 val_macro_f1=0.8402 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1039 val_loss=0.6435 val_macro_f1=0.8363 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0781 val_loss=0.6691 val_macro_f1=0.8428 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0545 val_loss=0.7345 val_macro_f1=0.8478 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0389 val_loss=0.7908 val_macro_f1=0.8400 clip_lr=5.00e-06 head_lr=2.50e-05
Early stopping at epoch 11

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_378_results.json
Best val macro F1: 0.8523
Test macro F1: 0.8394
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[29/30] Running seed 380

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9237 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg

======================================================================
Running trial selected_config_30_seed on seed 380
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_380
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1895 val_loss=1.2700 val_macro_f1=0.6953 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0391 val_loss=0.6178 val_macro_f1=0.7909 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6370 val_loss=0.5126 val_macro_f1=0.8198 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4552 val_loss=0.4921 val_macro_f1=0.8411 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3249 val_loss=0.5027 val_macro_f1=0.8425 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2370 val_loss=0.5423 val_macro_f1=0.8436 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1766 val_loss=0.5519 val_macro_f1=0.8540 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1241 val_loss=0.6010 val_macro_f1=0.8547 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0885 val_loss=0.6307 val_macro_f1=0.8555 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0659 val_loss=0.6965 val_macro_f1=0.8515 clip_lr=5.78e-06 head_lr=2.89e-05

Epoch 11/20: train_loss=0.0458 val_loss=0.6930 val_macro_f1=0.8515 clip_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/20: train_loss=0.0363 val_loss=0.7153 val_macro_f1=0.8534 clip_lr=4.22e-06 head_lr=2.11e-05

Epoch 13/20: train_loss=0.0284 val_loss=0.7475 val_macro_f1=0.8577 clip_lr=3.45e-06 head_lr=1.73e-05

Epoch 14/20: train_loss=0.0274 val_loss=0.7475 val_macro_f1=0.8561 clip_lr=2.73e-06 head_lr=1.37e-05

Epoch 15/20: train_loss=0.0194 val_loss=0.7826 val_macro_f1=0.8573 clip_lr=2.06e-06 head_lr=1.03e-05

Epoch 16/20: train_loss=0.0197 val_loss=0.7897 val_macro_f1=0.8566 clip_lr=1.46e-06 head_lr=7.32e-06

Epoch 17/20: train_loss=0.0177 val_loss=0.7897 val_macro_f1=0.8544 clip_lr=9.55e-07 head_lr=4.77e-06

Epoch 18/20: train_loss=0.0180 val_loss=0.7982 val_macro_f1=0.8558 clip_lr=5.45e-07 head_lr=2.72e-06
Early stopping at epoch 18

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_380_results.json
Best val macro F1: 0.8577
Test macro F1: 0.8488
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[30/30] Running seed 457

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Unfrozen visual blocks: 2
Trainable parameters: 14736526
   clip_model.visual.transformer.resblocks.10.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.10.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.10.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.10.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_1.weight
   clip_model.visual.transformer.resblocks.10.ln_1.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_fc.bias
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.weight
   clip_model.visual.transformer.resblocks.10.mlp.c_proj.bias
   clip_model.visual.transformer.resblocks.10.ln_2.weight
   clip_model.visual.transformer.resblocks.10.ln_2.bias
   clip_model.visual.transformer.resblocks.11.attn.in_proj_weight
   clip_model.visual.transformer.resblocks.11.attn.in_proj_bias
   clip_model.visual.transformer.resblocks.11.attn.out_proj.weight
   clip_model.visual.transformer.resblocks.11.attn.out_proj.bias
   clip_model.visual.transformer.resblocks.11.ln_1.weight
   clip_model.visual.transformer.resblocks.11.ln_1.bias
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.weight
   clip_model.visual.transformer.resblocks.11.mlp.c_fc.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
Dataset initialized with 1976 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
Dataset initialized with 1981 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg

======================================================================
Running trial selected_config_30_seed on seed 457
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_457
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1921 val_loss=1.2700 val_macro_f1=0.6786 clip_lr=1.00e-05 head_lr=5.00e-05

Epoch 2/20: train_loss=1.0499 val_loss=0.5911 val_macro_f1=0.8153 clip_lr=9.94e-06 head_lr=4.97e-05

Epoch 3/20: train_loss=0.6603 val_loss=0.5217 val_macro_f1=0.8216 clip_lr=9.76e-06 head_lr=4.88e-05

Epoch 4/20: train_loss=0.4576 val_loss=0.4692 val_macro_f1=0.8461 clip_lr=9.46e-06 head_lr=4.73e-05

Epoch 5/20: train_loss=0.3246 val_loss=0.5004 val_macro_f1=0.8573 clip_lr=9.05e-06 head_lr=4.52e-05

Epoch 6/20: train_loss=0.2245 val_loss=0.5187 val_macro_f1=0.8498 clip_lr=8.54e-06 head_lr=4.27e-05

Epoch 7/20: train_loss=0.1696 val_loss=0.5460 val_macro_f1=0.8558 clip_lr=7.94e-06 head_lr=3.97e-05

Epoch 8/20: train_loss=0.1177 val_loss=0.5777 val_macro_f1=0.8543 clip_lr=7.27e-06 head_lr=3.63e-05

Epoch 9/20: train_loss=0.0834 val_loss=0.6362 val_macro_f1=0.8481 clip_lr=6.55e-06 head_lr=3.27e-05

Epoch 10/20: train_loss=0.0654 val_loss=0.6819 val_macro_f1=0.8483 clip_lr=5.78e-06 head_lr=2.89e-05
Early stopping at epoch 10

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments/seed_457_results.json
Best val macro F1: 0.8573
Test macro F1: 0.8569
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'

Robustness run complete.
Successful seeds: 30 / 30
Failed seeds: 0
Results saved under: /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness

Per-seed summary:

,Seed,Best_Epoch,Early_Stopped,Best_Val_Macro_F1,Best_Val_Accuracy,Val_Loss_At_Best_Epoch,Min_Val_Loss,Test_Macro_F1,Test_Accuracy,Test_Macro_Precision,Test_Macro_Recall,Overfitting,Training_Time_Min,Trainable_Params
0,13,7,True,0.864177,86.434695,0.557778,0.472665,0.856459,85.598787,0.856898,0.858515,True,2.026171,14736526
1,14,12,True,0.868878,86.774356,0.646560,0.454653,0.844758,84.460141,0.846473,0.845918,True,2.873862,14736526
2,16,13,True,0.846987,84.615385,0.814394,0.525787,0.839231,83.854692,0.837304,0.842233,True,3.019219,14736526
3,17,6,True,0.852015,85.288170,0.563871,0.485463,0.842217,84.335523,0.842775,0.845592,True,1.863181,14736526
4,45,10,True,0.868400,86.740891,0.628770,0.450880,0.851487,84.883721,0.855104,0.849054,True,2.527485,14736526
5,48,12,True,0.860972,85.966683,0.666906,0.469464,0.860307,85.959596,0.861302,0.860272,True,2.864100,14736526
6,53,6,True,0.840287,83.897022,0.570595,0.524352,0.858126,85.685382,0.862317,0.856295,True,1.864216,14736526
7,58,10,True,0.851648,85.050505,0.647782,0.482702,0.862055,86.147624,0.861908,0.863061,True,2.533940,14736526
8,72,8,True,0.849684,84.906613,0.618076,0.493872,0.842042,84.367121,0.842720,0.843586,True,2.203088,14736526
9,102,16,False,0.863030,86.161616,0.750892,0.458429,0.867332,86.686838,0.869834,0.865773,False,3.390536,14736526
10,112,13,True,0.856564,85.439838,0.763735,0.476869,0.863264,86.239919,0.863920,0.863870,True,3.073877,14736526
11,115,4,True,0.849838,85.085945,0.490009,0.490009,0.840045,84.082870,0.838431,0.844751,True,1.536483,14736526
12,120,17,False,0.857025,85.540950,0.768102,0.480676,0.844233,84.335523,0.844239,0.845597,False,3.418099,14736526
13,126,18,False,0.855247,85.353535,0.818818,0.517359,0.848609,84.646465,0.850891,0.847926,False,3.442332,14736526
14,141,7,True,0.854774,85.353535,0.601499,0.505290,0.852083,85.172065,0.858082,0.850231,True,2.058608,14736526
15,215,10,True,0.860501,85.995956,0.668052,0.495713,0.855172,85.375693,0.857657,0.854499,True,2.578007,14736526
16,217,7,True,0.862282,86.111111,0.537362,0.472814,0.853544,85.159011,0.857042,0.852357,True,2.045565,14736526
17,259,9,True,0.859361,85.865724,0.593277,0.497352,0.846148,84.545455,0.845814,0.847957,True,2.373082,14736526
18,280,8,True,0.848833,84.689237,0.623872,0.498863,0.843793,84.300858,0.845385,0.844096,True,2.204784,14736526
19,288,10,True,0.858005,85.699848,0.626901,0.472615,0.854545,85.288170,0.858505,0.852184,True,2.525780,14736526
20,303,7,True,0.857991,85.707071,0.551809,0.465534,0.855254,85.447196,0.857753,0.853973,True,2.029995,14736526
21,309,16,False,0.862125,86.046512,0.795161,0.488648,0.845418,84.460141,0.848091,0.844001,False,3.371798,14736526
22,328,9,True,0.858868,85.901971,0.608258,0.477104,0.855375,85.598787,0.854925,0.859013,True,2.372082,14736526
23,333,12,True,0.855163,85.404040,0.725229,0.509865,0.849196,84.673748,0.854528,0.846879,True,2.874437,14736526
24,347,10,True,0.846916,84.588176,0.690423,0.492538,0.847975,84.732053,0.850178,0.849267,True,2.512365,14736526
25,360,11,True,0.852135,85.058051,0.720303,0.499160,0.849477,84.906613,0.851710,0.849724,True,2.706347,14736526
26,367,9,True,0.853275,85.159011,0.643705,0.488877,0.842372,84.175935,0.844770,0.841639,True,2.364905,14736526
27,378,6,True,0.852298,85.194543,0.516421,0.504777,0.839359,83.888889,0.839548,0.841643,True,1.862506,14736526
28,380,13,True,0.857746,85.512367,0.747521,0.492065,0.848762,84.782609,0.851676,0.847422,True,3.046619,14736526
29,457,5,True,0.857301,85.829960,0.500448,0.469198,0.856877,85.714286,0.859438,0.857326,True,1.685444,14736526

High-level robustness summary:
{
  "summary_statistics": [
    {
      "metric": "Test Macro F1",
      "mean": 0.850517229173512,
      "std": 0.007420450267628044,
      "min": 0.8392313864779696,
      "max": 0.8673322786940278,
      "median": 0.8493367043695952,
      "q25": 0.8443644703638196,
      "q75": 0.8553446168414114,
      "cv_percent": 0.8724632509606947,
      "ci_95_lower": 0.8476990192600071,
      "ci_95_upper": 0.8533354390870169,
      "n": 30
    },
    {
      "metric": "Test Accuracy",
      "mean": 84.98352365668964,
      "std": 0.7254833788240446,
      "min": 83.85469223007064,
      "max": 86.68683812405446,
      "median": 84.83316481294236,
      "q25": 84.39037571120417,
      "q75": 85.56088933804952,
      "cv_percent": 0.8536753332973112,
      "ci_95_lower": 84.70799260715152,
      "ci_95_upper": 85.25905470622776,
      "n": 30
    },
    {
      "metric": "Test Macro Precision",
      "mean": 0.8523073421510515,
      "std": 0.008151895519083569,
      "min": 0.8373044891145601,
      "max": 0.8698337818621356,
      "median": 0.8531187507592044,
      "q25": 0.8454925135636167,
      "q75": 0.8580001644498287,
      "cv_percent": 0.9564502282134321,
      "ci_95_lower": 0.8492113369307266,
      "ci_95_upper": 0.8554033473713765,
      "n": 30
    },
    {
      "metric": "Test Macro Recall",
      "mean": 0.8508218240456787,
      "std": 0.006860266535393484,
      "min": 0.841639240930891,
      "max": 0.865772616932442,
      "median": 0.8491602353654208,
      "q25": 0.8455932338387006,
      "q75": 0.8558463880027121,
      "cv_percent": 0.8063105977668448,
      "ci_95_lower": 0.848216366093393,
      "ci_95_upper": 0.8534272819979645,
      "n": 30
    },
    {
      "metric": "Best Val Macro F1",
      "mean": 0.8560775658063781,
      "std": 0.006337249541402713,
      "min": 0.8402867868485554,
      "max": 0.8688781553820786,
      "median": 0.8567944893560547,
      "q25": 0.8520450279998687,
      "q75": 0.8602158044153431,
      "cv_percent": 0.74026581171221,
      "ci_95_lower": 0.8536707442742874,
      "ci_95_upper": 0.8584843873384688,
      "n": 30
    },
    {
      "metric": "Best Val Accuracy",
      "mean": 85.51244393169996,
      "std": 0.6368471942795033,
      "min": 83.89702170620899,
      "max": 86.77435638566381,
      "median": 85.47610285579538,
      "q25": 85.10421169972167,
      "q75": 85.95050529295615,
      "cv_percent": 0.7447421275763824,
      "ci_95_lower": 85.27057598412594,
      "ci_95_upper": 85.75431187927398,
      "n": 30
    },
    {
      "metric": "Val Loss At Best Epoch",
      "mean": 0.6485509041654225,
      "std": 0.09244320681664316,
      "min": 0.4900090404816212,
      "max": 0.8188177394049783,
      "median": 0.6362370804793411,
      "q25": 0.5762657672317038,
      "q75": 0.7239973549055116,
      "cv_percent": 14.253808948983309,
      "ci_95_lower": 0.6134419346971682,
      "ci_95_upper": 0.6836598736336768,
      "n": 30
    },
    {
      "metric": "Min Val Loss",
      "mean": 0.4871198310366561,
      "std": 0.01889646583456116,
      "min": 0.4508804415743197,
      "max": 0.5257870282136625,
      "median": 0.4887627857707201,
      "q25": 0.4727022056017191,
      "q75": 0.4984853729124992,
      "cv_percent": 3.8792232692204207,
      "ci_95_lower": 0.47994314964610885,
      "ci_95_upper": 0.4942965124272034,
      "n": 30
    },
    {
      "metric": "Training Time (min)",
      "mean": 2.5082970274819263,
      "std": 0.5330533971756476,
      "min": 1.536483112970988,
      "max": 3.4423317233721415,
      "median": 2.5190722763538362,
      "q25": 2.0488254388173424,
      "q75": 2.874293175339699,
      "cv_percent": 21.251605824003175,
      "ci_95_lower": 2.3058488856351245,
      "ci_95_upper": 2.710745169328728,
      "n": 30
    }
  ],
  "overfitting_count": 26,
  "overfitting_percentage": 86.66666666666667,
  "total_experiments": 30
}

Key files:
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/overall_metrics_statistics.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/overall_metrics_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_statistics.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_f1_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_precision_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_recall_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_accuracy_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/comprehensive_report_overall.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/comprehensive_report_per_class.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/statistical_analysis.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments_summary.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/comparison_plots/robustness_analysis.png
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/comparison_plots/learning_curves_overlay.png
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/per_class_analysis_summary.png

In [11]:
print("\nRobustness run complete.")
print(f"Successful seeds: {len(all_results)} / {len(ROBUSTNESS_SEEDS)}")
print(f"Failed seeds: {len(failed_seeds)}")
print(f"Results saved under: {ROBUSTNESS_OUTPUT_ROOT}")

summary_csv = ROBUSTNESS_METRICS_DIR / "summary_table.csv"
overall_json = ROBUSTNESS_METRICS_DIR / "statistical_analysis.json"
experiments_summary_json = ROBUSTNESS_METRICS_DIR / "experiments_summary.json"

if summary_csv.exists():
    print("\nPer-seed summary:")
    display(pd.read_csv(summary_csv).sort_values("Seed"))

if overall_json.exists():
    print("\nHigh-level robustness summary:")
    with open(overall_json, "r", encoding="utf-8") as f:
        print(json.dumps(json.load(f), indent=2))

print("\nKey files:")
print("  ", ROBUSTNESS_METRICS_DIR / "experiments")
print("  ", ROBUSTNESS_METRICS_DIR / "summary_table.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "summary_table.xlsx")
print("  ", ROBUSTNESS_METRICS_DIR / "overall_metrics_statistics.json")
print("  ", ROBUSTNESS_METRICS_DIR / "overall_metrics_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_statistics.json")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_summary.xlsx")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_f1_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_precision_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_recall_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_accuracy_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "comprehensive_report_overall.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "comprehensive_report_per_class.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "statistical_analysis.json")
print("  ", experiments_summary_json)
print("  ", ROBUSTNESS_OUTPUT_ROOT / "comparison_plots" / "robustness_analysis.png")
print("  ", ROBUSTNESS_OUTPUT_ROOT / "comparison_plots" / "learning_curves_overlay.png")
print("  ", ROBUSTNESS_OUTPUT_ROOT / "per_class_analysis_summary.png")

Robustness run complete.
Successful seeds: 30 / 30
Failed seeds: 0
Results saved under: /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness

Per-seed summary:

,Seed,Best_Epoch,Early_Stopped,Best_Val_Macro_F1,Best_Val_Accuracy,Val_Loss_At_Best_Epoch,Min_Val_Loss,Test_Macro_F1,Test_Accuracy,Test_Macro_Precision,Test_Macro_Recall,Overfitting,Training_Time_Min,Trainable_Params
0,13,7,True,0.864177,86.434695,0.557778,0.472665,0.856459,85.598787,0.856898,0.858515,True,2.026171,14736526
1,14,12,True,0.868878,86.774356,0.646560,0.454653,0.844758,84.460141,0.846473,0.845918,True,2.873862,14736526
2,16,13,True,0.846987,84.615385,0.814394,0.525787,0.839231,83.854692,0.837304,0.842233,True,3.019219,14736526
3,17,6,True,0.852015,85.288170,0.563871,0.485463,0.842217,84.335523,0.842775,0.845592,True,1.863181,14736526
4,45,10,True,0.868400,86.740891,0.628770,0.450880,0.851487,84.883721,0.855104,0.849054,True,2.527485,14736526
5,48,12,True,0.860972,85.966683,0.666906,0.469464,0.860307,85.959596,0.861302,0.860272,True,2.864100,14736526
6,53,6,True,0.840287,83.897022,0.570595,0.524352,0.858126,85.685382,0.862317,0.856295,True,1.864216,14736526
7,58,10,True,0.851648,85.050505,0.647782,0.482702,0.862055,86.147624,0.861908,0.863061,True,2.533940,14736526
8,72,8,True,0.849684,84.906613,0.618076,0.493872,0.842042,84.367121,0.842720,0.843586,True,2.203088,14736526
9,102,16,False,0.863030,86.161616,0.750892,0.458429,0.867332,86.686838,0.869834,0.865773,False,3.390536,14736526
10,112,13,True,0.856564,85.439838,0.763735,0.476869,0.863264,86.239919,0.863920,0.863870,True,3.073877,14736526
11,115,4,True,0.849838,85.085945,0.490009,0.490009,0.840045,84.082870,0.838431,0.844751,True,1.536483,14736526
12,120,17,False,0.857025,85.540950,0.768102,0.480676,0.844233,84.335523,0.844239,0.845597,False,3.418099,14736526
13,126,18,False,0.855247,85.353535,0.818818,0.517359,0.848609,84.646465,0.850891,0.847926,False,3.442332,14736526
14,141,7,True,0.854774,85.353535,0.601499,0.505290,0.852083,85.172065,0.858082,0.850231,True,2.058608,14736526
15,215,10,True,0.860501,85.995956,0.668052,0.495713,0.855172,85.375693,0.857657,0.854499,True,2.578007,14736526
16,217,7,True,0.862282,86.111111,0.537362,0.472814,0.853544,85.159011,0.857042,0.852357,True,2.045565,14736526
17,259,9,True,0.859361,85.865724,0.593277,0.497352,0.846148,84.545455,0.845814,0.847957,True,2.373082,14736526
18,280,8,True,0.848833,84.689237,0.623872,0.498863,0.843793,84.300858,0.845385,0.844096,True,2.204784,14736526
19,288,10,True,0.858005,85.699848,0.626901,0.472615,0.854545,85.288170,0.858505,0.852184,True,2.525780,14736526
20,303,7,True,0.857991,85.707071,0.551809,0.465534,0.855254,85.447196,0.857753,0.853973,True,2.029995,14736526
21,309,16,False,0.862125,86.046512,0.795161,0.488648,0.845418,84.460141,0.848091,0.844001,False,3.371798,14736526
22,328,9,True,0.858868,85.901971,0.608258,0.477104,0.855375,85.598787,0.854925,0.859013,True,2.372082,14736526
23,333,12,True,0.855163,85.404040,0.725229,0.509865,0.849196,84.673748,0.854528,0.846879,True,2.874437,14736526
24,347,10,True,0.846916,84.588176,0.690423,0.492538,0.847975,84.732053,0.850178,0.849267,True,2.512365,14736526
25,360,11,True,0.852135,85.058051,0.720303,0.499160,0.849477,84.906613,0.851710,0.849724,True,2.706347,14736526
26,367,9,True,0.853275,85.159011,0.643705,0.488877,0.842372,84.175935,0.844770,0.841639,True,2.364905,14736526
27,378,6,True,0.852298,85.194543,0.516421,0.504777,0.839359,83.888889,0.839548,0.841643,True,1.862506,14736526
28,380,13,True,0.857746,85.512367,0.747521,0.492065,0.848762,84.782609,0.851676,0.847422,True,3.046619,14736526
29,457,5,True,0.857301,85.829960,0.500448,0.469198,0.856877,85.714286,0.859438,0.857326,True,1.685444,14736526

High-level robustness summary:
{
  "summary_statistics": [
    {
      "metric": "Test Macro F1",
      "mean": 0.850517229173512,
      "std": 0.007420450267628044,
      "min": 0.8392313864779696,
      "max": 0.8673322786940278,
      "median": 0.8493367043695952,
      "q25": 0.8443644703638196,
      "q75": 0.8553446168414114,
      "cv_percent": 0.8724632509606947,
      "ci_95_lower": 0.8476990192600071,
      "ci_95_upper": 0.8533354390870169,
      "n": 30
    },
    {
      "metric": "Test Accuracy",
      "mean": 84.98352365668964,
      "std": 0.7254833788240446,
      "min": 83.85469223007064,
      "max": 86.68683812405446,
      "median": 84.83316481294236,
      "q25": 84.39037571120417,
      "q75": 85.56088933804952,
      "cv_percent": 0.8536753332973112,
      "ci_95_lower": 84.70799260715152,
      "ci_95_upper": 85.25905470622776,
      "n": 30
    },
    {
      "metric": "Test Macro Precision",
      "mean": 0.8523073421510515,
      "std": 0.008151895519083569,
      "min": 0.8373044891145601,
      "max": 0.8698337818621356,
      "median": 0.8531187507592044,
      "q25": 0.8454925135636167,
      "q75": 0.8580001644498287,
      "cv_percent": 0.9564502282134321,
      "ci_95_lower": 0.8492113369307266,
      "ci_95_upper": 0.8554033473713765,
      "n": 30
    },
    {
      "metric": "Test Macro Recall",
      "mean": 0.8508218240456787,
      "std": 0.006860266535393484,
      "min": 0.841639240930891,
      "max": 0.865772616932442,
      "median": 0.8491602353654208,
      "q25": 0.8455932338387006,
      "q75": 0.8558463880027121,
      "cv_percent": 0.8063105977668448,
      "ci_95_lower": 0.848216366093393,
      "ci_95_upper": 0.8534272819979645,
      "n": 30
    },
    {
      "metric": "Best Val Macro F1",
      "mean": 0.8560775658063781,
      "std": 0.006337249541402713,
      "min": 0.8402867868485554,
      "max": 0.8688781553820786,
      "median": 0.8567944893560547,
      "q25": 0.8520450279998687,
      "q75": 0.8602158044153431,
      "cv_percent": 0.74026581171221,
      "ci_95_lower": 0.8536707442742874,
      "ci_95_upper": 0.8584843873384688,
      "n": 30
    },
    {
      "metric": "Best Val Accuracy",
      "mean": 85.51244393169996,
      "std": 0.6368471942795033,
      "min": 83.89702170620899,
      "max": 86.77435638566381,
      "median": 85.47610285579538,
      "q25": 85.10421169972167,
      "q75": 85.95050529295615,
      "cv_percent": 0.7447421275763824,
      "ci_95_lower": 85.27057598412594,
      "ci_95_upper": 85.75431187927398,
      "n": 30
    },
    {
      "metric": "Val Loss At Best Epoch",
      "mean": 0.6485509041654225,
      "std": 0.09244320681664316,
      "min": 0.4900090404816212,
      "max": 0.8188177394049783,
      "median": 0.6362370804793411,
      "q25": 0.5762657672317038,
      "q75": 0.7239973549055116,
      "cv_percent": 14.253808948983309,
      "ci_95_lower": 0.6134419346971682,
      "ci_95_upper": 0.6836598736336768,
      "n": 30
    },
    {
      "metric": "Min Val Loss",
      "mean": 0.4871198310366561,
      "std": 0.01889646583456116,
      "min": 0.4508804415743197,
      "max": 0.5257870282136625,
      "median": 0.4887627857707201,
      "q25": 0.4727022056017191,
      "q75": 0.4984853729124992,
      "cv_percent": 3.8792232692204207,
      "ci_95_lower": 0.47994314964610885,
      "ci_95_upper": 0.4942965124272034,
      "n": 30
    },
    {
      "metric": "Training Time (min)",
      "mean": 2.5082970274819263,
      "std": 0.5330533971756476,
      "min": 1.536483112970988,
      "max": 3.4423317233721415,
      "median": 2.5190722763538362,
      "q25": 2.0488254388173424,
      "q75": 2.874293175339699,
      "cv_percent": 21.251605824003175,
      "ci_95_lower": 2.3058488856351245,
      "ci_95_upper": 2.710745169328728,
      "n": 30
    }
  ],
  "overfitting_count": 26,
  "overfitting_percentage": 86.66666666666667,
  "total_experiments": 30
}

Key files:
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/summary_table.xlsx
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/overall_metrics_statistics.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/overall_metrics_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_statistics.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_summary.xlsx
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_f1_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_precision_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_recall_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/per_class_metrics_accuracy_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/comprehensive_report_overall.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/comprehensive_report_per_class.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/statistical_analysis.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/metrics/experiments_summary.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/comparison_plots/robustness_analysis.png
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/comparison_plots/learning_curves_overlay.png
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_clip_finetuned_robustness/per_class_analysis_summary.png