# Image-Only ViT-B/16 Tuning And Robustness Experiments

This notebook contains the self-contained `timm`-based ViT-B/16 image-only experiment pipeline used for model selection and robustness evaluation.

Completed workflow:
1. verified the CSV split loading and image-path remapping on matched seeds
2. ran a short smoke test to confirm transforms, logits, and output saving
3. ran a one-seed parameter search
4. selected the best configuration using **validation macro-F1** only
5. ran a shortlist comparison on additional matched seeds
6. reran the selected configuration cleanly
7. ran the final selected configuration on all 30 matched seeds

Primary output roots:
- `experiments/imageonly_vit_b16_pilot/`
- `experiments/imageonly_vit_b16_robustness/`

This notebook mirrors the fine-tuned CLIP image-only workflow as closely as possible so the backbone comparison remains clean and reviewer-facing.

In [16]:
import gc

def cleanup_memory():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        try:
            torch.cuda.ipc_collect()
        except Exception:
            pass

In [ ]:
# pip install timm

Requirement already satisfied: timm in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (0.6.13)
Requirement already satisfied: torch>=1.7 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from timm) (2.1.2)
Requirement already satisfied: torchvision in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from timm) (0.16.2)
Requirement already satisfied: pyyaml in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from timm) (6.0.3)
Requirement already satisfied: huggingface-hub in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from timm) (0.36.0)
Requirement already satisfied: filelock in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (3.20.0)
Requirement already satisfied: typing-extensions in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (4.15.0)
Requirement already satisfied: sympy in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (1.14.0)
Requirement already satisfied: networkx in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (3.4.2)
Requirement already satisfied: jinja2 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (3.1.6)
Requirement already satisfied: fsspec in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (2025.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.18.1 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (2.18.1)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (12.1.105)
Requirement already satisfied: triton==2.1.0 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torch>=1.7->timm) (2.1.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.7->timm) (12.8.93)
Requirement already satisfied: packaging>=20.9 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from huggingface-hub->timm) (25.0)
Requirement already satisfied: requests in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from huggingface-hub->timm) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from huggingface-hub->timm) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from huggingface-hub->timm) (1.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from jinja2->torch>=1.7->timm) (2.1.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from requests->huggingface-hub->timm) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from requests->huggingface-hub->timm) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from requests->huggingface-hub->timm) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from requests->huggingface-hub->timm) (2025.10.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from sympy->torch>=1.7->timm) (1.3.0)
Requirement already satisfied: numpy in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torchvision->timm) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages (from torchvision->timm) (10.4.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from pathlib import Path
from urllib.parse import unquote
import json
import os
import random
import time
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from PIL import Image
from IPython.display import display
from sklearn.metrics import f1_score, precision_score, recall_score
from sklearn.utils.class_weight import compute_class_weight
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

try:
    import timm
    from timm.data import create_transform
    try:
        from timm.data import resolve_model_data_config

        def get_timm_data_config(model):
            return resolve_model_data_config(model)

    except ImportError:
        from timm.data import resolve_data_config

        def get_timm_data_config(model):
            return resolve_data_config({}, model=model)

except ModuleNotFoundError as exc:
    raise ModuleNotFoundError(
        "This notebook requires `timm`. Install it in the notebook/kernel environment first, for example with `pip install timm`."
    ) from exc

warnings.filterwarnings("ignore")

_walk = Path.cwd().resolve()
for _ in range(10):
    if (_walk / "experiments").is_dir() and (_walk / "data").is_dir():
        PROJECT_ROOT = _walk
        break
    _walk = _walk.parent
else:
    PROJECT_ROOT = Path.cwd().resolve()

BASE_DIR = PROJECT_ROOT
SPLITS_ROOT = PROJECT_ROOT / "data" / "splits"
DATASET_CSV = PROJECT_ROOT / "data" / "processed" / "caption_dataset_final_full.csv"
OUTPUT_ROOT = PROJECT_ROOT / "experiments" / "imageonly_vit_b16_pilot"
METRICS_DIR = OUTPUT_ROOT / "metrics"
ARTIFACTS_DIR = OUTPUT_ROOT / "artifacts"
(METRICS_DIR / "trials").mkdir(parents=True, exist_ok=True)
(METRICS_DIR / "experiments").mkdir(parents=True, exist_ok=True)
(ARTIFACTS_DIR / "trial_models").mkdir(parents=True, exist_ok=True)
(ARTIFACTS_DIR / "trial_learning_curves").mkdir(parents=True, exist_ok=True)
(ARTIFACTS_DIR / "models").mkdir(parents=True, exist_ok=True)
(ARTIFACTS_DIR / "learning_curves").mkdir(parents=True, exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
MODEL_INIT_SEED = 42
DEFAULT_SEED = 13
DEBUG_SAMPLES = 5
NUM_WORKERS = 2
MODEL_NAME = "vit_base_patch16_224"

TRIAL_CONFIGS = [
    {
        "name": "vit_b16_lr5e6_head1e4",
        "model_name": MODEL_NAME,
        "batch_size": 32,
        "max_epochs": 15,
        "patience": 4,
        "dropout": 0.5,
        "weight_decay": 1e-4,
        "backbone_lr": 5e-6,
        "head_lr": 1e-4,
    },
    {
        "name": "vit_b16_lr1e5_head1e4",
        "model_name": MODEL_NAME,
        "batch_size": 32,
        "max_epochs": 15,
        "patience": 4,
        "dropout": 0.5,
        "weight_decay": 1e-4,
        "backbone_lr": 1e-5,
        "head_lr": 1e-4,
    },
    {
        "name": "vit_b16_lr2e5_head1e4",
        "model_name": MODEL_NAME,
        "batch_size": 32,
        "max_epochs": 15,
        "patience": 4,
        "dropout": 0.5,
        "weight_decay": 1e-4,
        "backbone_lr": 2e-5,
        "head_lr": 1e-4,
    },
]

print("PROJECT_ROOT:", PROJECT_ROOT)
print("SPLITS_ROOT:", SPLITS_ROOT)
print("DATASET_CSV:", DATASET_CSV)
print("OUTPUT_ROOT:", OUTPUT_ROOT)
print("DEVICE:", DEVICE)
print("Trial configs:")
for cfg in TRIAL_CONFIGS:
    print(" ", cfg)

PROJECT_ROOT: /home/ding-zhang/Dongmei/DATA255/Project
SPLITS_ROOT: /home/ding-zhang/Dongmei/DATA255/Project/data/splits
DATASET_CSV: /home/ding-zhang/Dongmei/DATA255/Project/data/processed/caption_dataset_final_full.csv
OUTPUT_ROOT: /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot
DEVICE: cuda
Trial configs:
  {'name': 'vit_b16_lr5e6_head1e4', 'model_name': 'vit_base_patch16_224', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'backbone_lr': 5e-06, 'head_lr': 0.0001}
  {'name': 'vit_b16_lr1e5_head1e4', 'model_name': 'vit_base_patch16_224', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'backbone_lr': 1e-05, 'head_lr': 0.0001}
  {'name': 'vit_b16_lr2e5_head1e4', 'model_name': 'vit_base_patch16_224', 'batch_size': 64, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'backbone_lr': 2e-05, 'head_lr': 0.0001}

## 1. Load Metadata, Split CSVs, And Verify Image Paths

This section loads the shared metadata and performs the initial path-resolution checks used before training:
- load style metadata
- load a selected seed from `data/splits/seed_<seed>/`
- verify that `dataset/...` paths remap into `data/raw dataset/...`
- confirm that sample images exist before launching training runs

In [3]:
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_style_metadata(dataset_csv):
    df = pd.read_csv(dataset_csv)
    df = df[df["status"] == "success"].copy()
    df["style"] = df["style"].str.strip()
    all_styles = sorted(df["style"].unique())
    style_to_idx = {style: idx for idx, style in enumerate(all_styles)}
    return all_styles, style_to_idx, len(all_styles)


def load_split_csvs(seed):
    split_dir = SPLITS_ROOT / f"seed_{seed}"
    train_df = pd.read_csv(split_dir / "train.csv")
    val_df = pd.read_csv(split_dir / "val.csv")
    test_df = pd.read_csv(split_dir / "test.csv")
    return split_dir, train_df, val_df, test_df


def resolve_image_path(image_path, base_dir):
    image_path = str(image_path)
    if not os.path.isabs(image_path):
        rel_path = image_path.replace("\\", "/")
        dataset_root = base_dir / "dataset"
        if rel_path.startswith("dataset/") and not dataset_root.is_dir():
            image_path = str(base_dir / "data" / "raw dataset" / rel_path[len("dataset/"):])
        else:
            image_path = str(base_dir / image_path)

    if "%" in image_path:
        parts = image_path.split("/")
        image_path = "/".join(unquote(part) if "%" in part else part for part in parts)

    return os.path.normpath(image_path)


def debug_path_resolution(df, sample_count=DEBUG_SAMPLES):
    print("=== Path resolution sanity check ===")
    print("BASE_DIR:", BASE_DIR)
    print("Top-level dataset/ exists:", (BASE_DIR / "dataset").is_dir())
    print("data/raw dataset/ exists:", (BASE_DIR / "data" / "raw dataset").is_dir())

    sample_count = min(sample_count, len(df))
    resolved_found = 0
    for raw_path in df["image_path"].head(sample_count):
        resolved_path = resolve_image_path(raw_path, BASE_DIR)
        exists = os.path.exists(resolved_path)
        resolved_found += int(exists)
        print(f"  exists={exists} raw={raw_path}")
        print(f"         resolved={resolved_path}")
    print(f"Resolved files found: {resolved_found}/{sample_count}")


all_styles, style_to_idx, num_classes = load_style_metadata(DATASET_CSV)
split_dir, train_df, val_df, test_df = load_split_csvs(DEFAULT_SEED)

print("Loaded seed:", DEFAULT_SEED)
print("Split dir:", split_dir)
print("Split sizes:", len(train_df), len(val_df), len(test_df))
print("Classes:", num_classes)
debug_path_resolution(train_df)

Loaded seed: 13
Split dir: /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Split sizes: 9261 1984 1985
Classes: 14
=== Path resolution sanity check ===
BASE_DIR: /home/ding-zhang/Dongmei/DATA255/Project
Top-level dataset/ exists: False
data/raw dataset/ exists: True
  exists=True raw=dataset/mode/9234303ea1b3437acd91437fb29df533.jpg
         resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/9234303ea1b3437acd91437fb29df533.jpg
  exists=True raw=dataset/conservative/deec85adc5c257cecbecd14ad2c6241999eb1fc4.jpg
         resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/conservative/deec85adc5c257cecbecd14ad2c6241999eb1fc4.jpg
  exists=True raw=dataset/retro/a8a3be106a52c363efff4aad6bd427c0.jpg
         resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/a8a3be106a52c363efff4aad6bd427c0.jpg
  exists=True raw=dataset/conservative/m_93b41ab3faace1063459db9e7bab6137bf3d7dca1449738231.jpg
         resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/conservative/m_93b41ab3faace1063459db9e7bab6137bf3d7dca1449738231.jpg
  exists=True raw=dataset/ethnic/20140328180630283_276.jpg
         resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/ethnic/20140328180630283_276.jpg
Resolved files found: 5/5

## 2. Dataset, Model, And Training Helpers

This section defines the reusable components for the ViT-B/16 image-only experiments:
- dataset loading
- `timm` ViT-B/16 train and evaluation transforms
- full-backbone fine-tuning with a CLIP-matched MLP classifier head
- optimizer parameter groups for `backbone_lr` and `head_lr`
- training, validation, prediction saving, and summary utilities

In [4]:
def make_seed_worker(base_seed):
    def seed_worker(worker_id):
        worker_seed = base_seed + worker_id
        np.random.seed(worker_seed)
        random.seed(worker_seed)

    return seed_worker


class FashionImageOnlyDataset(Dataset):
    def __init__(self, df, style_to_idx, transform=None, base_dir=None):
        self.df = df.reset_index(drop=True)
        self.style_to_idx = style_to_idx
        self.transform = transform
        self.base_dir = Path(base_dir) if base_dir is not None else None
        self.valid_indices = []
        self.missing_examples = []

        for idx in range(len(self.df)):
            row = self.df.iloc[idx]
            resolved_path = resolve_image_path(row["image_path"], self.base_dir or PROJECT_ROOT)
            if os.path.exists(resolved_path):
                self.valid_indices.append(idx)
            elif len(self.missing_examples) < 5:
                self.missing_examples.append((str(row["image_path"]), resolved_path))

        print(f"Dataset initialized with {len(self.valid_indices)} valid samples (out of {len(self.df)})")
        if self.missing_examples:
            print("  Missing image examples:")
            for raw_path, resolved_path in self.missing_examples:
                print(f"    raw={raw_path}")
                print(f"    resolved={resolved_path}")

    def __len__(self):
        return len(self.valid_indices)

    def __getitem__(self, idx):
        actual_idx = self.valid_indices[idx]
        row = self.df.iloc[actual_idx]
        image_path = resolve_image_path(row["image_path"], self.base_dir or PROJECT_ROOT)
        image = Image.open(image_path).convert("RGB")
        if self.transform:
            image = self.transform(image)

        style = row["style"]
        label = self.style_to_idx[style]
        return {
            "image": image,
            "label": label,
            "style": style,
            "image_path": image_path,
        }


def build_vit_transforms(model_name):
    tmp_model = timm.create_model(model_name, pretrained=True, num_classes=0)
    data_config = get_timm_data_config(tmp_model)
    train_transform = create_transform(**data_config, is_training=True)
    eval_transform = create_transform(**data_config, is_training=False)
    del tmp_model
    return data_config, train_transform, eval_transform


class ViTImageOnlyClassifier(nn.Module):
    def __init__(self, model_name, num_classes, dropout=0.5):
        super().__init__()
        self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0)
        feature_dim = self.backbone.num_features
        self.classifier = nn.Sequential(
            nn.Linear(feature_dim, 256),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, num_classes),
        )

    def forward(self, images):
        features = self.backbone(images)
        return self.classifier(features)


def build_optimizer(model, backbone_lr, head_lr, weight_decay):
    return torch.optim.AdamW(
        [
            {"params": model.backbone.parameters(), "lr": backbone_lr, "name": "backbone"},
            {"params": model.classifier.parameters(), "lr": head_lr, "name": "head"},
        ],
        weight_decay=weight_decay,
    )


def train_epoch(model, data_loader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    correct = 0
    total = 0

    for batch in tqdm(data_loader, desc="Training", leave=False):
        images = batch["image"].to(device)
        labels = batch["label"].to(device)

        optimizer.zero_grad(set_to_none=True)
        logits = model(images)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        predicted = logits.argmax(dim=1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    accuracy = correct / total if total > 0 else 0.0
    avg_loss = total_loss / max(len(data_loader), 1)
    return avg_loss, accuracy


def validate_epoch(model, data_loader, criterion, device):
    model.eval()
    total_loss = 0.0
    correct = 0
    total = 0
    all_predictions = []
    all_labels = []

    with torch.no_grad():
        for batch in tqdm(data_loader, desc="Validation", leave=False):
            images = batch["image"].to(device)
            labels = batch["label"].to(device)

            logits = model(images)
            loss = criterion(logits, labels)

            total_loss += loss.item()
            predicted = logits.argmax(dim=1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            all_predictions.extend(predicted.cpu().numpy().tolist())
            all_labels.extend(labels.cpu().numpy().tolist())

    accuracy = correct / total if total > 0 else 0.0
    avg_loss = total_loss / max(len(data_loader), 1)
    macro_f1 = f1_score(all_labels, all_predictions, average="macro", zero_division=0)
    return avg_loss, accuracy, all_predictions, all_labels, macro_f1


def evaluate_with_per_class_metrics(model, data_loader, criterion, device, all_styles):
    model.eval()
    total_loss = 0.0
    correct = 0
    total = 0
    all_predictions = []
    all_labels = []
    all_image_paths = []
    all_style_names = []

    with torch.no_grad():
        for batch in tqdm(data_loader, desc="Evaluating", leave=False):
            images = batch["image"].to(device)
            labels = batch["label"].to(device)

            logits = model(images)
            loss = criterion(logits, labels)

            total_loss += loss.item()
            predicted = logits.argmax(dim=1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

            all_predictions.extend(predicted.cpu().numpy().tolist())
            all_labels.extend(labels.cpu().numpy().tolist())
            all_image_paths.extend([str(x) for x in batch["image_path"]])
            all_style_names.extend([str(x) for x in batch["style"]])

    accuracy = correct / total if total > 0 else 0.0
    avg_loss = total_loss / max(len(data_loader), 1)
    macro_f1 = f1_score(all_labels, all_predictions, average="macro", zero_division=0)
    macro_precision = precision_score(all_labels, all_predictions, average="macro", zero_division=0)
    macro_recall = recall_score(all_labels, all_predictions, average="macro", zero_division=0)

    per_class_f1 = f1_score(all_labels, all_predictions, average=None, zero_division=0)
    per_class_precision = precision_score(all_labels, all_predictions, average=None, zero_division=0)
    per_class_recall = recall_score(all_labels, all_predictions, average=None, zero_division=0)

    labels_np = np.array(all_labels)
    predictions_np = np.array(all_predictions)
    per_class_accuracy = []
    for class_idx in range(len(all_styles)):
        class_mask = labels_np == class_idx
        if np.sum(class_mask) > 0:
            class_acc = float(np.sum((predictions_np == class_idx) & class_mask) / np.sum(class_mask))
        else:
            class_acc = 0.0
        per_class_accuracy.append(class_acc)

    per_class_f1_dict = {all_styles[i]: float(per_class_f1[i]) for i in range(len(all_styles))}
    per_class_precision_dict = {all_styles[i]: float(per_class_precision[i]) for i in range(len(all_styles))}
    per_class_recall_dict = {all_styles[i]: float(per_class_recall[i]) for i in range(len(all_styles))}
    per_class_accuracy_dict = {all_styles[i]: float(per_class_accuracy[i]) for i in range(len(all_styles))}

    return (
        avg_loss,
        accuracy,
        all_predictions,
        all_labels,
        macro_f1,
        macro_precision,
        macro_recall,
        per_class_f1_dict,
        per_class_precision_dict,
        per_class_recall_dict,
        per_class_accuracy_dict,
        all_image_paths,
        all_style_names,
    )


def save_learning_curves(train_losses, val_losses, train_accs, val_accs, val_macro_f1s, backbone_lrs, head_lrs, best_epoch, output_path, seed):
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    axes[0, 0].plot(train_losses, label="Train Loss", color="blue", linewidth=2)
    axes[0, 0].plot(val_losses, label="Val Loss", color="red", linewidth=2)
    axes[0, 0].axvline(x=best_epoch - 1, color="green", linestyle="--", alpha=0.7)
    axes[0, 0].set_title("Training and Validation Loss")
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)

    axes[0, 1].plot(train_accs, label="Train Acc", color="blue", linewidth=2)
    axes[0, 1].plot(val_accs, label="Val Acc", color="red", linewidth=2)
    axes[0, 1].axvline(x=best_epoch - 1, color="green", linestyle="--", alpha=0.7)
    axes[0, 1].set_title("Training and Validation Accuracy")
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)

    axes[1, 0].plot(val_macro_f1s, label="Val Macro F1", color="green", linewidth=2)
    axes[1, 0].axvline(x=best_epoch - 1, color="red", linestyle="--", alpha=0.7)
    axes[1, 0].set_title("Validation Macro F1")
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)

    axes[1, 1].plot(head_lrs, label="Head LR", color="purple", linewidth=2)
    axes[1, 1].plot(backbone_lrs, label="Backbone LR", color="orange", linewidth=2)
    axes[1, 1].set_title("Learning Rate Schedule")
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)

    plt.suptitle(f"ViT-B/16 Learning Curves - Seed {seed}", fontsize=14, y=1.02)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close()


def run_vit_trial(config, seed=DEFAULT_SEED, save_as_seed_result=False):
    set_seed(MODEL_INIT_SEED)
    split_dir, train_df, val_df, test_df = load_split_csvs(seed)

    data_config, train_transform, eval_transform = build_vit_transforms(config.get("model_name", MODEL_NAME))
    model = ViTImageOnlyClassifier(
        model_name=config.get("model_name", MODEL_NAME),
        num_classes=num_classes,
        dropout=config["dropout"],
    ).to(DEVICE)

    trainable_names = [name for name, param in model.named_parameters() if param.requires_grad]
    trainable_param_count = sum(param.numel() for param in model.parameters() if param.requires_grad)
    total_param_count = sum(param.numel() for param in model.parameters())

    print("\n=== Trainable parameter summary ===")
    print("Trial:", config["name"])
    print("Model:", config.get("model_name", MODEL_NAME))
    print("Trainable parameters:", trainable_param_count)
    for name in trainable_names[:20]:
        print("  ", name)
    if len(trainable_names) > 20:
        print("  ...")

    train_dataset = FashionImageOnlyDataset(train_df, style_to_idx, train_transform, base_dir=BASE_DIR)
    val_dataset = FashionImageOnlyDataset(val_df, style_to_idx, eval_transform, base_dir=BASE_DIR)
    test_dataset = FashionImageOnlyDataset(test_df, style_to_idx, eval_transform, base_dir=BASE_DIR)

    loader_seed = MODEL_INIT_SEED + seed
    generator = torch.Generator()
    generator.manual_seed(loader_seed)
    worker_init_fn = make_seed_worker(loader_seed)

    train_loader = DataLoader(
        train_dataset,
        batch_size=config["batch_size"],
        shuffle=True,
        num_workers=NUM_WORKERS,
        generator=generator,
        worker_init_fn=worker_init_fn,
    )
    val_loader = DataLoader(val_dataset, batch_size=config["batch_size"], shuffle=False, num_workers=NUM_WORKERS)
    test_loader = DataLoader(test_dataset, batch_size=config["batch_size"], shuffle=False, num_workers=NUM_WORKERS)

    train_valid_df = train_dataset.df.iloc[train_dataset.valid_indices]
    class_weights = compute_class_weight(
        class_weight="balanced",
        classes=np.array(list(style_to_idx.values())),
        y=train_valid_df["style"].map(style_to_idx).values,
    )
    class_weights = torch.FloatTensor(class_weights).to(DEVICE)

    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = build_optimizer(model, config["backbone_lr"], config["head_lr"], config["weight_decay"])
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config["max_epochs"])

    train_losses = []
    val_losses = []
    train_accs = []
    val_accs = []
    val_macro_f1s = []
    backbone_lrs = []
    head_lrs = []

    best_val_macro_f1 = -1.0
    min_val_loss = float("inf")
    best_epoch = 0
    best_train_loss = None
    best_train_acc = None
    best_val_loss_at_epoch = None
    best_val_acc_at_epoch = None
    patience_counter = 0
    early_stopped = False
    start_time = time.time()

    if save_as_seed_result:
        model_path = ARTIFACTS_DIR / "models" / f"seed_{seed}_best_model.pth"
        curve_path = ARTIFACTS_DIR / "learning_curves" / f"seed_{seed}_learning_curves.png"
        result_path = METRICS_DIR / "experiments" / f"seed_{seed}_results.json"
    else:
        model_path = ARTIFACTS_DIR / "trial_models" / f"{config['name']}_seed_{seed}.pth"
        curve_path = ARTIFACTS_DIR / "trial_learning_curves" / f"{config['name']}_seed_{seed}.png"
        result_path = METRICS_DIR / "trials" / f"{config['name']}_seed_{seed}.json"

    print(f"\n{'=' * 70}")
    print(f"Running trial {config['name']} on seed {seed}")
    print(f"Loaded CSVs from {split_dir}")
    print(f"Train/Val/Test: {len(train_df)} / {len(val_df)} / {len(test_df)}")
    print(f"{'=' * 70}")

    for epoch in range(config["max_epochs"]):
        train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, DEVICE)
        val_loss, val_acc, _, _, val_macro_f1 = validate_epoch(model, val_loader, criterion, DEVICE)

        current_backbone_lr = 0.0
        current_head_lr = 0.0
        for group in optimizer.param_groups:
            if group.get("name") == "backbone":
                current_backbone_lr = float(group["lr"])
            else:
                current_head_lr = float(group["lr"])

        backbone_lrs.append(current_backbone_lr)
        head_lrs.append(current_head_lr)
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_accs.append(train_acc)
        val_accs.append(val_acc)
        val_macro_f1s.append(val_macro_f1)

        print(
            f"Epoch {epoch + 1}/{config['max_epochs']}: "
            f"train_loss={train_loss:.4f} "
            f"val_loss={val_loss:.4f} "
            f"val_macro_f1={val_macro_f1:.4f} "
            f"backbone_lr={current_backbone_lr:.2e} "
            f"head_lr={current_head_lr:.2e}"
        )

        if val_macro_f1 > best_val_macro_f1:
            best_val_macro_f1 = val_macro_f1
            best_epoch = epoch + 1
            best_train_loss = train_loss
            best_train_acc = train_acc
            best_val_loss_at_epoch = val_loss
            best_val_acc_at_epoch = val_acc
            patience_counter = 0
            torch.save(model.state_dict(), model_path)
        else:
            patience_counter += 1

        if val_loss < min_val_loss:
            min_val_loss = val_loss

        scheduler.step()

        if patience_counter >= config["patience"]:
            early_stopped = True
            print(f"Early stopping at epoch {epoch + 1}")
            break

    total_time = time.time() - start_time
    model.load_state_dict(torch.load(model_path, map_location=DEVICE))

    (
        val_loss,
        val_acc,
        val_predictions,
        val_labels,
        val_macro_f1,
        val_macro_precision,
        val_macro_recall,
        val_per_class_f1,
        val_per_class_precision,
        val_per_class_recall,
        val_per_class_accuracy,
        val_image_paths,
        val_styles,
    ) = evaluate_with_per_class_metrics(model, val_loader, criterion, DEVICE, all_styles)

    (
        test_loss,
        test_acc,
        test_predictions,
        test_labels,
        test_macro_f1,
        test_macro_precision,
        test_macro_recall,
        test_per_class_f1,
        test_per_class_precision,
        test_per_class_recall,
        test_per_class_accuracy,
        test_image_paths,
        test_styles,
    ) = evaluate_with_per_class_metrics(model, test_loader, criterion, DEVICE, all_styles)

    recomputed_val_loss_best_checkpoint = float(val_loss)
    recomputed_val_macro_f1_best_checkpoint = float(val_macro_f1)
    val_loss_at_best_epoch = float(best_val_loss_at_epoch) if best_val_loss_at_epoch is not None else recomputed_val_loss_best_checkpoint
    val_accuracy_at_best_epoch = float(best_val_acc_at_epoch) if best_val_acc_at_epoch is not None else float(val_acc)
    final_val_loss = float(val_losses[-1]) if val_losses else recomputed_val_loss_best_checkpoint
    overfitting_detected = final_val_loss > val_loss_at_best_epoch * 1.05
    train_val_loss_gap = float(best_train_loss - val_loss_at_best_epoch) if best_train_loss is not None else 0.0

    save_learning_curves(
        train_losses,
        val_losses,
        train_accs,
        val_accs,
        val_macro_f1s,
        backbone_lrs,
        head_lrs,
        best_epoch,
        curve_path,
        seed,
    )

    results = {
        "experiment_id": f"seed_{seed}",
        "seed_value": seed,
        "seed_index": None,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "model_type": "image_only_vit_b16_finetuned",
        "trial_name": config["name"],
        "configuration": {
            "model_name": config.get("model_name", MODEL_NAME),
            "pretrained": True,
            "batch_size": config["batch_size"],
            "dropout": config["dropout"],
            "weight_decay": config["weight_decay"],
            "max_epochs": config["max_epochs"],
            "early_stopping_patience": config["patience"],
            "model_init_seed": MODEL_INIT_SEED,
            "data_split_seed": seed,
            "split_source": "csv",
            "backbone_lr": config["backbone_lr"],
            "head_lr": config["head_lr"],
            "input_size": list(data_config.get("input_size", (3, 224, 224))),
            "mean": list(data_config.get("mean", (0.5, 0.5, 0.5))),
            "std": list(data_config.get("std", (0.5, 0.5, 0.5))),
            "interpolation": str(data_config.get("interpolation")),
            "crop_pct": data_config.get("crop_pct"),
        },
        "training_info": {
            "total_epochs": len(train_losses),
            "best_epoch": best_epoch,
            "early_stopped": early_stopped,
            "total_time_minutes": float(total_time / 60.0),
            "trainable_parameter_count": int(trainable_param_count),
            "total_parameter_count": int(total_param_count),
            "train_loss_at_best_epoch": float(best_train_loss) if best_train_loss is not None else None,
            "train_accuracy_at_best_epoch": float(best_train_acc) if best_train_acc is not None else None,
        },
        "validation_metrics": {
            "best_val_macro_f1": float(best_val_macro_f1),
            "best_val_accuracy": float(val_accuracy_at_best_epoch),
            "best_val_macro_precision": float(val_macro_precision),
            "best_val_macro_recall": float(val_macro_recall),
            "val_loss_at_best_epoch": float(val_loss_at_best_epoch),
            "val_accuracy_at_best_epoch": float(val_accuracy_at_best_epoch),
            "recomputed_val_macro_f1_best_checkpoint": float(recomputed_val_macro_f1_best_checkpoint),
            "recomputed_val_loss_best_checkpoint": float(recomputed_val_loss_best_checkpoint),
            "min_val_loss": float(min_val_loss),
            "predictions": [int(x) for x in val_predictions],
            "labels": [int(x) for x in val_labels],
            "image_paths": [str(x) for x in val_image_paths],
            "styles": [str(x) for x in val_styles],
            "per_class_metrics": {
                "f1": val_per_class_f1,
                "precision": val_per_class_precision,
                "recall": val_per_class_recall,
                "accuracy": val_per_class_accuracy,
            },
        },
        "test_metrics": {
            "test_macro_f1": float(test_macro_f1),
            "test_accuracy": float(test_acc),
            "test_macro_precision": float(test_macro_precision),
            "test_macro_recall": float(test_macro_recall),
            "test_loss": float(test_loss),
            "predictions": [int(x) for x in test_predictions],
            "labels": [int(x) for x in test_labels],
            "image_paths": [str(x) for x in test_image_paths],
            "styles": [str(x) for x in test_styles],
            "per_class_metrics": {
                "f1": test_per_class_f1,
                "precision": test_per_class_precision,
                "recall": test_per_class_recall,
                "accuracy": test_per_class_accuracy,
            },
        },
        "overfitting_analysis": {
            "overfitting_detected": overfitting_detected,
            "val_loss_at_best_epoch": float(val_loss_at_best_epoch),
            "min_val_loss": float(min_val_loss),
            "final_val_loss": float(final_val_loss),
            "train_val_loss_gap": float(train_val_loss_gap),
        },
        "training_curves": {
            "train_losses": [float(x) for x in train_losses],
            "val_losses": [float(x) for x in val_losses],
            "train_accs": [float(x) for x in train_accs],
            "val_accs": [float(x) for x in val_accs],
            "val_macro_f1s": [float(x) for x in val_macro_f1s],
            "backbone_learning_rates": [float(x) for x in backbone_lrs],
            "head_learning_rates": [float(x) for x in head_lrs],
        },
        "data_split_info": {
            "train_size_raw": len(train_df),
            "val_size_raw": len(val_df),
            "test_size_raw": len(test_df),
            "train_size_valid": len(train_dataset),
            "val_size_valid": len(val_dataset),
            "test_size_valid": len(test_dataset),
        },
        "trainable_parameters": {
            "trainable_parameter_count": int(trainable_param_count),
            "total_parameter_count": int(total_param_count),
            "trainable_parameter_names_preview": trainable_names[:20],
            "full_backbone_finetuning": True,
        },
    }

    with open(result_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    print(f"Saved result JSON to {result_path}")
    print(f"Best val macro F1: {results['validation_metrics']['best_val_macro_f1']:.4f}")
    print(f"Test macro F1: {results['test_metrics']['test_macro_f1']:.4f}")
    return results

## 2.5 Smoke Test

This section was used as an initial smoke test to confirm that:
- the `timm` transforms load correctly
- the model produces 14-class logits
- training runs without path or environment errors
- JSON outputs and learning-curve artifacts save to the expected pilot folders

This check was used to validate the setup before running the full one-seed search.

In [5]:
RUN_SMOKE_TEST = True

smoke_test_config = TRIAL_CONFIGS[0].copy()
smoke_test_config["name"] = "smoke_test_vit_b16"
smoke_test_config["max_epochs"] = 2
smoke_test_config["patience"] = 2

if RUN_SMOKE_TEST:
    smoke_test_result = run_vit_trial(smoke_test_config, seed=DEFAULT_SEED, save_as_seed_result=False)
    print("\nSmoke test complete.")
    print("Best val macro F1:", smoke_test_result["validation_metrics"]["best_val_macro_f1"])
    print("Test macro F1:", smoke_test_result["test_metrics"]["test_macro_f1"])
else:
    print("Smoke test skipped. Set RUN_SMOKE_TEST = True to run the 2-epoch sanity check.")

=== Trainable parameter summary ===
Trial: smoke_test_vit_b16
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial smoke_test_vit_b16 on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/2: train_loss=2.0970 val_loss=1.1276 val_macro_f1=0.6507 backbone_lr=5.00e-06 head_lr=1.00e-04

Epoch 2/2: train_loss=1.3870 val_loss=0.8738 val_macro_f1=0.6946 backbone_lr=2.50e-06 head_lr=5.00e-05

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/trials/smoke_test_vit_b16_seed_13.json
Best val macro F1: 0.6946
Test macro F1: 0.7079

Smoke test complete.
Best val macro F1: 0.6946249089713162
Test macro F1: 0.7079402718422171

## 3. One-Seed Parameter Search

This section runs a small ViT-B/16 parameter search on one matched seed.

Configuration selection is **validation-only**: `BEST_CONFIG` is chosen using validation macro-F1 and validation loss, while test metrics are logged only for reference and are not used for model selection.

In [6]:
SEARCH_RESULTS = []
for trial_cfg in TRIAL_CONFIGS:
    result = run_vit_trial(trial_cfg, seed=DEFAULT_SEED, save_as_seed_result=False)
    SEARCH_RESULTS.append(
        {
            "trial_name": trial_cfg["name"],
            "best_val_macro_f1": result["validation_metrics"]["best_val_macro_f1"],
            "val_loss_at_best_epoch": result["validation_metrics"]["val_loss_at_best_epoch"],
            "min_val_loss": result["validation_metrics"]["min_val_loss"],
            "test_macro_f1": result["test_metrics"]["test_macro_f1"],
            "epochs": result["training_info"]["total_epochs"],
            "backbone_lr": trial_cfg["backbone_lr"],
            "head_lr": trial_cfg["head_lr"],
            "dropout": trial_cfg["dropout"],
            "weight_decay": trial_cfg["weight_decay"],
        }
    )


df_search = pd.DataFrame(SEARCH_RESULTS).sort_values(
    ["best_val_macro_f1", "val_loss_at_best_epoch", "epochs"],
    ascending=[False, True, True],
).reset_index(drop=True)

display_cols = [
    "trial_name",
    "best_val_macro_f1",
    "val_loss_at_best_epoch",
    "min_val_loss",
    "epochs",
    "backbone_lr",
    "head_lr",
    "dropout",
    "weight_decay",
]
display(df_search[display_cols])

BEST_CONFIG = next(cfg for cfg in TRIAL_CONFIGS if cfg["name"] == df_search.iloc[0]["trial_name"]).copy()
TOP2_CONFIG_NAMES = df_search.head(2)["trial_name"].tolist()
print("Best config from validation-only search:")
print(BEST_CONFIG)
print("Top 2 configs:", TOP2_CONFIG_NAMES)

=== Trainable parameter summary ===
Trial: vit_b16_lr5e6_head1e4
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial vit_b16_lr5e6_head1e4 on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.0922 val_loss=1.1225 val_macro_f1=0.6493 backbone_lr=5.00e-06 head_lr=1.00e-04

Epoch 2/15: train_loss=1.3227 val_loss=0.7818 val_macro_f1=0.7230 backbone_lr=4.95e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=1.0781 val_loss=0.6603 val_macro_f1=0.7684 backbone_lr=4.78e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.9392 val_loss=0.6163 val_macro_f1=0.7885 backbone_lr=4.52e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.8406 val_loss=0.6336 val_macro_f1=0.7784 backbone_lr=4.17e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.7904 val_loss=0.5596 val_macro_f1=0.8006 backbone_lr=3.75e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.7011 val_loss=0.5702 val_macro_f1=0.7987 backbone_lr=3.27e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.6775 val_loss=0.5553 val_macro_f1=0.8067 backbone_lr=2.76e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.6417 val_loss=0.5310 val_macro_f1=0.8202 backbone_lr=2.24e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.6046 val_loss=0.5303 val_macro_f1=0.8215 backbone_lr=1.73e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.5850 val_loss=0.5237 val_macro_f1=0.8232 backbone_lr=1.25e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.5621 val_loss=0.5268 val_macro_f1=0.8195 backbone_lr=8.27e-07 head_lr=1.65e-05

Epoch 13/15: train_loss=0.5684 val_loss=0.5217 val_macro_f1=0.8191 backbone_lr=4.77e-07 head_lr=9.55e-06

Epoch 14/15: train_loss=0.5405 val_loss=0.5132 val_macro_f1=0.8238 backbone_lr=2.16e-07 head_lr=4.32e-06

Epoch 15/15: train_loss=0.5340 val_loss=0.5127 val_macro_f1=0.8257 backbone_lr=5.46e-08 head_lr=1.09e-06

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/trials/vit_b16_lr5e6_head1e4_seed_13.json
Best val macro F1: 0.8257
Test macro F1: 0.8296

=== Trainable parameter summary ===
Trial: vit_b16_lr1e5_head1e4
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial vit_b16_lr1e5_head1e4 on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.0154 val_loss=1.0615 val_macro_f1=0.6685 backbone_lr=1.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=1.2637 val_loss=0.7342 val_macro_f1=0.7382 backbone_lr=9.89e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=1.0130 val_loss=0.6483 val_macro_f1=0.7716 backbone_lr=9.57e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.8852 val_loss=0.6042 val_macro_f1=0.7901 backbone_lr=9.05e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.7713 val_loss=0.6489 val_macro_f1=0.7794 backbone_lr=8.35e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.7244 val_loss=0.5579 val_macro_f1=0.8055 backbone_lr=7.50e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.6270 val_loss=0.5431 val_macro_f1=0.8217 backbone_lr=6.55e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.5917 val_loss=0.5550 val_macro_f1=0.8180 backbone_lr=5.52e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.5469 val_loss=0.5484 val_macro_f1=0.8227 backbone_lr=4.48e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.5052 val_loss=0.5428 val_macro_f1=0.8255 backbone_lr=3.45e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.4725 val_loss=0.5296 val_macro_f1=0.8339 backbone_lr=2.50e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.4504 val_loss=0.5523 val_macro_f1=0.8306 backbone_lr=1.65e-06 head_lr=1.65e-05

Epoch 13/15: train_loss=0.4529 val_loss=0.5305 val_macro_f1=0.8327 backbone_lr=9.55e-07 head_lr=9.55e-06

Epoch 14/15: train_loss=0.4235 val_loss=0.5289 val_macro_f1=0.8346 backbone_lr=4.32e-07 head_lr=4.32e-06

Epoch 15/15: train_loss=0.4137 val_loss=0.5291 val_macro_f1=0.8325 backbone_lr=1.09e-07 head_lr=1.09e-06

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/trials/vit_b16_lr1e5_head1e4_seed_13.json
Best val macro F1: 0.8346
Test macro F1: 0.8291

=== Trainable parameter summary ===
Trial: vit_b16_lr2e5_head1e4
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial vit_b16_lr2e5_head1e4 on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=1.9523 val_loss=1.0041 val_macro_f1=0.6925 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=1.2371 val_loss=0.7637 val_macro_f1=0.7409 backbone_lr=1.98e-05 head_lr=9.89e-05

Epoch 3/15: train_loss=1.0007 val_loss=0.6635 val_macro_f1=0.7769 backbone_lr=1.91e-05 head_lr=9.57e-05

Epoch 4/15: train_loss=0.8576 val_loss=0.6154 val_macro_f1=0.7972 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 5/15: train_loss=0.7372 val_loss=0.6752 val_macro_f1=0.7854 backbone_lr=1.67e-05 head_lr=8.35e-05

Epoch 6/15: train_loss=0.6785 val_loss=0.6013 val_macro_f1=0.8000 backbone_lr=1.50e-05 head_lr=7.50e-05

Epoch 7/15: train_loss=0.5818 val_loss=0.5822 val_macro_f1=0.8058 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 8/15: train_loss=0.5431 val_loss=0.5834 val_macro_f1=0.8067 backbone_lr=1.10e-05 head_lr=5.52e-05

Epoch 9/15: train_loss=0.4851 val_loss=0.5981 val_macro_f1=0.8197 backbone_lr=8.95e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.4310 val_loss=0.5988 val_macro_f1=0.8256 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.3948 val_loss=0.5599 val_macro_f1=0.8323 backbone_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.3694 val_loss=0.5750 val_macro_f1=0.8287 backbone_lr=3.31e-06 head_lr=1.65e-05

Epoch 13/15: train_loss=0.3623 val_loss=0.5722 val_macro_f1=0.8277 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 14/15: train_loss=0.3323 val_loss=0.5680 val_macro_f1=0.8239 backbone_lr=8.65e-07 head_lr=4.32e-06

Epoch 15/15: train_loss=0.3206 val_loss=0.5669 val_macro_f1=0.8263 backbone_lr=2.19e-07 head_lr=1.09e-06
Early stopping at epoch 15

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/trials/vit_b16_lr2e5_head1e4_seed_13.json
Best val macro F1: 0.8323
Test macro F1: 0.8239

,trial_name,best_val_macro_f1,val_loss_at_best_epoch,min_val_loss,epochs,backbone_lr,head_lr,dropout,weight_decay
0,vit_b16_lr1e5_head1e4,0.834613,0.528909,0.528909,15,0.000010,0.0001,0.5,0.0001
1,vit_b16_lr2e5_head1e4,0.832338,0.559944,0.559944,15,0.000020,0.0001,0.5,0.0001
2,vit_b16_lr5e6_head1e4,0.825737,0.512654,0.512654,15,0.000005,0.0001,0.5,0.0001

Best config from validation-only search:
{'name': 'vit_b16_lr1e5_head1e4', 'model_name': 'vit_base_patch16_224', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'backbone_lr': 1e-05, 'head_lr': 0.0001}
Top 2 configs: ['vit_b16_lr1e5_head1e4', 'vit_b16_lr2e5_head1e4']

In [7]:
# ============================================================
# 3.5 Shortlist the top 2 configs on 3 more seeds
# Uses the existing seed-13 trial results if present.
# Edit SHORTLIST_NEW_SEEDS if you want different additional seeds.
# ============================================================

SHORTLIST_CONFIG_NAMES = df_search.head(2)["trial_name"].tolist()
SHORTLIST_NEW_SEEDS = [14, 17, 53]
SHORTLIST_ALL_SEEDS = [DEFAULT_SEED] + SHORTLIST_NEW_SEEDS  # seed 13 + 3 more

trial_cfg_lookup = {cfg["name"]: cfg for cfg in TRIAL_CONFIGS}
SHORTLIST_CONFIGS = [trial_cfg_lookup[name].copy() for name in SHORTLIST_CONFIG_NAMES]

def load_existing_trial_result(trial_name, seed):
    result_path = METRICS_DIR / "trials" / f"{trial_name}_seed_{seed}.json"
    if result_path.exists():
        with open(result_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return None

SHORTLIST_RUN_RESULTS = []

for trial_cfg in SHORTLIST_CONFIGS:
    for seed in SHORTLIST_ALL_SEEDS:
        existing_result = load_existing_trial_result(trial_cfg["name"], seed)

        if existing_result is not None:
            result = existing_result
            print(f"Reusing existing result: {trial_cfg['name']} seed {seed}")
        else:
            result = run_vit_trial(trial_cfg, seed=seed, save_as_seed_result=False)

        SHORTLIST_RUN_RESULTS.append(
            {
                "trial_name": trial_cfg["name"],
                "seed": seed,
                "best_val_macro_f1": result["validation_metrics"]["best_val_macro_f1"],
                "val_loss_at_best_epoch": result["validation_metrics"]["val_loss_at_best_epoch"],
                "min_val_loss": result["validation_metrics"]["min_val_loss"],
                "test_macro_f1": result["test_metrics"]["test_macro_f1"],
                "epochs": result["training_info"]["total_epochs"],
                "best_epoch": result["training_info"]["best_epoch"],
                "early_stopped": result["training_info"]["early_stopped"],
                "total_time_minutes": result["training_info"]["total_time_minutes"],
                "backbone_lr": trial_cfg["backbone_lr"],
                "head_lr": trial_cfg["head_lr"],
                "dropout": trial_cfg["dropout"],
                "weight_decay": trial_cfg["weight_decay"],
            }
        )

df_shortlist_runs = (
    pd.DataFrame(SHORTLIST_RUN_RESULTS)
    .sort_values(["trial_name", "seed"])
    .reset_index(drop=True)
)

print("\nPer-seed shortlist results:")
display(
    df_shortlist_runs[
        [
            "trial_name",
            "seed",
            "best_val_macro_f1",
            "val_loss_at_best_epoch",
            "test_macro_f1",
            "epochs",
            "best_epoch",
            "early_stopped",
            "total_time_minutes",
            "backbone_lr",
            "head_lr",
        ]
    ]
)

df_shortlist_summary = (
    df_shortlist_runs
    .groupby("trial_name", as_index=False)
    .agg(
        mean_val_macro_f1=("best_val_macro_f1", "mean"),
        std_val_macro_f1=("best_val_macro_f1", "std"),
        mean_val_loss_at_best_epoch=("val_loss_at_best_epoch", "mean"),
        mean_test_macro_f1=("test_macro_f1", "mean"),
        std_test_macro_f1=("test_macro_f1", "std"),
        mean_epochs=("epochs", "mean"),
        mean_best_epoch=("best_epoch", "mean"),
        mean_time_minutes=("total_time_minutes", "mean"),
        backbone_lr=("backbone_lr", "first"),
        head_lr=("head_lr", "first"),
        dropout=("dropout", "first"),
        weight_decay=("weight_decay", "first"),
    )
)

df_shortlist_summary["std_val_macro_f1"] = df_shortlist_summary["std_val_macro_f1"].fillna(0.0)
df_shortlist_summary["std_test_macro_f1"] = df_shortlist_summary["std_test_macro_f1"].fillna(0.0)

df_shortlist_summary = df_shortlist_summary.sort_values(
    ["mean_val_macro_f1", "std_val_macro_f1", "mean_val_loss_at_best_epoch"],
    ascending=[False, True, True],
).reset_index(drop=True)

print("\nAggregated shortlist summary (selection is validation-only):")
display(
    df_shortlist_summary[
        [
            "trial_name",
            "mean_val_macro_f1",
            "std_val_macro_f1",
            "mean_val_loss_at_best_epoch",
            "mean_test_macro_f1",
            "std_test_macro_f1",
            "mean_epochs",
            "mean_best_epoch",
            "mean_time_minutes",
            "backbone_lr",
            "head_lr",
        ]
    ]
)

BEST_CONFIG = next(
    cfg for cfg in TRIAL_CONFIGS if cfg["name"] == df_shortlist_summary.iloc[0]["trial_name"]
).copy()

print("\nSelected BEST_CONFIG after shortlist:")
print(BEST_CONFIG)
print(f"Section 4 will now rerun this config cleanly on DEFAULT_SEED={DEFAULT_SEED}.")

Reusing existing result: vit_b16_lr1e5_head1e4 seed 13

=== Trainable parameter summary ===
Trial: vit_b16_lr1e5_head1e4
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9233 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
Dataset initialized with 1982 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg

======================================================================
Running trial vit_b16_lr1e5_head1e4 on seed 14
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_14
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.0221 val_loss=1.0390 val_macro_f1=0.6832 backbone_lr=1.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=1.2470 val_loss=0.7456 val_macro_f1=0.7366 backbone_lr=9.89e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=1.0259 val_loss=0.6418 val_macro_f1=0.7763 backbone_lr=9.57e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.8750 val_loss=0.5739 val_macro_f1=0.8041 backbone_lr=9.05e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.7870 val_loss=0.5470 val_macro_f1=0.8119 backbone_lr=8.35e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.6871 val_loss=0.5225 val_macro_f1=0.8250 backbone_lr=7.50e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.6266 val_loss=0.5385 val_macro_f1=0.8224 backbone_lr=6.55e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.5829 val_loss=0.5442 val_macro_f1=0.8127 backbone_lr=5.52e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.5507 val_loss=0.4956 val_macro_f1=0.8377 backbone_lr=4.48e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.5152 val_loss=0.5108 val_macro_f1=0.8378 backbone_lr=3.45e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.4660 val_loss=0.4970 val_macro_f1=0.8357 backbone_lr=2.50e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.4673 val_loss=0.4985 val_macro_f1=0.8405 backbone_lr=1.65e-06 head_lr=1.65e-05

Epoch 13/15: train_loss=0.4383 val_loss=0.4923 val_macro_f1=0.8424 backbone_lr=9.55e-07 head_lr=9.55e-06

Epoch 14/15: train_loss=0.4349 val_loss=0.4947 val_macro_f1=0.8422 backbone_lr=4.32e-07 head_lr=4.32e-06

Epoch 15/15: train_loss=0.4269 val_loss=0.4936 val_macro_f1=0.8422 backbone_lr=1.09e-07 head_lr=1.09e-06

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/trials/vit_b16_lr1e5_head1e4_seed_14.json
Best val macro F1: 0.8424
Test macro F1: 0.8289

=== Trainable parameter summary ===
Trial: vit_b16_lr1e5_head1e4
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial vit_b16_lr1e5_head1e4 on seed 17
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_17
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.0075 val_loss=1.0551 val_macro_f1=0.6188 backbone_lr=1.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=1.2272 val_loss=0.7499 val_macro_f1=0.7515 backbone_lr=9.89e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=1.0010 val_loss=0.6246 val_macro_f1=0.7874 backbone_lr=9.57e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.8696 val_loss=0.6357 val_macro_f1=0.7766 backbone_lr=9.05e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.7491 val_loss=0.6283 val_macro_f1=0.7980 backbone_lr=8.35e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.6890 val_loss=0.5971 val_macro_f1=0.8060 backbone_lr=7.50e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.6357 val_loss=0.5606 val_macro_f1=0.8185 backbone_lr=6.55e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.5796 val_loss=0.5982 val_macro_f1=0.8118 backbone_lr=5.52e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.5124 val_loss=0.5731 val_macro_f1=0.8201 backbone_lr=4.48e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.5012 val_loss=0.5624 val_macro_f1=0.8247 backbone_lr=3.45e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.4627 val_loss=0.5561 val_macro_f1=0.8280 backbone_lr=2.50e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.4541 val_loss=0.5556 val_macro_f1=0.8328 backbone_lr=1.65e-06 head_lr=1.65e-05

Epoch 13/15: train_loss=0.4490 val_loss=0.5465 val_macro_f1=0.8335 backbone_lr=9.55e-07 head_lr=9.55e-06

Epoch 14/15: train_loss=0.4253 val_loss=0.5409 val_macro_f1=0.8308 backbone_lr=4.32e-07 head_lr=4.32e-06

Epoch 15/15: train_loss=0.4144 val_loss=0.5465 val_macro_f1=0.8345 backbone_lr=1.09e-07 head_lr=1.09e-06

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/trials/vit_b16_lr1e5_head1e4_seed_17.json
Best val macro F1: 0.8345
Test macro F1: 0.8378

=== Trainable parameter summary ===
Trial: vit_b16_lr1e5_head1e4
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
Dataset initialized with 1977 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg

======================================================================
Running trial vit_b16_lr1e5_head1e4 on seed 53
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_53
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=2.0282 val_loss=1.0340 val_macro_f1=0.6800 backbone_lr=1.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=1.2590 val_loss=0.7660 val_macro_f1=0.7403 backbone_lr=9.89e-06 head_lr=9.89e-05

Epoch 3/15: train_loss=1.0204 val_loss=0.6941 val_macro_f1=0.7681 backbone_lr=9.57e-06 head_lr=9.57e-05

Epoch 4/15: train_loss=0.8677 val_loss=0.6407 val_macro_f1=0.7854 backbone_lr=9.05e-06 head_lr=9.05e-05

Epoch 5/15: train_loss=0.7603 val_loss=0.6390 val_macro_f1=0.7816 backbone_lr=8.35e-06 head_lr=8.35e-05

Epoch 6/15: train_loss=0.7041 val_loss=0.5741 val_macro_f1=0.8131 backbone_lr=7.50e-06 head_lr=7.50e-05

Epoch 7/15: train_loss=0.6261 val_loss=0.5684 val_macro_f1=0.8077 backbone_lr=6.55e-06 head_lr=6.55e-05

Epoch 8/15: train_loss=0.5867 val_loss=0.5524 val_macro_f1=0.8221 backbone_lr=5.52e-06 head_lr=5.52e-05

Epoch 9/15: train_loss=0.5328 val_loss=0.5803 val_macro_f1=0.8122 backbone_lr=4.48e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.4995 val_loss=0.5682 val_macro_f1=0.8160 backbone_lr=3.45e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.4523 val_loss=0.5716 val_macro_f1=0.8189 backbone_lr=2.50e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.4648 val_loss=0.5602 val_macro_f1=0.8171 backbone_lr=1.65e-06 head_lr=1.65e-05
Early stopping at epoch 12

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/trials/vit_b16_lr1e5_head1e4_seed_53.json
Best val macro F1: 0.8221
Test macro F1: 0.8174
Reusing existing result: vit_b16_lr2e5_head1e4 seed 13

=== Trainable parameter summary ===
Trial: vit_b16_lr2e5_head1e4
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9233 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
Dataset initialized with 1982 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg

======================================================================
Running trial vit_b16_lr2e5_head1e4 on seed 14
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_14
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=1.9326 val_loss=0.9314 val_macro_f1=0.7065 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=1.2039 val_loss=0.7254 val_macro_f1=0.7581 backbone_lr=1.98e-05 head_lr=9.89e-05

Epoch 3/15: train_loss=0.9890 val_loss=0.6434 val_macro_f1=0.7785 backbone_lr=1.91e-05 head_lr=9.57e-05

Epoch 4/15: train_loss=0.8495 val_loss=0.6081 val_macro_f1=0.8073 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 5/15: train_loss=0.7522 val_loss=0.5912 val_macro_f1=0.8025 backbone_lr=1.67e-05 head_lr=8.35e-05

Epoch 6/15: train_loss=0.6534 val_loss=0.5516 val_macro_f1=0.8188 backbone_lr=1.50e-05 head_lr=7.50e-05

Epoch 7/15: train_loss=0.5854 val_loss=0.6061 val_macro_f1=0.8039 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 8/15: train_loss=0.5227 val_loss=0.5805 val_macro_f1=0.8157 backbone_lr=1.10e-05 head_lr=5.52e-05

Epoch 9/15: train_loss=0.4848 val_loss=0.5391 val_macro_f1=0.8345 backbone_lr=8.95e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.4330 val_loss=0.5589 val_macro_f1=0.8257 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.3846 val_loss=0.5567 val_macro_f1=0.8380 backbone_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.3680 val_loss=0.5573 val_macro_f1=0.8356 backbone_lr=3.31e-06 head_lr=1.65e-05

Epoch 13/15: train_loss=0.3609 val_loss=0.5594 val_macro_f1=0.8373 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 14/15: train_loss=0.3371 val_loss=0.5586 val_macro_f1=0.8365 backbone_lr=8.65e-07 head_lr=4.32e-06

Epoch 15/15: train_loss=0.3326 val_loss=0.5575 val_macro_f1=0.8360 backbone_lr=2.19e-07 head_lr=1.09e-06
Early stopping at epoch 15

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/trials/vit_b16_lr2e5_head1e4_seed_14.json
Best val macro F1: 0.8380
Test macro F1: 0.8299

=== Trainable parameter summary ===
Trial: vit_b16_lr2e5_head1e4
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial vit_b16_lr2e5_head1e4 on seed 17
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_17
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=1.9292 val_loss=0.9869 val_macro_f1=0.6471 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=1.2171 val_loss=0.7863 val_macro_f1=0.7375 backbone_lr=1.98e-05 head_lr=9.89e-05

Epoch 3/15: train_loss=0.9957 val_loss=0.6745 val_macro_f1=0.7761 backbone_lr=1.91e-05 head_lr=9.57e-05

Epoch 4/15: train_loss=0.8557 val_loss=0.7002 val_macro_f1=0.7736 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 5/15: train_loss=0.7399 val_loss=0.6687 val_macro_f1=0.7856 backbone_lr=1.67e-05 head_lr=8.35e-05

Epoch 6/15: train_loss=0.6610 val_loss=0.6725 val_macro_f1=0.7919 backbone_lr=1.50e-05 head_lr=7.50e-05

Epoch 7/15: train_loss=0.5900 val_loss=0.6189 val_macro_f1=0.8070 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 8/15: train_loss=0.5306 val_loss=0.6602 val_macro_f1=0.8024 backbone_lr=1.10e-05 head_lr=5.52e-05

Epoch 9/15: train_loss=0.4506 val_loss=0.6290 val_macro_f1=0.8154 backbone_lr=8.95e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.4270 val_loss=0.6236 val_macro_f1=0.8209 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.3856 val_loss=0.6119 val_macro_f1=0.8251 backbone_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.3612 val_loss=0.6226 val_macro_f1=0.8296 backbone_lr=3.31e-06 head_lr=1.65e-05

Epoch 13/15: train_loss=0.3512 val_loss=0.6208 val_macro_f1=0.8281 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 14/15: train_loss=0.3382 val_loss=0.6145 val_macro_f1=0.8309 backbone_lr=8.65e-07 head_lr=4.32e-06

Epoch 15/15: train_loss=0.3185 val_loss=0.6183 val_macro_f1=0.8311 backbone_lr=2.19e-07 head_lr=1.09e-06

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/trials/vit_b16_lr2e5_head1e4_seed_17.json
Best val macro F1: 0.8311
Test macro F1: 0.8380

=== Trainable parameter summary ===
Trial: vit_b16_lr2e5_head1e4
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
Dataset initialized with 1977 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg

======================================================================
Running trial vit_b16_lr2e5_head1e4 on seed 53
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_53
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/15: train_loss=1.9541 val_loss=1.0077 val_macro_f1=0.6908 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/15: train_loss=1.2421 val_loss=0.7865 val_macro_f1=0.7206 backbone_lr=1.98e-05 head_lr=9.89e-05

Epoch 3/15: train_loss=1.0059 val_loss=0.6968 val_macro_f1=0.7614 backbone_lr=1.91e-05 head_lr=9.57e-05

Epoch 4/15: train_loss=0.8596 val_loss=0.6440 val_macro_f1=0.7777 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 5/15: train_loss=0.7393 val_loss=0.6733 val_macro_f1=0.7831 backbone_lr=1.67e-05 head_lr=8.35e-05

Epoch 6/15: train_loss=0.6880 val_loss=0.6245 val_macro_f1=0.8015 backbone_lr=1.50e-05 head_lr=7.50e-05

Epoch 7/15: train_loss=0.5844 val_loss=0.6319 val_macro_f1=0.7938 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 8/15: train_loss=0.5314 val_loss=0.5783 val_macro_f1=0.8221 backbone_lr=1.10e-05 head_lr=5.52e-05

Epoch 9/15: train_loss=0.4679 val_loss=0.6130 val_macro_f1=0.8159 backbone_lr=8.95e-06 head_lr=4.48e-05

Epoch 10/15: train_loss=0.4332 val_loss=0.5842 val_macro_f1=0.8276 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 11/15: train_loss=0.3821 val_loss=0.6033 val_macro_f1=0.8242 backbone_lr=5.00e-06 head_lr=2.50e-05

Epoch 12/15: train_loss=0.3792 val_loss=0.6123 val_macro_f1=0.8274 backbone_lr=3.31e-06 head_lr=1.65e-05

Epoch 13/15: train_loss=0.3472 val_loss=0.5880 val_macro_f1=0.8314 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 14/15: train_loss=0.3474 val_loss=0.5778 val_macro_f1=0.8387 backbone_lr=8.65e-07 head_lr=4.32e-06

Epoch 15/15: train_loss=0.3137 val_loss=0.5794 val_macro_f1=0.8348 backbone_lr=2.19e-07 head_lr=1.09e-06

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/trials/vit_b16_lr2e5_head1e4_seed_53.json
Best val macro F1: 0.8387
Test macro F1: 0.8352

Per-seed shortlist results:

,trial_name,seed,best_val_macro_f1,val_loss_at_best_epoch,test_macro_f1,epochs,best_epoch,early_stopped,total_time_minutes,backbone_lr,head_lr
0,vit_b16_lr1e5_head1e4,13,0.834613,0.528909,0.829093,15,14,False,9.006681,0.00001,0.0001
1,vit_b16_lr1e5_head1e4,14,0.842420,0.492301,0.828894,15,13,False,8.994660,0.00001,0.0001
2,vit_b16_lr1e5_head1e4,17,0.834524,0.546505,0.837814,15,15,False,9.009259,0.00001,0.0001
3,vit_b16_lr1e5_head1e4,53,0.822131,0.552435,0.817390,12,8,True,7.198811,0.00001,0.0001
4,vit_b16_lr2e5_head1e4,13,0.832338,0.559944,0.823925,15,11,True,9.010529,0.00002,0.0001
5,vit_b16_lr2e5_head1e4,14,0.837953,0.556744,0.829896,15,11,True,9.001183,0.00002,0.0001
6,vit_b16_lr2e5_head1e4,17,0.831128,0.618348,0.838037,15,15,False,9.013377,0.00002,0.0001
7,vit_b16_lr2e5_head1e4,53,0.838709,0.577783,0.835175,15,14,False,9.009784,0.00002,0.0001

Aggregated shortlist summary (selection is validation-only):

,trial_name,mean_val_macro_f1,std_val_macro_f1,mean_val_loss_at_best_epoch,mean_test_macro_f1,std_test_macro_f1,mean_epochs,mean_best_epoch,mean_time_minutes,backbone_lr,head_lr
0,vit_b16_lr2e5_head1e4,0.835032,0.003854,0.578205,0.831758,0.006216,15.00,12.75,9.008718,0.00002,0.0001
1,vit_b16_lr1e5_head1e4,0.833422,0.008388,0.530038,0.828298,0.008377,14.25,12.50,8.552353,0.00001,0.0001

Selected BEST_CONFIG after shortlist:
{'name': 'vit_b16_lr2e5_head1e4', 'model_name': 'vit_base_patch16_224', 'batch_size': 32, 'max_epochs': 15, 'patience': 4, 'dropout': 0.5, 'weight_decay': 0.0001, 'backbone_lr': 2e-05, 'head_lr': 0.0001}
Section 4 will now rerun this config cleanly on DEFAULT_SEED=13.

## 4. Clean Rerun Of The Selected Configuration

This section reruns the selected ViT-B/16 configuration cleanly on the default seed after the search and shortlist stages, producing the final one-seed result used before full robustness evaluation.

In [8]:
if "BEST_CONFIG" not in globals():
    BEST_CONFIG = TRIAL_CONFIGS[0].copy()

BEST_CONFIG = BEST_CONFIG.copy()
BEST_CONFIG["name"] = "selected_config"
BEST_CONFIG["max_epochs"] = 20
BEST_CONFIG["patience"] = 5

print("Final config to rerun:")
print(BEST_CONFIG)

final_result = run_vit_trial(BEST_CONFIG, seed=DEFAULT_SEED, save_as_seed_result=True)

result_path = METRICS_DIR / "experiments" / f"seed_{DEFAULT_SEED}_results.json"
print("\nFinal result JSON:", result_path)
print("Best val macro F1:", final_result["validation_metrics"]["best_val_macro_f1"])
print("Test macro F1:", final_result["test_metrics"]["test_macro_f1"])
print("Trainable params:", final_result["training_info"]["trainable_parameter_count"])

Final config to rerun:
{'name': 'selected_config', 'model_name': 'vit_base_patch16_224', 'batch_size': 32, 'max_epochs': 20, 'patience': 5, 'dropout': 0.5, 'weight_decay': 0.0001, 'backbone_lr': 2e-05, 'head_lr': 0.0001}

=== Trainable parameter summary ===
Trial: selected_config
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial selected_config on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=1.9447 val_loss=0.9657 val_macro_f1=0.7019 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.2313 val_loss=0.7510 val_macro_f1=0.7436 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0039 val_loss=0.6744 val_macro_f1=0.7675 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8720 val_loss=0.6037 val_macro_f1=0.7963 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7527 val_loss=0.6629 val_macro_f1=0.7780 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.6939 val_loss=0.6186 val_macro_f1=0.7953 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.5982 val_loss=0.5629 val_macro_f1=0.8134 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5690 val_loss=0.6165 val_macro_f1=0.8016 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5075 val_loss=0.6634 val_macro_f1=0.7957 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4658 val_loss=0.6048 val_macro_f1=0.8088 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4120 val_loss=0.5807 val_macro_f1=0.8228 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.3780 val_loss=0.6288 val_macro_f1=0.8163 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3509 val_loss=0.6312 val_macro_f1=0.8191 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3167 val_loss=0.6293 val_macro_f1=0.8240 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.2900 val_loss=0.6310 val_macro_f1=0.8290 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.2780 val_loss=0.6582 val_macro_f1=0.8255 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.2628 val_loss=0.6755 val_macro_f1=0.8267 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2736 val_loss=0.6676 val_macro_f1=0.8289 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2528 val_loss=0.6653 val_macro_f1=0.8304 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2501 val_loss=0.6631 val_macro_f1=0.8308 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/experiments/seed_13_results.json
Best val macro F1: 0.8308
Test macro F1: 0.8267

Final result JSON: /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_pilot/metrics/experiments/seed_13_results.json
Best val macro F1: 0.8307575881940773
Test macro F1: 0.8267311140585465
Trainable params: 86030222

## 5. Full 30-Seed Robustness Run

This section runs the final selected ViT-B/16 configuration across all 30 matched seeds and saves the robustness outputs, including per-seed results, aggregated summary tables, statistical summaries, learning curves, and comparison plots.

In [12]:
import re

try:
    from scipy import stats as scipy_stats
except Exception:
    scipy_stats = None

if "BEST_CONFIG" not in globals():
    raise RuntimeError("Run sections 3/3.5 first so BEST_CONFIG is defined.")

if "all_styles" not in globals() or "style_to_idx" not in globals() or "num_classes" not in globals():
    all_styles, style_to_idx, num_classes = load_style_metadata(DATASET_CSV)

ROBUSTNESS_OUTPUT_ROOT = PROJECT_ROOT / "experiments" / "imageonly_vit_b16_robustness"
ROBUSTNESS_METRICS_DIR = ROBUSTNESS_OUTPUT_ROOT / "metrics"

# Use root-level folders so layout matches earlier robustness outputs.
ROBUSTNESS_ARTIFACTS_DIR = ROBUSTNESS_OUTPUT_ROOT
(ROBUSTNESS_METRICS_DIR / "trials").mkdir(parents=True, exist_ok=True)
(ROBUSTNESS_METRICS_DIR / "experiments").mkdir(parents=True, exist_ok=True)
(ROBUSTNESS_ARTIFACTS_DIR / "models").mkdir(parents=True, exist_ok=True)
(ROBUSTNESS_ARTIFACTS_DIR / "learning_curves").mkdir(parents=True, exist_ok=True)
(ROBUSTNESS_ARTIFACTS_DIR / "comparison_plots").mkdir(parents=True, exist_ok=True)

SEEDS_FILE = PROJECT_ROOT / "experiments" / "phase3_robustness" / "metrics" / "seeds_list.txt"

def load_robustness_seeds():
    if SEEDS_FILE.exists():
        text = SEEDS_FILE.read_text(encoding="utf-8")
        seeds = [int(x) for x in re.findall(r"Seed\s+(\d+)", text)]
        if seeds:
            return seeds

    seeds = []
    for p in sorted(SPLITS_ROOT.glob("seed_*")):
        if p.is_dir() and (p / "train.csv").exists() and (p / "val.csv").exists() and (p / "test.csv").exists():
            try:
                seeds.append(int(p.name.split("_")[1]))
            except Exception:
                pass
    return seeds

def calculate_stats(values, name):
    arr = np.array(values, dtype=float)
    mean_val = float(np.mean(arr))
    std_val = float(np.std(arr))
    min_val = float(np.min(arr))
    max_val = float(np.max(arr))
    median_val = float(np.median(arr))
    q25 = float(np.percentile(arr, 25))
    q75 = float(np.percentile(arr, 75))
    cv = float((std_val / mean_val * 100.0) if mean_val != 0 else 0.0)

    if len(arr) > 1 and scipy_stats is not None:
        ci = scipy_stats.t.interval(0.95, len(arr) - 1, loc=mean_val, scale=scipy_stats.sem(arr))
        ci_lower = float(ci[0])
        ci_upper = float(ci[1])
    else:
        ci_lower = mean_val
        ci_upper = mean_val

    return {
        "metric": name,
        "mean": mean_val,
        "std": std_val,
        "min": min_val,
        "max": max_val,
        "median": median_val,
        "q25": q25,
        "q75": q75,
        "cv_percent": cv,
        "ci_95_lower": ci_lower,
        "ci_95_upper": ci_upper,
        "n": int(len(arr)),
    }

def safe_to_excel(df, path):
    try:
        df.to_excel(path, index=False)
        print(f"Saved Excel: {path}")
    except Exception as exc:
        print(f"Could not save Excel file {path}: {exc}")

def fmt_mean_std(mean_val, std_val, digits=4):
    return f"{mean_val:.{digits}f} +/- {std_val:.{digits}f}"

def fmt_ci(stat_obj, digits=4):
    return f"[{stat_obj['ci_95_lower']:.{digits}f}, {stat_obj['ci_95_upper']:.{digits}f}]"

def write_robustness_seeds_list(metrics_dir, seeds):
    path = metrics_dir / "seeds_list.txt"
    with open(path, "w", encoding="utf-8") as f:
        f.write("ViT-B/16 image-only robustness seeds\n")
        f.write("=" * 50 + "\n")
        f.write(f"Total seeds: {len(seeds)}\n\n")
        for idx, seed in enumerate(seeds, 1):
            f.write(f"{idx:2d}. Seed {seed}\n")

def build_per_class_tables(all_results, all_styles):
    summary_rows = []
    per_class_stats = {}
    detailed_tables = {
        "f1": [],
        "precision": [],
        "recall": [],
        "accuracy": [],
    }

    for style in all_styles:
        style_metrics = {
            "f1": [],
            "precision": [],
            "recall": [],
            "accuracy": [],
        }

        for result in all_results:
            test_pc = result["test_metrics"].get("per_class_metrics", {})
            if not test_pc:
                continue
            for metric_name in style_metrics:
                metric_dict = test_pc.get(metric_name, {})
                if style in metric_dict:
                    style_metrics[metric_name].append(float(metric_dict[style]))

        if not style_metrics["f1"]:
            continue

        style_stat_block = {
            metric_name: calculate_stats(values, f"{style} - Test {metric_name.title()}")
            for metric_name, values in style_metrics.items()
        }
        per_class_stats[style] = style_stat_block

        summary_rows.append(
            {
                "Style": style,
                "Test_F1_Mean": style_stat_block["f1"]["mean"],
                "Test_F1_Std": style_stat_block["f1"]["std"],
                "Test_Precision_Mean": style_stat_block["precision"]["mean"],
                "Test_Precision_Std": style_stat_block["precision"]["std"],
                "Test_Recall_Mean": style_stat_block["recall"]["mean"],
                "Test_Recall_Std": style_stat_block["recall"]["std"],
                "Test_Accuracy_Mean": style_stat_block["accuracy"]["mean"],
                "Test_Accuracy_Std": style_stat_block["accuracy"]["std"],
            }
        )

        for metric_name in ["f1", "precision", "recall", "accuracy"]:
            stat_obj = style_stat_block[metric_name]
            detailed_tables[metric_name].append(
                {
                    "Style": style,
                    "Mean": stat_obj["mean"],
                    "Std": stat_obj["std"],
                    "Min": stat_obj["min"],
                    "Max": stat_obj["max"],
                    "95% CI Lower": stat_obj["ci_95_lower"],
                    "95% CI Upper": stat_obj["ci_95_upper"],
                    "N": stat_obj["n"],
                }
            )

    df_per_class_summary = pd.DataFrame(summary_rows).sort_values("Style").reset_index(drop=True)
    detailed_tables = {
        metric_name: pd.DataFrame(rows).sort_values("Style").reset_index(drop=True)
        for metric_name, rows in detailed_tables.items()
    }
    return df_per_class_summary, per_class_stats, detailed_tables

In [13]:
def save_robustness_plots(all_results, df_summary, df_per_class_summary):
    if len(all_results) == 0:
        return
    plot_dir = ROBUSTNESS_ARTIFACTS_DIR / "comparison_plots"
    plot_dir.mkdir(parents=True, exist_ok=True)
    results_sorted = sorted(all_results, key=lambda x: x["seed_value"])
    seeds = [r["seed_value"] for r in results_sorted]
    test_f1s = [r["test_metrics"]["test_macro_f1"] for r in results_sorted]
    test_accs = [r["test_metrics"]["test_accuracy"] for r in results_sorted]
    val_f1s = [r["validation_metrics"]["best_val_macro_f1"] for r in results_sorted]
    train_times = [r["training_info"]["total_time_minutes"] for r in results_sorted]
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes[0, 0].plot(seeds, test_f1s, marker="o", linewidth=2, color="tab:blue")
    axes[0, 0].axhline(np.mean(test_f1s), color="red", linestyle="--", label=f"Mean={np.mean(test_f1s):.4f}")
    axes[0, 0].set_title("Test Macro F1 Across Seeds")
    axes[0, 0].set_xlabel("Seed")
    axes[0, 0].set_ylabel("Macro F1")
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].legend()
    axes[0, 1].plot(seeds, test_accs, marker="o", linewidth=2, color="tab:green")
    axes[0, 1].axhline(np.mean(test_accs), color="red", linestyle="--", label=f"Mean={np.mean(test_accs):.4f}")
    axes[0, 1].set_title("Test Accuracy Across Seeds")
    axes[0, 1].set_xlabel("Seed")
    axes[0, 1].set_ylabel("Accuracy")
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].legend()
    axes[1, 0].boxplot([val_f1s, test_f1s], labels=["Best Val Macro F1", "Test Macro F1"])
    axes[1, 0].set_title("Validation vs Test Macro F1")
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 1].plot(seeds, train_times, marker="o", linewidth=2, color="tab:purple")
    axes[1, 1].axhline(np.mean(train_times), color="red", linestyle="--", label=f"Mean={np.mean(train_times):.2f} min")
    axes[1, 1].set_title("Training Time Across Seeds")
    axes[1, 1].set_xlabel("Seed")
    axes[1, 1].set_ylabel("Minutes")
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].legend()
    plt.tight_layout()
    robustness_plot_path = plot_dir / "robustness_analysis.png"
    plt.savefig(robustness_plot_path, dpi=300, bbox_inches="tight")
    plt.close()
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    overlay_results = results_sorted[: min(5, len(results_sorted))]
    for result in overlay_results:
        seed = result["seed_value"]
        curves = result.get("training_curves", {})
        val_curve = curves.get("val_macro_f1s", [])
        val_loss_curve = curves.get("val_losses", [])
        if val_curve:
            axes[0].plot(range(1, len(val_curve) + 1), val_curve, linewidth=2, label=f"Seed {seed}")
        if val_loss_curve:
            axes[1].plot(range(1, len(val_loss_curve) + 1), val_loss_curve, linewidth=2, label=f"Seed {seed}")
    axes[0].set_title("Validation Macro F1 Overlay")
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Macro F1")
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()
    axes[1].set_title("Validation Loss Overlay")
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Loss")
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()
    plt.tight_layout()
    overlay_path = plot_dir / "learning_curves_overlay.png"
    plt.savefig(overlay_path, dpi=300, bbox_inches="tight")
    plt.close()
    if len(df_per_class_summary) > 0:
        df_plot = df_per_class_summary.sort_values("Test_F1_Mean", ascending=True)
        plt.figure(figsize=(10, max(6, len(df_plot) * 0.45)))
        plt.barh(
            df_plot["Style"],
            df_plot["Test_F1_Mean"],
            xerr=df_plot["Test_F1_Std"],
            color="steelblue",
            alpha=0.85,
            ecolor="black",
            capsize=4,
        )
        plt.xlabel("Test F1 Mean")
        plt.title("Per-Class Test F1 Summary")
        plt.grid(True, axis="x", alpha=0.3)
        plt.tight_layout()
        per_class_plot_path = ROBUSTNESS_OUTPUT_ROOT / "per_class_analysis_summary.png"
        plt.savefig(per_class_plot_path, dpi=300, bbox_inches="tight")
        plt.close()

def save_robustness_outputs(all_results, failed_seeds, seeds, metrics_dir, all_styles):
    summary = {
        "total_seeds": len(seeds),
        "successful_experiments": len(all_results),
        "failed_experiments": len(failed_seeds),
        "failed_seeds": failed_seeds,
        "completed_seeds": [result["seed_value"] for result in all_results],
        "experiment_root": str(ROBUSTNESS_OUTPUT_ROOT),
    }
    with open(metrics_dir / "experiments_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    if not all_results:
        return
    summary_rows = []
    for result in all_results:
        validation_metrics = result["validation_metrics"]
        test_metrics = result["test_metrics"]
        overfit_metrics = result["overfitting_analysis"]
        training_info = result["training_info"]
        summary_rows.append(
            {
                "Seed": result["seed_value"],
                "Best_Epoch": training_info["best_epoch"],
                "Early_Stopped": training_info["early_stopped"],
                "Best_Val_Macro_F1": validation_metrics["best_val_macro_f1"],
                "Best_Val_Accuracy": validation_metrics["best_val_accuracy"],
                "Val_Loss_At_Best_Epoch": validation_metrics.get(
                    "val_loss_at_best_epoch",
                    validation_metrics.get("best_val_loss")
                ),
                "Min_Val_Loss": validation_metrics.get(
                    "min_val_loss",
                    validation_metrics.get("best_val_loss")
                ),
                "Test_Macro_F1": test_metrics["test_macro_f1"],
                "Test_Accuracy": test_metrics["test_accuracy"],
                "Test_Macro_Precision": test_metrics["test_macro_precision"],
                "Test_Macro_Recall": test_metrics["test_macro_recall"],
                "Overfitting": overfit_metrics["overfitting_detected"],
                "Training_Time_Min": training_info["total_time_minutes"],
                "Trainable_Params": training_info["trainable_parameter_count"],
            }
        )
    df_summary = pd.DataFrame(summary_rows).sort_values("Seed").reset_index(drop=True)
    df_summary.to_csv(metrics_dir / "summary_table.csv", index=False)
    safe_to_excel(df_summary, metrics_dir / "summary_table.xlsx")
    overall_stats = [
        calculate_stats(df_summary["Test_Macro_F1"].tolist(), "Test Macro F1"),
        calculate_stats(df_summary["Test_Accuracy"].tolist(), "Test Accuracy"),
        calculate_stats(df_summary["Test_Macro_Precision"].tolist(), "Test Macro Precision"),
        calculate_stats(df_summary["Test_Macro_Recall"].tolist(), "Test Macro Recall"),
        calculate_stats(df_summary["Best_Val_Macro_F1"].tolist(), "Best Val Macro F1"),
        calculate_stats(df_summary["Best_Val_Accuracy"].tolist(), "Best Val Accuracy"),
        calculate_stats(df_summary["Val_Loss_At_Best_Epoch"].tolist(), "Val Loss At Best Epoch"),
        calculate_stats(df_summary["Min_Val_Loss"].tolist(), "Min Val Loss"),
        calculate_stats(df_summary["Training_Time_Min"].tolist(), "Training Time (min)"),
    ]
    with open(metrics_dir / "overall_metrics_statistics.json", "w", encoding="utf-8") as f:
        json.dump({"overall_metrics": overall_stats}, f, indent=2)
    pd.DataFrame(overall_stats).to_csv(metrics_dir / "overall_metrics_summary.csv", index=False)
    overfitting_count = int(df_summary["Overfitting"].sum())
    statistical_analysis = {
        "summary_statistics": overall_stats,
        "overfitting_count": overfitting_count,
        "overfitting_percentage": float(100.0 * overfitting_count / len(df_summary)),
        "total_experiments": int(len(df_summary)),
    }
    with open(metrics_dir / "statistical_analysis.json", "w", encoding="utf-8") as f:
        json.dump(statistical_analysis, f, indent=2)
    overall_report_rows = []
    for stat_obj in overall_stats:
        digits = 2 if "Time" in stat_obj["metric"] else 4
        overall_report_rows.append(
            {
                "Metric": stat_obj["metric"],
                "Mean +/- Std": fmt_mean_std(stat_obj["mean"], stat_obj["std"], digits=digits),
                "95% CI": fmt_ci(stat_obj, digits=digits),
                "Min": round(stat_obj["min"], digits),
                "Max": round(stat_obj["max"], digits),
                "CV %": round(stat_obj["cv_percent"], 2),
            }
        )
    pd.DataFrame(overall_report_rows).to_csv(metrics_dir / "comprehensive_report_overall.csv", index=False)
    df_per_class_summary, per_class_stats, detailed_tables = build_per_class_tables(all_results, all_styles)
    with open(metrics_dir / "per_class_metrics_statistics.json", "w", encoding="utf-8") as f:
        json.dump(per_class_stats, f, indent=2)
    if len(df_per_class_summary) > 0:
        df_per_class_summary.to_csv(metrics_dir / "per_class_metrics_summary.csv", index=False)
        safe_to_excel(df_per_class_summary, metrics_dir / "per_class_metrics_summary.xlsx")
        detailed_tables["f1"].to_csv(metrics_dir / "per_class_metrics_f1_summary.csv", index=False)
        detailed_tables["precision"].to_csv(metrics_dir / "per_class_metrics_precision_summary.csv", index=False)
        detailed_tables["recall"].to_csv(metrics_dir / "per_class_metrics_recall_summary.csv", index=False)
        detailed_tables["accuracy"].to_csv(metrics_dir / "per_class_metrics_accuracy_summary.csv", index=False)
        per_class_report_rows = []
        for style in sorted(per_class_stats.keys()):
            f1_stat = per_class_stats[style]["f1"]
            precision_stat = per_class_stats[style]["precision"]
            recall_stat = per_class_stats[style]["recall"]
            per_class_report_rows.append(
                {
                    "Style": style,
                    "F1-Score": fmt_mean_std(f1_stat["mean"], f1_stat["std"], digits=4),
                    "Precision": fmt_mean_std(precision_stat["mean"], precision_stat["std"], digits=4),
                    "Recall": fmt_mean_std(recall_stat["mean"], recall_stat["std"], digits=4),
                    "95% CI (F1)": fmt_ci(f1_stat, digits=4),
                }
            )
        pd.DataFrame(per_class_report_rows).to_csv(metrics_dir / "comprehensive_report_per_class.csv", index=False)
    save_robustness_plots(all_results, df_summary, df_per_class_summary)

In [ ]:
ROBUSTNESS_CONFIG = BEST_CONFIG.copy()
ROBUSTNESS_CONFIG["name"] = "selected_config_30_seed"
# Match the section-4 clean rerun defaults.
ROBUSTNESS_CONFIG["batch_size"] = 64
selected_config_path = ROBUSTNESS_METRICS_DIR / "selected_config.json"
config_keys_to_compare = [
    "model_name",
    "batch_size",
    "max_epochs",
    "patience",
    "dropout",
    "weight_decay",
    "backbone_lr",
    "head_lr",
]
if selected_config_path.exists():
    previous_config = json.loads(selected_config_path.read_text(encoding="utf-8"))
    old_core = {k: previous_config.get(k) for k in config_keys_to_compare}
    new_core = {k: ROBUSTNESS_CONFIG.get(k) for k in config_keys_to_compare}
    if old_core != new_core:
        raise RuntimeError(
            "The robustness output folder already contains results from a different config. "
            "Use a new output folder or remove the old robustness results first."
        )
with open(selected_config_path, "w", encoding="utf-8") as f:
    json.dump(ROBUSTNESS_CONFIG, f, indent=2)
ROBUSTNESS_SEEDS = load_robustness_seeds()
write_robustness_seeds_list(ROBUSTNESS_METRICS_DIR, ROBUSTNESS_SEEDS)
print("Running final 30-seed robustness with config:")
print(ROBUSTNESS_CONFIG)
print(f"Total seeds found: {len(ROBUSTNESS_SEEDS)}")
print(f"Output root: {ROBUSTNESS_OUTPUT_ROOT}")
ORIG_OUTPUT_ROOT = OUTPUT_ROOT
ORIG_METRICS_DIR = METRICS_DIR
ORIG_ARTIFACTS_DIR = ARTIFACTS_DIR
all_results = []
failed_seeds = []
try:
    OUTPUT_ROOT = ROBUSTNESS_OUTPUT_ROOT
    METRICS_DIR = ROBUSTNESS_METRICS_DIR
    ARTIFACTS_DIR = ROBUSTNESS_ARTIFACTS_DIR
    for seed_idx, seed in enumerate(ROBUSTNESS_SEEDS, start=1):
        result_path = METRICS_DIR / "experiments" / f"seed_{seed}_results.json"
        try:
            if result_path.exists():
                print(f"[{seed_idx}/{len(ROBUSTNESS_SEEDS)}] Reusing saved result for seed {seed}")
                with open(result_path, "r", encoding="utf-8") as f:
                    result = json.load(f)
            else:
                print(f"[{seed_idx}/{len(ROBUSTNESS_SEEDS)}] Running seed {seed}")
                result = run_vit_trial(ROBUSTNESS_CONFIG, seed=seed, save_as_seed_result=True)
            all_results.append(result)
        except Exception as exc:
            print(f"[{seed_idx}/{len(ROBUSTNESS_SEEDS)}] Seed {seed} failed: {exc}")
            failed_seeds.append({"seed": seed, "error": str(exc)})
        save_robustness_outputs(
            all_results=all_results,
            failed_seeds=failed_seeds,
            seeds=ROBUSTNESS_SEEDS,
            metrics_dir=ROBUSTNESS_METRICS_DIR,
            all_styles=all_styles,
        )

        cleanup_memory()
        
finally:
    OUTPUT_ROOT = ORIG_OUTPUT_ROOT
    METRICS_DIR = ORIG_METRICS_DIR
    ARTIFACTS_DIR = ORIG_ARTIFACTS_DIR
print("\nRobustness run complete.")

Running final 30-seed robustness with config:
{'name': 'selected_config_30_seed', 'model_name': 'vit_base_patch16_224', 'batch_size': 64, 'max_epochs': 20, 'patience': 5, 'dropout': 0.5, 'weight_decay': 0.0001, 'backbone_lr': 2e-05, 'head_lr': 0.0001}
Total seeds found: 30
Output root: /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness
[1/30] Running seed 13

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1983 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial selected_config_30_seed on seed 13
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_13
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0901 val_loss=1.1521 val_macro_f1=0.6485 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3330 val_loss=0.7964 val_macro_f1=0.7134 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0592 val_loss=0.6786 val_macro_f1=0.7524 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8987 val_loss=0.6279 val_macro_f1=0.7852 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8005 val_loss=0.6356 val_macro_f1=0.7900 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7137 val_loss=0.5894 val_macro_f1=0.8038 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6262 val_loss=0.5773 val_macro_f1=0.8063 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.6013 val_loss=0.5823 val_macro_f1=0.8098 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5419 val_loss=0.5788 val_macro_f1=0.8151 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4984 val_loss=0.6017 val_macro_f1=0.8137 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4530 val_loss=0.5849 val_macro_f1=0.8201 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4088 val_loss=0.6115 val_macro_f1=0.8253 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3893 val_loss=0.5822 val_macro_f1=0.8367 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3607 val_loss=0.6007 val_macro_f1=0.8325 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3420 val_loss=0.5932 val_macro_f1=0.8299 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3146 val_loss=0.6018 val_macro_f1=0.8297 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3151 val_loss=0.5926 val_macro_f1=0.8343 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2970 val_loss=0.5876 val_macro_f1=0.8367 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2998 val_loss=0.5936 val_macro_f1=0.8340 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2837 val_loss=0.5920 val_macro_f1=0.8346 backbone_lr=1.23e-07 head_lr=6.16e-07

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7b28303a6b00>
Traceback (most recent call last):
  File "/home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/ding-zhang/anaconda3/envs/tf_gpu/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1436, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_13_results.json
Best val macro F1: 0.8367
Test macro F1: 0.8303
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[2/30] Running seed 14

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9233 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
Dataset initialized with 1982 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg

======================================================================
Running trial selected_config_30_seed on seed 14
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_14
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0770 val_loss=1.1127 val_macro_f1=0.6285 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3429 val_loss=0.7793 val_macro_f1=0.7331 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0482 val_loss=0.6964 val_macro_f1=0.7518 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9192 val_loss=0.6230 val_macro_f1=0.7939 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8065 val_loss=0.5816 val_macro_f1=0.7943 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7289 val_loss=0.5359 val_macro_f1=0.8195 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6507 val_loss=0.5429 val_macro_f1=0.8191 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5978 val_loss=0.5321 val_macro_f1=0.8310 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5336 val_loss=0.5363 val_macro_f1=0.8347 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4988 val_loss=0.5635 val_macro_f1=0.8273 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4643 val_loss=0.5366 val_macro_f1=0.8371 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4195 val_loss=0.5517 val_macro_f1=0.8383 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.4013 val_loss=0.5854 val_macro_f1=0.8333 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3670 val_loss=0.5507 val_macro_f1=0.8425 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3427 val_loss=0.5662 val_macro_f1=0.8393 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3052 val_loss=0.5641 val_macro_f1=0.8471 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.2963 val_loss=0.5571 val_macro_f1=0.8458 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3188 val_loss=0.5537 val_macro_f1=0.8495 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2974 val_loss=0.5544 val_macro_f1=0.8461 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2998 val_loss=0.5541 val_macro_f1=0.8461 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_14_results.json
Best val macro F1: 0.8495
Test macro F1: 0.8286
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[3/30] Running seed 16

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1976 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
Dataset initialized with 1982 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial selected_config_30_seed on seed 16
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_16
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0695 val_loss=1.1433 val_macro_f1=0.6120 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3141 val_loss=0.8232 val_macro_f1=0.7051 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0577 val_loss=0.6952 val_macro_f1=0.7594 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9167 val_loss=0.6562 val_macro_f1=0.7697 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7937 val_loss=0.6266 val_macro_f1=0.7906 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7163 val_loss=0.6209 val_macro_f1=0.7967 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6595 val_loss=0.5765 val_macro_f1=0.8106 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5994 val_loss=0.5660 val_macro_f1=0.8140 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5477 val_loss=0.6124 val_macro_f1=0.8126 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.5077 val_loss=0.5837 val_macro_f1=0.8132 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4639 val_loss=0.6003 val_macro_f1=0.8211 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4254 val_loss=0.6028 val_macro_f1=0.8241 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3782 val_loss=0.6066 val_macro_f1=0.8277 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3407 val_loss=0.6159 val_macro_f1=0.8227 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3406 val_loss=0.5996 val_macro_f1=0.8315 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3288 val_loss=0.6055 val_macro_f1=0.8373 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3084 val_loss=0.6146 val_macro_f1=0.8312 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3028 val_loss=0.6079 val_macro_f1=0.8306 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2942 val_loss=0.6081 val_macro_f1=0.8316 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2875 val_loss=0.6087 val_macro_f1=0.8337 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_16_results.json
Best val macro F1: 0.8373
Test macro F1: 0.8322
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[4/30] Running seed 17

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial selected_config_30_seed on seed 17
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_17
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0874 val_loss=1.1207 val_macro_f1=0.6318 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3398 val_loss=0.8189 val_macro_f1=0.7491 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0343 val_loss=0.6736 val_macro_f1=0.7738 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9012 val_loss=0.6324 val_macro_f1=0.7846 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7894 val_loss=0.6117 val_macro_f1=0.7940 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7226 val_loss=0.6294 val_macro_f1=0.7933 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6446 val_loss=0.5980 val_macro_f1=0.8144 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5966 val_loss=0.6092 val_macro_f1=0.8122 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5268 val_loss=0.6151 val_macro_f1=0.8153 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.5043 val_loss=0.6217 val_macro_f1=0.8164 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4593 val_loss=0.6331 val_macro_f1=0.8182 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4094 val_loss=0.6392 val_macro_f1=0.8261 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3882 val_loss=0.6293 val_macro_f1=0.8266 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3480 val_loss=0.6340 val_macro_f1=0.8265 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3496 val_loss=0.6720 val_macro_f1=0.8146 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3249 val_loss=0.6264 val_macro_f1=0.8359 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3128 val_loss=0.6348 val_macro_f1=0.8342 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3012 val_loss=0.6447 val_macro_f1=0.8348 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2993 val_loss=0.6390 val_macro_f1=0.8335 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2945 val_loss=0.6406 val_macro_f1=0.8343 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_17_results.json
Best val macro F1: 0.8359
Test macro F1: 0.8450
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[5/30] Running seed 45

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9242 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
Dataset initialized with 1976 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png

======================================================================
Running trial selected_config_30_seed on seed 45
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_45
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0905 val_loss=1.1505 val_macro_f1=0.6378 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3257 val_loss=0.7618 val_macro_f1=0.7332 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0500 val_loss=0.6840 val_macro_f1=0.7567 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8962 val_loss=0.6230 val_macro_f1=0.7911 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8134 val_loss=0.6397 val_macro_f1=0.7829 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7103 val_loss=0.5727 val_macro_f1=0.8068 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6594 val_loss=0.5583 val_macro_f1=0.8093 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5689 val_loss=0.5179 val_macro_f1=0.8268 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5416 val_loss=0.5755 val_macro_f1=0.8220 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4910 val_loss=0.5486 val_macro_f1=0.8310 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4394 val_loss=0.6068 val_macro_f1=0.8244 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4190 val_loss=0.5624 val_macro_f1=0.8347 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3861 val_loss=0.5768 val_macro_f1=0.8380 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3702 val_loss=0.5448 val_macro_f1=0.8413 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3381 val_loss=0.5774 val_macro_f1=0.8425 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3235 val_loss=0.5689 val_macro_f1=0.8446 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3010 val_loss=0.5790 val_macro_f1=0.8425 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2989 val_loss=0.5826 val_macro_f1=0.8440 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2874 val_loss=0.5782 val_macro_f1=0.8493 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2928 val_loss=0.5794 val_macro_f1=0.8483 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_45_results.json
Best val macro F1: 0.8493
Test macro F1: 0.8343
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[6/30] Running seed 48

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9235 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
Dataset initialized with 1980 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg

======================================================================
Running trial selected_config_30_seed on seed 48
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_48
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1055 val_loss=1.1399 val_macro_f1=0.6502 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3224 val_loss=0.7791 val_macro_f1=0.7350 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0428 val_loss=0.6728 val_macro_f1=0.7690 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9088 val_loss=0.5798 val_macro_f1=0.8026 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7871 val_loss=0.5781 val_macro_f1=0.8036 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7333 val_loss=0.5570 val_macro_f1=0.8089 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6512 val_loss=0.5345 val_macro_f1=0.8231 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5826 val_loss=0.5537 val_macro_f1=0.8241 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5449 val_loss=0.5633 val_macro_f1=0.8196 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4872 val_loss=0.5606 val_macro_f1=0.8270 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4592 val_loss=0.6129 val_macro_f1=0.8148 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4408 val_loss=0.5441 val_macro_f1=0.8337 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.4044 val_loss=0.5734 val_macro_f1=0.8244 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3663 val_loss=0.5661 val_macro_f1=0.8324 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3549 val_loss=0.5502 val_macro_f1=0.8398 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3402 val_loss=0.5448 val_macro_f1=0.8420 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3160 val_loss=0.5538 val_macro_f1=0.8399 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2982 val_loss=0.5658 val_macro_f1=0.8414 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2929 val_loss=0.5581 val_macro_f1=0.8404 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2876 val_loss=0.5581 val_macro_f1=0.8396 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_48_results.json
Best val macro F1: 0.8420
Test macro F1: 0.8307
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[7/30] Running seed 53

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
Dataset initialized with 1977 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg

======================================================================
Running trial selected_config_30_seed on seed 53
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_53
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0844 val_loss=1.1531 val_macro_f1=0.6407 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3401 val_loss=0.8157 val_macro_f1=0.7176 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0534 val_loss=0.7197 val_macro_f1=0.7505 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9162 val_loss=0.6150 val_macro_f1=0.8012 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8117 val_loss=0.6292 val_macro_f1=0.7905 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7057 val_loss=0.5734 val_macro_f1=0.8123 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6544 val_loss=0.5849 val_macro_f1=0.8105 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5959 val_loss=0.6107 val_macro_f1=0.8063 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5432 val_loss=0.6439 val_macro_f1=0.8105 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4953 val_loss=0.5759 val_macro_f1=0.8191 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4510 val_loss=0.5890 val_macro_f1=0.8240 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4103 val_loss=0.5775 val_macro_f1=0.8223 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3782 val_loss=0.5899 val_macro_f1=0.8297 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3711 val_loss=0.6299 val_macro_f1=0.8175 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3440 val_loss=0.6315 val_macro_f1=0.8283 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3275 val_loss=0.6197 val_macro_f1=0.8245 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3042 val_loss=0.6098 val_macro_f1=0.8325 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3194 val_loss=0.6140 val_macro_f1=0.8324 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2939 val_loss=0.6097 val_macro_f1=0.8330 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.3043 val_loss=0.6098 val_macro_f1=0.8325 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_53_results.json
Best val macro F1: 0.8330
Test macro F1: 0.8307
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[8/30] Running seed 58

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg

======================================================================
Running trial selected_config_30_seed on seed 58
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_58
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0871 val_loss=1.1278 val_macro_f1=0.6728 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3328 val_loss=0.8118 val_macro_f1=0.7166 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0577 val_loss=0.6970 val_macro_f1=0.7599 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9179 val_loss=0.6572 val_macro_f1=0.7722 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8027 val_loss=0.6108 val_macro_f1=0.7892 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7135 val_loss=0.5985 val_macro_f1=0.8070 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6489 val_loss=0.5985 val_macro_f1=0.8075 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5932 val_loss=0.5916 val_macro_f1=0.8077 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5322 val_loss=0.5733 val_macro_f1=0.8074 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4921 val_loss=0.6272 val_macro_f1=0.8098 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4344 val_loss=0.6060 val_macro_f1=0.8146 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4050 val_loss=0.6126 val_macro_f1=0.8179 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3775 val_loss=0.6265 val_macro_f1=0.8248 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3666 val_loss=0.5955 val_macro_f1=0.8211 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3418 val_loss=0.6066 val_macro_f1=0.8308 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3054 val_loss=0.6194 val_macro_f1=0.8256 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3084 val_loss=0.6229 val_macro_f1=0.8253 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2892 val_loss=0.6253 val_macro_f1=0.8317 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2939 val_loss=0.6285 val_macro_f1=0.8301 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2956 val_loss=0.6280 val_macro_f1=0.8295 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_58_results.json
Best val macro F1: 0.8317
Test macro F1: 0.8509
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[9/30] Running seed 72

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9232 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1983 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg

======================================================================
Running trial selected_config_30_seed on seed 72
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_72
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0709 val_loss=1.1004 val_macro_f1=0.6374 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3195 val_loss=0.8279 val_macro_f1=0.7220 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0565 val_loss=0.7868 val_macro_f1=0.7298 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8845 val_loss=0.6648 val_macro_f1=0.7695 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7920 val_loss=0.6005 val_macro_f1=0.7955 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7111 val_loss=0.6212 val_macro_f1=0.7911 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6437 val_loss=0.5853 val_macro_f1=0.8079 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5902 val_loss=0.5974 val_macro_f1=0.8021 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5406 val_loss=0.5438 val_macro_f1=0.8286 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4678 val_loss=0.6001 val_macro_f1=0.8188 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4597 val_loss=0.5776 val_macro_f1=0.8283 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4378 val_loss=0.5590 val_macro_f1=0.8329 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3921 val_loss=0.5802 val_macro_f1=0.8340 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3686 val_loss=0.5881 val_macro_f1=0.8308 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3414 val_loss=0.5842 val_macro_f1=0.8428 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3184 val_loss=0.5889 val_macro_f1=0.8387 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.2978 val_loss=0.5969 val_macro_f1=0.8369 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2978 val_loss=0.5873 val_macro_f1=0.8372 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2918 val_loss=0.5896 val_macro_f1=0.8375 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2959 val_loss=0.5869 val_macro_f1=0.8382 backbone_lr=1.23e-07 head_lr=6.16e-07
Early stopping at epoch 20

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_72_results.json
Best val macro F1: 0.8428
Test macro F1: 0.8300
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[10/30] Running seed 102

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9233 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
Dataset initialized with 1983 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg

======================================================================
Running trial selected_config_30_seed on seed 102
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_102
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0706 val_loss=1.1025 val_macro_f1=0.6362 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3266 val_loss=0.7657 val_macro_f1=0.7565 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0572 val_loss=0.6743 val_macro_f1=0.7682 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8937 val_loss=0.5700 val_macro_f1=0.8071 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7950 val_loss=0.5873 val_macro_f1=0.8023 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7014 val_loss=0.5331 val_macro_f1=0.8302 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6472 val_loss=0.5449 val_macro_f1=0.8336 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5894 val_loss=0.5350 val_macro_f1=0.8300 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5431 val_loss=0.5163 val_macro_f1=0.8295 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4942 val_loss=0.5190 val_macro_f1=0.8372 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4508 val_loss=0.5521 val_macro_f1=0.8298 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4196 val_loss=0.5332 val_macro_f1=0.8360 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.4012 val_loss=0.5592 val_macro_f1=0.8358 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3444 val_loss=0.5512 val_macro_f1=0.8391 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3534 val_loss=0.5489 val_macro_f1=0.8419 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3302 val_loss=0.5608 val_macro_f1=0.8413 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3085 val_loss=0.5644 val_macro_f1=0.8477 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3079 val_loss=0.5551 val_macro_f1=0.8491 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.3064 val_loss=0.5581 val_macro_f1=0.8462 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2957 val_loss=0.5569 val_macro_f1=0.8477 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_102_results.json
Best val macro F1: 0.8491
Test macro F1: 0.8302
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[11/30] Running seed 112

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
Dataset initialized with 1984 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg

======================================================================
Running trial selected_config_30_seed on seed 112
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_112
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0636 val_loss=1.0941 val_macro_f1=0.6428 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3051 val_loss=0.7621 val_macro_f1=0.7454 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0365 val_loss=0.6941 val_macro_f1=0.7596 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9150 val_loss=0.6809 val_macro_f1=0.7706 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7800 val_loss=0.5793 val_macro_f1=0.8103 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.6942 val_loss=0.6178 val_macro_f1=0.8045 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6485 val_loss=0.5390 val_macro_f1=0.8226 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5913 val_loss=0.5598 val_macro_f1=0.8212 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5664 val_loss=0.5847 val_macro_f1=0.8168 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.5121 val_loss=0.6118 val_macro_f1=0.8117 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4546 val_loss=0.6178 val_macro_f1=0.8130 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4141 val_loss=0.6047 val_macro_f1=0.8186 backbone_lr=8.44e-06 head_lr=4.22e-05
Early stopping at epoch 12

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_112_results.json
Best val macro F1: 0.8226
Test macro F1: 0.8165
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[12/30] Running seed 115

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg

======================================================================
Running trial selected_config_30_seed on seed 115
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_115
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0946 val_loss=1.1051 val_macro_f1=0.6591 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3465 val_loss=0.7519 val_macro_f1=0.7527 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0548 val_loss=0.6384 val_macro_f1=0.7897 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9003 val_loss=0.6055 val_macro_f1=0.7995 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8034 val_loss=0.5700 val_macro_f1=0.8095 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7029 val_loss=0.5490 val_macro_f1=0.8232 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6401 val_loss=0.5768 val_macro_f1=0.8164 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5863 val_loss=0.5681 val_macro_f1=0.8270 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5302 val_loss=0.5625 val_macro_f1=0.8266 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.5111 val_loss=0.5713 val_macro_f1=0.8284 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4353 val_loss=0.5713 val_macro_f1=0.8328 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4077 val_loss=0.5812 val_macro_f1=0.8304 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3830 val_loss=0.5860 val_macro_f1=0.8324 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3668 val_loss=0.5552 val_macro_f1=0.8368 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3474 val_loss=0.5591 val_macro_f1=0.8410 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3357 val_loss=0.5737 val_macro_f1=0.8341 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3117 val_loss=0.5763 val_macro_f1=0.8385 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3119 val_loss=0.5836 val_macro_f1=0.8371 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2832 val_loss=0.5689 val_macro_f1=0.8354 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2965 val_loss=0.5708 val_macro_f1=0.8376 backbone_lr=1.23e-07 head_lr=6.16e-07
Early stopping at epoch 20

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_115_results.json
Best val macro F1: 0.8410
Test macro F1: 0.8316
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[13/30] Running seed 120

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg

======================================================================
Running trial selected_config_30_seed on seed 120
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_120
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0810 val_loss=1.1318 val_macro_f1=0.6466 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3273 val_loss=0.7824 val_macro_f1=0.7473 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0490 val_loss=0.6612 val_macro_f1=0.7712 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9040 val_loss=0.5988 val_macro_f1=0.7879 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7778 val_loss=0.5691 val_macro_f1=0.8168 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7180 val_loss=0.5743 val_macro_f1=0.8031 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6345 val_loss=0.6007 val_macro_f1=0.8129 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5628 val_loss=0.5454 val_macro_f1=0.8296 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5090 val_loss=0.5644 val_macro_f1=0.8322 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4930 val_loss=0.5584 val_macro_f1=0.8323 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4517 val_loss=0.5890 val_macro_f1=0.8296 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4386 val_loss=0.5436 val_macro_f1=0.8377 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3831 val_loss=0.5518 val_macro_f1=0.8437 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3508 val_loss=0.5707 val_macro_f1=0.8436 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3398 val_loss=0.5676 val_macro_f1=0.8402 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3315 val_loss=0.5722 val_macro_f1=0.8395 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3140 val_loss=0.5548 val_macro_f1=0.8422 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3067 val_loss=0.5612 val_macro_f1=0.8475 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2842 val_loss=0.5657 val_macro_f1=0.8476 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2845 val_loss=0.5635 val_macro_f1=0.8474 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_120_results.json
Best val macro F1: 0.8476
Test macro F1: 0.8349
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[14/30] Running seed 126

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9236 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
Dataset initialized with 1980 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg

======================================================================
Running trial selected_config_30_seed on seed 126
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_126
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1072 val_loss=1.1394 val_macro_f1=0.6323 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3350 val_loss=0.7972 val_macro_f1=0.7413 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0423 val_loss=0.6938 val_macro_f1=0.7530 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9031 val_loss=0.7077 val_macro_f1=0.7595 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7961 val_loss=0.6238 val_macro_f1=0.7964 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7222 val_loss=0.6023 val_macro_f1=0.8090 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6455 val_loss=0.5900 val_macro_f1=0.8021 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5587 val_loss=0.6288 val_macro_f1=0.7963 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5407 val_loss=0.6025 val_macro_f1=0.8139 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4932 val_loss=0.6087 val_macro_f1=0.8046 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4413 val_loss=0.6036 val_macro_f1=0.8172 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4097 val_loss=0.6210 val_macro_f1=0.8146 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3954 val_loss=0.6409 val_macro_f1=0.8209 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3491 val_loss=0.6362 val_macro_f1=0.8222 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3382 val_loss=0.6242 val_macro_f1=0.8244 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3362 val_loss=0.6271 val_macro_f1=0.8281 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3034 val_loss=0.6471 val_macro_f1=0.8263 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3018 val_loss=0.6205 val_macro_f1=0.8336 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2933 val_loss=0.6243 val_macro_f1=0.8314 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.3064 val_loss=0.6244 val_macro_f1=0.8320 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_126_results.json
Best val macro F1: 0.8336
Test macro F1: 0.8335
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[15/30] Running seed 141

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9240 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
Dataset initialized with 1976 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg

======================================================================
Running trial selected_config_30_seed on seed 141
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_141
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1291 val_loss=1.1657 val_macro_f1=0.6180 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3385 val_loss=0.8562 val_macro_f1=0.7018 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0625 val_loss=0.7871 val_macro_f1=0.7218 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8990 val_loss=0.6550 val_macro_f1=0.7657 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7787 val_loss=0.6074 val_macro_f1=0.7923 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7218 val_loss=0.6244 val_macro_f1=0.7973 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6566 val_loss=0.6646 val_macro_f1=0.7869 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5779 val_loss=0.6089 val_macro_f1=0.8059 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5323 val_loss=0.6355 val_macro_f1=0.8056 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4846 val_loss=0.6297 val_macro_f1=0.8054 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4526 val_loss=0.5943 val_macro_f1=0.8210 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4063 val_loss=0.6317 val_macro_f1=0.8067 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3924 val_loss=0.6123 val_macro_f1=0.8312 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3558 val_loss=0.6440 val_macro_f1=0.8226 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3575 val_loss=0.6243 val_macro_f1=0.8240 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3299 val_loss=0.6230 val_macro_f1=0.8294 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3087 val_loss=0.6340 val_macro_f1=0.8306 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2987 val_loss=0.6360 val_macro_f1=0.8291 backbone_lr=1.09e-06 head_lr=5.45e-06
Early stopping at epoch 18

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_141_results.json
Best val macro F1: 0.8312
Test macro F1: 0.8382
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[16/30] Running seed 215

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9235 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
Dataset initialized with 1983 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg

======================================================================
Running trial selected_config_30_seed on seed 215
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_215
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1071 val_loss=1.1696 val_macro_f1=0.6334 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3520 val_loss=0.8244 val_macro_f1=0.7244 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0655 val_loss=0.7504 val_macro_f1=0.7354 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9237 val_loss=0.6437 val_macro_f1=0.7812 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7996 val_loss=0.6739 val_macro_f1=0.7725 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7374 val_loss=0.5898 val_macro_f1=0.8031 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6640 val_loss=0.6136 val_macro_f1=0.8000 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.6069 val_loss=0.6232 val_macro_f1=0.8002 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5397 val_loss=0.6214 val_macro_f1=0.8080 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.5073 val_loss=0.5901 val_macro_f1=0.8197 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4583 val_loss=0.5754 val_macro_f1=0.8295 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4283 val_loss=0.5784 val_macro_f1=0.8300 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3971 val_loss=0.5899 val_macro_f1=0.8355 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3720 val_loss=0.6336 val_macro_f1=0.8240 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3430 val_loss=0.6282 val_macro_f1=0.8295 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3315 val_loss=0.6315 val_macro_f1=0.8327 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3142 val_loss=0.6116 val_macro_f1=0.8378 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2972 val_loss=0.6194 val_macro_f1=0.8372 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.3091 val_loss=0.6093 val_macro_f1=0.8395 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2933 val_loss=0.6085 val_macro_f1=0.8396 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_215_results.json
Best val macro F1: 0.8396
Test macro F1: 0.8393
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[17/30] Running seed 217

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9235 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
Dataset initialized with 1981 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg

======================================================================
Running trial selected_config_30_seed on seed 217
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_217
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0899 val_loss=1.1142 val_macro_f1=0.6541 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3270 val_loss=0.8419 val_macro_f1=0.7242 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0576 val_loss=0.6687 val_macro_f1=0.7904 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9060 val_loss=0.6332 val_macro_f1=0.7901 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8161 val_loss=0.6070 val_macro_f1=0.8056 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7392 val_loss=0.6222 val_macro_f1=0.8012 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6634 val_loss=0.6000 val_macro_f1=0.8112 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5705 val_loss=0.6015 val_macro_f1=0.8181 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5414 val_loss=0.5728 val_macro_f1=0.8272 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.5210 val_loss=0.5564 val_macro_f1=0.8288 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4513 val_loss=0.5616 val_macro_f1=0.8322 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4153 val_loss=0.5477 val_macro_f1=0.8367 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3996 val_loss=0.5817 val_macro_f1=0.8300 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3684 val_loss=0.5818 val_macro_f1=0.8341 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3503 val_loss=0.5807 val_macro_f1=0.8364 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3167 val_loss=0.5867 val_macro_f1=0.8393 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3141 val_loss=0.5818 val_macro_f1=0.8383 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3131 val_loss=0.5764 val_macro_f1=0.8412 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.3138 val_loss=0.5760 val_macro_f1=0.8403 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2982 val_loss=0.5772 val_macro_f1=0.8403 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_217_results.json
Best val macro F1: 0.8412
Test macro F1: 0.8357
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[18/30] Running seed 259

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9235 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
Dataset initialized with 1980 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg

======================================================================
Running trial selected_config_30_seed on seed 259
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_259
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0731 val_loss=1.1356 val_macro_f1=0.6550 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3172 val_loss=0.7517 val_macro_f1=0.7516 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0620 val_loss=0.6400 val_macro_f1=0.7845 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9256 val_loss=0.5749 val_macro_f1=0.8049 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7949 val_loss=0.5662 val_macro_f1=0.8081 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7274 val_loss=0.5469 val_macro_f1=0.8139 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6360 val_loss=0.5258 val_macro_f1=0.8231 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.6045 val_loss=0.5144 val_macro_f1=0.8352 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5310 val_loss=0.5301 val_macro_f1=0.8286 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4712 val_loss=0.5682 val_macro_f1=0.8254 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4597 val_loss=0.5353 val_macro_f1=0.8370 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4197 val_loss=0.5395 val_macro_f1=0.8365 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3983 val_loss=0.5650 val_macro_f1=0.8330 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3716 val_loss=0.5315 val_macro_f1=0.8436 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3407 val_loss=0.5471 val_macro_f1=0.8440 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3210 val_loss=0.5464 val_macro_f1=0.8471 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3246 val_loss=0.5518 val_macro_f1=0.8457 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2986 val_loss=0.5541 val_macro_f1=0.8486 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.3102 val_loss=0.5484 val_macro_f1=0.8526 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2890 val_loss=0.5502 val_macro_f1=0.8500 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_259_results.json
Best val macro F1: 0.8526
Test macro F1: 0.8338
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[19/30] Running seed 280

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9236 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
Dataset initialized with 1979 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1981 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg

======================================================================
Running trial selected_config_30_seed on seed 280
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_280
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0926 val_loss=1.1174 val_macro_f1=0.6771 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3225 val_loss=0.8087 val_macro_f1=0.7371 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0687 val_loss=0.6916 val_macro_f1=0.7764 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9022 val_loss=0.6750 val_macro_f1=0.7726 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8010 val_loss=0.5910 val_macro_f1=0.7990 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7040 val_loss=0.6039 val_macro_f1=0.8063 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6304 val_loss=0.6032 val_macro_f1=0.7978 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5857 val_loss=0.5947 val_macro_f1=0.8110 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5363 val_loss=0.5891 val_macro_f1=0.8107 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4960 val_loss=0.6406 val_macro_f1=0.8014 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4534 val_loss=0.5913 val_macro_f1=0.8260 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.3963 val_loss=0.6367 val_macro_f1=0.8169 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3753 val_loss=0.6221 val_macro_f1=0.8242 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3590 val_loss=0.6269 val_macro_f1=0.8230 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3267 val_loss=0.6215 val_macro_f1=0.8246 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3213 val_loss=0.6124 val_macro_f1=0.8295 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3056 val_loss=0.6281 val_macro_f1=0.8317 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3124 val_loss=0.6265 val_macro_f1=0.8240 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.3063 val_loss=0.6211 val_macro_f1=0.8255 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2976 val_loss=0.6197 val_macro_f1=0.8256 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_280_results.json
Best val macro F1: 0.8317
Test macro F1: 0.8241
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[20/30] Running seed 288

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
Dataset initialized with 1979 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg

======================================================================
Running trial selected_config_30_seed on seed 288
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_288
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1158 val_loss=1.1630 val_macro_f1=0.6192 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3534 val_loss=0.7895 val_macro_f1=0.7317 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0627 val_loss=0.7287 val_macro_f1=0.7527 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9050 val_loss=0.6368 val_macro_f1=0.7816 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7994 val_loss=0.5923 val_macro_f1=0.8026 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7128 val_loss=0.6233 val_macro_f1=0.8052 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6475 val_loss=0.5940 val_macro_f1=0.8207 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.6009 val_loss=0.5868 val_macro_f1=0.8162 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5463 val_loss=0.6019 val_macro_f1=0.8212 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4846 val_loss=0.5850 val_macro_f1=0.8266 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4458 val_loss=0.5895 val_macro_f1=0.8251 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4436 val_loss=0.6077 val_macro_f1=0.8245 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3814 val_loss=0.6007 val_macro_f1=0.8336 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3518 val_loss=0.6416 val_macro_f1=0.8282 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3627 val_loss=0.6237 val_macro_f1=0.8362 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3237 val_loss=0.6355 val_macro_f1=0.8338 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3151 val_loss=0.6346 val_macro_f1=0.8330 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3107 val_loss=0.6413 val_macro_f1=0.8306 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.3073 val_loss=0.6364 val_macro_f1=0.8306 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2961 val_loss=0.6368 val_macro_f1=0.8322 backbone_lr=1.23e-07 head_lr=6.16e-07
Early stopping at epoch 20

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_288_results.json
Best val macro F1: 0.8362
Test macro F1: 0.8319
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[21/30] Running seed 303

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9237 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg

======================================================================
Running trial selected_config_30_seed on seed 303
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_303
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0870 val_loss=1.1101 val_macro_f1=0.6487 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3402 val_loss=0.7896 val_macro_f1=0.7433 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0571 val_loss=0.6901 val_macro_f1=0.7610 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8987 val_loss=0.6166 val_macro_f1=0.7892 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8018 val_loss=0.5946 val_macro_f1=0.8015 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7223 val_loss=0.5944 val_macro_f1=0.7962 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6386 val_loss=0.6160 val_macro_f1=0.8110 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5869 val_loss=0.5737 val_macro_f1=0.8188 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5146 val_loss=0.5869 val_macro_f1=0.8228 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4993 val_loss=0.5691 val_macro_f1=0.8276 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4431 val_loss=0.5691 val_macro_f1=0.8258 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4147 val_loss=0.6038 val_macro_f1=0.8276 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3893 val_loss=0.6024 val_macro_f1=0.8317 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3618 val_loss=0.6000 val_macro_f1=0.8293 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3564 val_loss=0.6020 val_macro_f1=0.8339 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3336 val_loss=0.6263 val_macro_f1=0.8270 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3170 val_loss=0.6236 val_macro_f1=0.8331 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2985 val_loss=0.6271 val_macro_f1=0.8351 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2918 val_loss=0.6284 val_macro_f1=0.8327 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2998 val_loss=0.6282 val_macro_f1=0.8327 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_303_results.json
Best val macro F1: 0.8351
Test macro F1: 0.8370
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[22/30] Running seed 309

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9236 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
Dataset initialized with 1978 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1982 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg

======================================================================
Running trial selected_config_30_seed on seed 309
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_309
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0710 val_loss=1.1710 val_macro_f1=0.6549 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3136 val_loss=0.7903 val_macro_f1=0.7431 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0661 val_loss=0.6787 val_macro_f1=0.7858 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8985 val_loss=0.6070 val_macro_f1=0.8049 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7942 val_loss=0.5605 val_macro_f1=0.8216 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7135 val_loss=0.5630 val_macro_f1=0.8137 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6481 val_loss=0.5835 val_macro_f1=0.8133 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5865 val_loss=0.5785 val_macro_f1=0.8158 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5218 val_loss=0.5683 val_macro_f1=0.8247 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4905 val_loss=0.5710 val_macro_f1=0.8223 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4446 val_loss=0.5472 val_macro_f1=0.8370 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4193 val_loss=0.5802 val_macro_f1=0.8393 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3816 val_loss=0.5770 val_macro_f1=0.8320 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3597 val_loss=0.5862 val_macro_f1=0.8342 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3405 val_loss=0.5878 val_macro_f1=0.8347 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3303 val_loss=0.5817 val_macro_f1=0.8344 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3005 val_loss=0.5872 val_macro_f1=0.8346 backbone_lr=1.91e-06 head_lr=9.55e-06
Early stopping at epoch 17

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_309_results.json
Best val macro F1: 0.8393
Test macro F1: 0.8327
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[23/30] Running seed 328

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9238 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
Dataset initialized with 1979 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
Dataset initialized with 1979 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg

======================================================================
Running trial selected_config_30_seed on seed 328
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_328
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0680 val_loss=1.1242 val_macro_f1=0.6599 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3105 val_loss=0.8313 val_macro_f1=0.7391 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0487 val_loss=0.6831 val_macro_f1=0.7774 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9040 val_loss=0.6179 val_macro_f1=0.7932 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8216 val_loss=0.5882 val_macro_f1=0.8025 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7407 val_loss=0.6095 val_macro_f1=0.7949 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6596 val_loss=0.5255 val_macro_f1=0.8244 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.6027 val_loss=0.5748 val_macro_f1=0.8109 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5467 val_loss=0.5821 val_macro_f1=0.8086 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.5030 val_loss=0.5618 val_macro_f1=0.8229 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4610 val_loss=0.5590 val_macro_f1=0.8225 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4156 val_loss=0.5579 val_macro_f1=0.8272 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3874 val_loss=0.5880 val_macro_f1=0.8228 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3608 val_loss=0.5930 val_macro_f1=0.8251 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3480 val_loss=0.6040 val_macro_f1=0.8337 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3286 val_loss=0.6031 val_macro_f1=0.8299 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3070 val_loss=0.5961 val_macro_f1=0.8402 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3131 val_loss=0.5982 val_macro_f1=0.8343 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.3167 val_loss=0.5940 val_macro_f1=0.8357 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2989 val_loss=0.5929 val_macro_f1=0.8349 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_328_results.json
Best val macro F1: 0.8402
Test macro F1: 0.8387
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[24/30] Running seed 333

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
Dataset initialized with 1980 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2016新しい夏のファッション女性服フィンガープリントレタープリントtシャツの女性面白いスタイルパンク岩女性トップスティーシャツ.jpg
Dataset initialized with 1977 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    raw=dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/オリジナルコットンリネンスタンド襟ドレス緩いガウン新しい2016春秋の女性ヴィンテージドレス服プラスサイズ.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg

======================================================================
Running trial selected_config_30_seed on seed 333
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_333
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0622 val_loss=1.1036 val_macro_f1=0.6378 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3102 val_loss=0.7546 val_macro_f1=0.7554 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0591 val_loss=0.6698 val_macro_f1=0.7711 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9039 val_loss=0.6068 val_macro_f1=0.7982 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8005 val_loss=0.5973 val_macro_f1=0.7978 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7143 val_loss=0.5859 val_macro_f1=0.8022 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6332 val_loss=0.6022 val_macro_f1=0.8089 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5809 val_loss=0.5758 val_macro_f1=0.8182 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5332 val_loss=0.5977 val_macro_f1=0.8191 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4719 val_loss=0.6187 val_macro_f1=0.8181 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4366 val_loss=0.5978 val_macro_f1=0.8239 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4099 val_loss=0.6189 val_macro_f1=0.8202 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3895 val_loss=0.5941 val_macro_f1=0.8268 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3639 val_loss=0.6019 val_macro_f1=0.8278 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3402 val_loss=0.5751 val_macro_f1=0.8411 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3010 val_loss=0.5883 val_macro_f1=0.8394 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3033 val_loss=0.5930 val_macro_f1=0.8444 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2873 val_loss=0.5998 val_macro_f1=0.8431 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.3020 val_loss=0.5908 val_macro_f1=0.8438 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2900 val_loss=0.5895 val_macro_f1=0.8427 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_333_results.json
Best val macro F1: 0.8444
Test macro F1: 0.8250
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[25/30] Running seed 347

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG.jpg
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
Dataset initialized with 1979 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/yvonne-warmbier-vintage-kleid-grün.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG

======================================================================
Running trial selected_config_30_seed on seed 347
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_347
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0863 val_loss=1.1310 val_macro_f1=0.6488 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3364 val_loss=0.8038 val_macro_f1=0.7374 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0386 val_loss=0.6863 val_macro_f1=0.7782 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8859 val_loss=0.6178 val_macro_f1=0.7926 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8060 val_loss=0.5942 val_macro_f1=0.8045 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7079 val_loss=0.6017 val_macro_f1=0.8126 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6384 val_loss=0.5657 val_macro_f1=0.8207 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5731 val_loss=0.6004 val_macro_f1=0.8186 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5104 val_loss=0.5725 val_macro_f1=0.8256 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.5122 val_loss=0.5666 val_macro_f1=0.8313 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4387 val_loss=0.5763 val_macro_f1=0.8356 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4170 val_loss=0.5650 val_macro_f1=0.8445 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3911 val_loss=0.5486 val_macro_f1=0.8354 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3488 val_loss=0.5950 val_macro_f1=0.8349 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3402 val_loss=0.5825 val_macro_f1=0.8450 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3275 val_loss=0.5849 val_macro_f1=0.8476 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.2978 val_loss=0.5989 val_macro_f1=0.8441 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3081 val_loss=0.5964 val_macro_f1=0.8439 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2891 val_loss=0.5942 val_macro_f1=0.8479 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2889 val_loss=0.5952 val_macro_f1=0.8455 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_347_results.json
Best val macro F1: 0.8479
Test macro F1: 0.8378
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[26/30] Running seed 360

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9234 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
Dataset initialized with 1981 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg

======================================================================
Running trial selected_config_30_seed on seed 360
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_360
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0917 val_loss=1.1707 val_macro_f1=0.6801 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3421 val_loss=0.7756 val_macro_f1=0.7460 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0482 val_loss=0.7014 val_macro_f1=0.7791 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8812 val_loss=0.6298 val_macro_f1=0.7912 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7840 val_loss=0.6309 val_macro_f1=0.7884 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7025 val_loss=0.6253 val_macro_f1=0.8043 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6481 val_loss=0.6493 val_macro_f1=0.7934 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5746 val_loss=0.5796 val_macro_f1=0.8055 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5511 val_loss=0.5986 val_macro_f1=0.8050 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4968 val_loss=0.5830 val_macro_f1=0.8265 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4594 val_loss=0.6141 val_macro_f1=0.8120 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4181 val_loss=0.6034 val_macro_f1=0.8147 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3870 val_loss=0.6046 val_macro_f1=0.8257 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3780 val_loss=0.5786 val_macro_f1=0.8300 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3489 val_loss=0.5853 val_macro_f1=0.8246 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3143 val_loss=0.6024 val_macro_f1=0.8343 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3107 val_loss=0.6156 val_macro_f1=0.8271 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2970 val_loss=0.6002 val_macro_f1=0.8343 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2887 val_loss=0.5981 val_macro_f1=0.8364 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2980 val_loss=0.5982 val_macro_f1=0.8374 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_360_results.json
Best val macro F1: 0.8374
Test macro F1: 0.8285
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[27/30] Running seed 367

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9237 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Bibi-Bevza-Femme-Prêt-à-Porter-_-Automne-Hiver-2013-_2014-Photographié-avant-le-défilé-Chloé-Fashionweek-Paris-Street-Style1.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/2df283cfce44d8061bfdc93a02b30be4のコピー.jpg
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最高のバージョン-2016女性ハーレムパンツカジュアルヒップホップパンツスウェットパンツ衣装ズボン女の子のためのブランドバギーダンスパンツ.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg

======================================================================
Running trial selected_config_30_seed on seed 367
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_367
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0864 val_loss=1.1095 val_macro_f1=0.6552 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3359 val_loss=0.7610 val_macro_f1=0.7447 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0372 val_loss=0.6648 val_macro_f1=0.7696 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9172 val_loss=0.6511 val_macro_f1=0.7787 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8087 val_loss=0.5857 val_macro_f1=0.7958 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7274 val_loss=0.5715 val_macro_f1=0.8088 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6518 val_loss=0.5704 val_macro_f1=0.8091 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5949 val_loss=0.5326 val_macro_f1=0.8261 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5299 val_loss=0.5710 val_macro_f1=0.8171 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.5166 val_loss=0.5616 val_macro_f1=0.8274 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4620 val_loss=0.5491 val_macro_f1=0.8349 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4201 val_loss=0.5778 val_macro_f1=0.8288 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.4025 val_loss=0.5198 val_macro_f1=0.8424 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3520 val_loss=0.5441 val_macro_f1=0.8406 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3462 val_loss=0.5483 val_macro_f1=0.8355 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3358 val_loss=0.5583 val_macro_f1=0.8426 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3110 val_loss=0.5504 val_macro_f1=0.8344 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3015 val_loss=0.5482 val_macro_f1=0.8390 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2959 val_loss=0.5499 val_macro_f1=0.8449 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2965 val_loss=0.5475 val_macro_f1=0.8470 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_367_results.json
Best val macro F1: 0.8470
Test macro F1: 0.8410
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[28/30] Running seed 378

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9237 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/Twinset-hiphop女性ロング-スリーブ-トップ-ヒップホップヒップホップジャズ-ds.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
Dataset initialized with 1979 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/mode/kosmetyczna+hedonistka_stylizacja+z+bia%C5%82%C4%85+koszul%C4%85.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/kosmetyczna+hedonistka_stylizacja+z+białą+koszulą.png
    raw=dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料-新加入-高-品質-ノースリーブ-ボウ-コットンスウィートロリータドレス.jpg
    raw=dataset/mode/czarny+koronkowy+top+o%C5%82%C3%B3wkowa+czarna+sp%C3%B3dniczka+rajstopy.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/czarny+koronkowy+top+ołówkowa+czarna+spódniczka+rajstopy.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
Dataset initialized with 1980 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/rock/アヴリル１.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/アヴリル１.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/mode/skórzane_spodnie-201x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/skórzane_spodnie-201x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/2016新しい女性ヒップホップパンツダンス落書き春と夏緩いジャズハーレムスウェットパンツ用女の子ズボン.jpg

======================================================================
Running trial selected_config_30_seed on seed 378
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_378
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0621 val_loss=1.1148 val_macro_f1=0.6735 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.2887 val_loss=0.7595 val_macro_f1=0.7514 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0454 val_loss=0.6819 val_macro_f1=0.7579 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.8901 val_loss=0.6708 val_macro_f1=0.7807 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7707 val_loss=0.5677 val_macro_f1=0.8082 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7010 val_loss=0.6008 val_macro_f1=0.8029 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6343 val_loss=0.5640 val_macro_f1=0.8182 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5772 val_loss=0.5859 val_macro_f1=0.8228 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5295 val_loss=0.5771 val_macro_f1=0.8305 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4738 val_loss=0.5950 val_macro_f1=0.8251 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4439 val_loss=0.6064 val_macro_f1=0.8125 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4064 val_loss=0.6158 val_macro_f1=0.8252 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3668 val_loss=0.6055 val_macro_f1=0.8279 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3619 val_loss=0.5983 val_macro_f1=0.8394 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3301 val_loss=0.6166 val_macro_f1=0.8311 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3102 val_loss=0.6081 val_macro_f1=0.8323 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3007 val_loss=0.6057 val_macro_f1=0.8394 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2912 val_loss=0.6047 val_macro_f1=0.8390 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2892 val_loss=0.6037 val_macro_f1=0.8396 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.2936 val_loss=0.6040 val_macro_f1=0.8390 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_378_results.json
Best val macro F1: 0.8396
Test macro F1: 0.8278
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[29/30] Running seed 380

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9237 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+%289%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Model+Street+Style+Paris+Couture+Fashion+Week+SS+2017+(9).jpg
    raw=dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/新しいファッション女性ジャズはハーレムトップ緩い超-短いt-シャツネオンいたずら書きヒップホップダンス衣装t-シャツ.jpg
    raw=dataset/mode/Botas+MODA+%281%29.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Botas+MODA+(1).jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
Dataset initialized with 1981 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/mode/3607541_ö_015.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/3607541_ö_015.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
Dataset initialized with 1978 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    raw=dataset/retro/レトロロングコーデ-225x300.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/レトロロングコーデ-225x300.jpg
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop-bts.jpg
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg

======================================================================
Running trial selected_config_30_seed on seed 380
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_380
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.1102 val_loss=1.1346 val_macro_f1=0.6603 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3299 val_loss=0.8072 val_macro_f1=0.7344 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0464 val_loss=0.6473 val_macro_f1=0.7802 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9090 val_loss=0.6159 val_macro_f1=0.7921 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.7901 val_loss=0.6208 val_macro_f1=0.8021 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7357 val_loss=0.5919 val_macro_f1=0.8214 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6384 val_loss=0.6124 val_macro_f1=0.8025 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5775 val_loss=0.6160 val_macro_f1=0.8105 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5402 val_loss=0.6070 val_macro_f1=0.8113 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.4976 val_loss=0.5856 val_macro_f1=0.8147 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4506 val_loss=0.5810 val_macro_f1=0.8280 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4092 val_loss=0.6320 val_macro_f1=0.8238 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3904 val_loss=0.6056 val_macro_f1=0.8317 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3681 val_loss=0.6062 val_macro_f1=0.8288 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3394 val_loss=0.6041 val_macro_f1=0.8343 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3196 val_loss=0.6161 val_macro_f1=0.8294 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3084 val_loss=0.6077 val_macro_f1=0.8345 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.3024 val_loss=0.6116 val_macro_f1=0.8337 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.2948 val_loss=0.6060 val_macro_f1=0.8362 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.3034 val_loss=0.6061 val_macro_f1=0.8336 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_380_results.json
Best val macro F1: 0.8362
Test macro F1: 0.8378
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'
[30/30] Running seed 457

=== Trainable parameter summary ===
Trial: selected_config_30_seed
Model: vit_base_patch16_224
Trainable parameters: 86030222
   backbone.cls_token
   backbone.pos_embed
   backbone.patch_embed.proj.weight
   backbone.patch_embed.proj.bias
   backbone.blocks.0.norm1.weight
   backbone.blocks.0.norm1.bias
   backbone.blocks.0.attn.qkv.weight
   backbone.blocks.0.attn.qkv.bias
   backbone.blocks.0.attn.proj.weight
   backbone.blocks.0.attn.proj.bias
   backbone.blocks.0.norm2.weight
   backbone.blocks.0.norm2.bias
   backbone.blocks.0.mlp.fc1.weight
   backbone.blocks.0.mlp.fc1.bias
   backbone.blocks.0.mlp.fc2.weight
   backbone.blocks.0.mlp.fc2.bias
   backbone.blocks.1.norm1.weight
   backbone.blocks.1.norm1.bias
   backbone.blocks.1.attn.qkv.weight
   backbone.blocks.1.attn.qkv.bias
  ...
Dataset initialized with 9239 valid samples (out of 9261)
  Missing image examples:
    raw=dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/ヒップホップtシャツヒップホップレディース服ヒップホップtシャツ女性服oネックトップスティーtシャツヒップホップ服kpop.jpg
    raw=dataset/rock/outfit-latzrock-stradivarius-schwarz-wei%C3%9Fer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/rock/outfit-latzrock-stradivarius-schwarz-weißer-rollkragenpullover-osprey-tasche-dr-martens-overknee-strumpfhosen66.JPG
    raw=dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/street/最も人気2016女性服ファッション-エレガント-な特別な日ゴールデン半袖スパンコール緩い-ミニ-ドレス女の子ヒップ-ホップ.jpg
    raw=dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/2016ファッションプリンセスレースコスプレ傘アーチ型ブランド傘ビニール紫外線太陽の傘創造傘女性ロリータスタイル.jpg
    raw=dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ファッションヴィンテージオードリー-ヘップバーンドレスレトロ50-sドレス50-sスイングドレスvestidos-femininos-olオフィスドレス.jpg
Dataset initialized with 1976 valid samples (out of 1984)
  Missing image examples:
    raw=dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%255B1%255D.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/TB2uGrpcFXXXXbUXXXXXXXXXXXX-1992797956_thumb%5B1%5D.jpg
    raw=dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ピンク岬スウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/送料無料綿ブルーケープスウィートロリータドレスコスプレ衣装.jpg
    raw=dataset/retro/ガーリーワンピースファッションコーデ.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/retro/ガーリーワンピースファッションコーデ.jpg
    raw=dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/140207Used-MIX3月号P59着こなしガイドmooi.jpg
Dataset initialized with 1981 valid samples (out of 1985)
  Missing image examples:
    raw=dataset/mode/Fall%2B2016%2BModels%2BlQu00JFpMmNx.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/mode/Fall+2016+Models+lQu00JFpMmNx.jpg
    raw=dataset/natural/ストライプ白ガウチョパンツ.png
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/ストライプ白ガウチョパンツ.png
    raw=dataset/natural/i=%2F%2Fs.eximg.jp%2Fexnews%2Ffeed%2FFolk%2FFolk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/natural/i=/s.eximg.jp/exnews/feed/Folk/Folk_435866_503d_7.jpg.jpg,qualit70,type=.jpg
    raw=dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg
    resolved=/home/ding-zhang/Dongmei/DATA255/Project/data/raw dataset/lolita/ロングスリーブアリスウサギ刺繍ウールドレススウィートロリータコートロリータコートゴシックロリータウール4xl-5xl-6-xlcoat.jpg

======================================================================
Running trial selected_config_30_seed on seed 457
Loaded CSVs from /home/ding-zhang/Dongmei/DATA255/Project/data/splits/seed_457
Train/Val/Test: 9261 / 1984 / 1985
======================================================================

Epoch 1/20: train_loss=2.0769 val_loss=1.1215 val_macro_f1=0.6711 backbone_lr=2.00e-05 head_lr=1.00e-04

Epoch 2/20: train_loss=1.3262 val_loss=0.7773 val_macro_f1=0.7537 backbone_lr=1.99e-05 head_lr=9.94e-05

Epoch 3/20: train_loss=1.0465 val_loss=0.6668 val_macro_f1=0.7796 backbone_lr=1.95e-05 head_lr=9.76e-05

Epoch 4/20: train_loss=0.9045 val_loss=0.5954 val_macro_f1=0.8031 backbone_lr=1.89e-05 head_lr=9.46e-05

Epoch 5/20: train_loss=0.8012 val_loss=0.6020 val_macro_f1=0.8081 backbone_lr=1.81e-05 head_lr=9.05e-05

Epoch 6/20: train_loss=0.7301 val_loss=0.5955 val_macro_f1=0.8131 backbone_lr=1.71e-05 head_lr=8.54e-05

Epoch 7/20: train_loss=0.6451 val_loss=0.5985 val_macro_f1=0.8112 backbone_lr=1.59e-05 head_lr=7.94e-05

Epoch 8/20: train_loss=0.5852 val_loss=0.6090 val_macro_f1=0.8117 backbone_lr=1.45e-05 head_lr=7.27e-05

Epoch 9/20: train_loss=0.5380 val_loss=0.5848 val_macro_f1=0.8207 backbone_lr=1.31e-05 head_lr=6.55e-05

Epoch 10/20: train_loss=0.5335 val_loss=0.5845 val_macro_f1=0.8322 backbone_lr=1.16e-05 head_lr=5.78e-05

Epoch 11/20: train_loss=0.4713 val_loss=0.5936 val_macro_f1=0.8301 backbone_lr=1.00e-05 head_lr=5.00e-05

Epoch 12/20: train_loss=0.4248 val_loss=0.5958 val_macro_f1=0.8299 backbone_lr=8.44e-06 head_lr=4.22e-05

Epoch 13/20: train_loss=0.3844 val_loss=0.6194 val_macro_f1=0.8227 backbone_lr=6.91e-06 head_lr=3.45e-05

Epoch 14/20: train_loss=0.3655 val_loss=0.6011 val_macro_f1=0.8289 backbone_lr=5.46e-06 head_lr=2.73e-05

Epoch 15/20: train_loss=0.3476 val_loss=0.6101 val_macro_f1=0.8339 backbone_lr=4.12e-06 head_lr=2.06e-05

Epoch 16/20: train_loss=0.3340 val_loss=0.6081 val_macro_f1=0.8341 backbone_lr=2.93e-06 head_lr=1.46e-05

Epoch 17/20: train_loss=0.3188 val_loss=0.6046 val_macro_f1=0.8369 backbone_lr=1.91e-06 head_lr=9.55e-06

Epoch 18/20: train_loss=0.2968 val_loss=0.6095 val_macro_f1=0.8344 backbone_lr=1.09e-06 head_lr=5.45e-06

Epoch 19/20: train_loss=0.3016 val_loss=0.6057 val_macro_f1=0.8369 backbone_lr=4.89e-07 head_lr=2.45e-06

Epoch 20/20: train_loss=0.3154 val_loss=0.6067 val_macro_f1=0.8367 backbone_lr=1.23e-07 head_lr=6.16e-07

Saved result JSON to /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments/seed_457_results.json
Best val macro F1: 0.8369
Test macro F1: 0.8453
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx: No module named 'openpyxl'
Could not save Excel file /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx: No module named 'openpyxl'

Robustness run complete.
Successful seeds: 30 / 30
Failed seeds: 0
Results saved under: /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness

Per-seed summary:

,Seed,Best_Epoch,Early_Stopped,Best_Val_Macro_F1,Best_Val_Accuracy,Val_Loss_At_Best_Epoch,Min_Val_Loss,Test_Macro_F1,Test_Accuracy,Test_Macro_Precision,Test_Macro_Recall,Overfitting,Training_Time_Min,Trainable_Params
0,13,18,False,0.836745,0.836107,0.587575,0.577258,0.830296,0.829207,0.829806,0.831840,False,11.539363,86030222
1,14,18,False,0.849534,0.849066,0.553735,0.532104,0.828619,0.827952,0.829128,0.829685,False,11.573012,86030222
2,16,16,False,0.837342,0.837045,0.605519,0.566015,0.832199,0.831988,0.834060,0.833614,False,11.576890,86030222
3,17,16,False,0.835902,0.835693,0.626357,0.597994,0.844965,0.842850,0.846412,0.845060,False,11.574070,86030222
4,45,19,False,0.849329,0.847672,0.578153,0.517913,0.834327,0.832154,0.837417,0.832206,False,11.583092,86030222
5,48,16,False,0.841979,0.841494,0.544761,0.534467,0.830720,0.830808,0.831610,0.832502,False,11.575246,86030222
6,53,19,False,0.832973,0.831903,0.609690,0.573447,0.830744,0.830551,0.833019,0.830217,False,11.573763,86030222
7,58,18,False,0.831744,0.829798,0.625315,0.573256,0.850938,0.850354,0.851129,0.851638,False,11.585115,86030222
8,72,15,True,0.842807,0.840989,0.584166,0.543836,0.830039,0.829047,0.832506,0.830125,False,11.558378,86030222
9,102,18,False,0.849117,0.846970,0.555111,0.516313,0.830156,0.829047,0.831107,0.830663,False,11.568828,86030222
10,112,7,True,0.822618,0.822042,0.538973,0.538973,0.816549,0.815524,0.818176,0.819693,True,6.940207,86030222
11,115,15,True,0.841042,0.840748,0.559078,0.549017,0.831622,0.831228,0.831970,0.832814,False,11.573325,86030222
12,120,19,False,0.847594,0.844793,0.565745,0.543626,0.834861,0.833249,0.837031,0.833975,False,11.577488,86030222
13,126,18,False,0.833616,0.832323,0.620451,0.589982,0.833470,0.831313,0.836563,0.832215,False,11.573898,86030222
14,141,13,True,0.831244,0.830808,0.612292,0.594332,0.838231,0.838057,0.838141,0.839822,False,10.414513,86030222
15,215,20,False,0.839582,0.839232,0.608492,0.575394,0.839328,0.838628,0.839659,0.839605,False,11.575803,86030222
16,217,18,False,0.841169,0.840404,0.576405,0.547736,0.835653,0.834427,0.836118,0.836291,False,11.574240,86030222
17,259,19,False,0.852613,0.850581,0.548445,0.514387,0.833773,0.832323,0.834130,0.833865,False,11.581486,86030222
18,280,17,False,0.831701,0.829207,0.628057,0.589113,0.824147,0.822312,0.826891,0.823110,False,11.566771,86030222
19,288,15,True,0.836249,0.835270,0.623715,0.585001,0.831912,0.829626,0.835263,0.831435,False,11.572238,86030222
20,303,18,False,0.835134,0.833838,0.627070,0.569107,0.836988,0.836281,0.838728,0.836487,False,11.580655,86030222
21,309,12,True,0.839321,0.838220,0.580212,0.547242,0.832727,0.831988,0.836579,0.831741,False,9.830532,86030222
22,328,17,False,0.840188,0.838302,0.596065,0.525475,0.838650,0.837797,0.839453,0.840556,False,11.569931,86030222
23,333,17,False,0.844355,0.842929,0.592969,0.575125,0.824975,0.823470,0.828397,0.824213,False,11.583522,86030222
24,347,19,False,0.847936,0.845376,0.594158,0.548555,0.837761,0.836704,0.838084,0.838149,False,11.587579,86030222
25,360,20,False,0.837442,0.835941,0.598204,0.578643,0.828545,0.827865,0.828980,0.828721,False,11.568147,86030222
26,367,20,False,0.846998,0.845028,0.547547,0.519810,0.840953,0.838726,0.843761,0.840087,False,11.581979,86030222
27,378,19,False,0.839631,0.838302,0.603669,0.563953,0.827776,0.826263,0.831859,0.825369,False,11.577256,86030222
28,380,19,False,0.836203,0.833922,0.606017,0.580961,0.837783,0.837715,0.838003,0.838496,False,11.575939,86030222
29,457,19,False,0.836936,0.836032,0.605682,0.584480,0.845332,0.845533,0.845731,0.846325,False,11.582146,86030222

High-level robustness summary:
{
  "summary_statistics": [
    {
      "metric": "Test Macro F1",
      "mean": 0.8338012818611276,
      "std": 0.0067152681023404884,
      "min": 0.8165493988872169,
      "max": 0.850937547924178,
      "median": 0.8330982232095675,
      "q25": 0.8301907680641386,
      "q75": 0.8377776359357358,
      "cv_percent": 0.8053799206630314,
      "ci_95_lower": 0.8312508928071882,
      "ci_95_upper": 0.8363516709150669,
      "n": 30
    },
    {
      "metric": "Test Accuracy",
      "mean": 0.8327661482123742,
      "std": 0.006831805569979691,
      "min": 0.8155241935483871,
      "max": 0.8503538928210314,
      "median": 0.8319878910191726,
      "q25": 0.8290868414876629,
      "q75": 0.8374620829120324,
      "cv_percent": 0.820375033812905,
      "ci_95_lower": 0.8301714994390444,
      "ci_95_upper": 0.8353607969857039,
      "n": 30
    },
    {
      "metric": "Test Macro Precision",
      "mean": 0.8353236559038245,
      "std": 0.006394707213803825,
      "min": 0.8181760524800745,
      "max": 0.8511289422390816,
      "median": 0.8356904690083198,
      "q25": 0.8316720534114054,
      "q75": 0.8381266095549307,
      "cv_percent": 0.7655364682429254,
      "ci_95_lower": 0.8328950125447384,
      "ci_95_upper": 0.8377522992629106,
      "n": 30
    },
    {
      "metric": "Test Macro Recall",
      "mean": 0.8340173051802762,
      "std": 0.006798515121204491,
      "min": 0.8196930523086354,
      "max": 0.8516379356492152,
      "median": 0.8326579566697828,
      "q25": 0.8303284160330695,
      "q75": 0.8384090729138979,
      "cv_percent": 0.8151527646941288,
      "ci_95_lower": 0.831435299773505,
      "ci_95_upper": 0.8365993105870473,
      "n": 30
    },
    {
      "metric": "Best Val Macro F1",
      "mean": 0.8396347532070927,
      "std": 0.006654153209189352,
      "min": 0.8226175919848316,
      "max": 0.8526130085561837,
      "median": 0.8394515161027576,
      "q25": 0.8359774264030659,
      "q75": 0.8439676634568386,
      "cv_percent": 0.7925056917633483,
      "ci_95_lower": 0.8371075749545912,
      "ci_95_upper": 0.8421619314595942,
      "n": 30
    },
    {
      "metric": "Best Val Accuracy",
      "mean": 0.83833457347244,
      "std": 0.006433064466334975,
      "min": 0.8220424671385238,
      "max": 0.8505805148914689,
      "median": 0.838261298742969,
      "q25": 0.8342592807517807,
      "q75": 0.8425705184097411,
      "cv_percent": 0.7673624194799429,
      "ci_95_lower": 0.8358913624273727,
      "ci_95_upper": 0.8407777845175073,
      "n": 30
    },
    {
      "metric": "Val Loss At Best Epoch",
      "mean": 0.5901208410820654,
      "std": 0.027361248865025112,
      "min": 0.5389725921615478,
      "max": 0.6280565665614221,
      "median": 0.595111470308996,
      "q25": 0.5684100123903444,
      "q75": 0.6093908696165008,
      "cv_percent": 4.636550170784446,
      "ci_95_lower": 0.5797293230452579,
      "ci_95_upper": 0.6005123591188729,
      "n": 30
    },
    {
      "metric": "Min Val Loss",
      "mean": 0.5584504726272758,
      "std": 0.025230182258275197,
      "min": 0.5143868432890984,
      "max": 0.5979937834124411,
      "median": 0.5649840274164754,
      "q25": 0.5401358672928426,
      "q75": 0.578296717136137,
      "cv_percent": 4.517890752169615,
      "ci_95_lower": 0.5488683115460269,
      "ci_95_upper": 0.5680326337085246,
      "n": 30
    },
    {
      "metric": "Training Time (min)",
      "mean": 11.323180426094268,
      "std": 0.8938894070617491,
      "min": 6.940206583340963,
      "max": 11.587578805287679,
      "median": 11.574155193567275,
      "q25": 11.569104008873303,
      "q75": 11.579863197604816,
      "cv_percent": 7.894331569616087,
      "ci_95_lower": 10.983690516762428,
      "ci_95_upper": 11.662670335426109,
      "n": 30
    }
  ],
  "overfitting_count": 1,
  "overfitting_percentage": 3.3333333333333335,
  "total_experiments": 30
}

Key files:
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/overall_metrics_statistics.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/overall_metrics_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_statistics.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_f1_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_precision_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_recall_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_accuracy_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/comprehensive_report_overall.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/comprehensive_report_per_class.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/statistical_analysis.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments_summary.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/comparison_plots/robustness_analysis.png
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/comparison_plots/learning_curves_overlay.png
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/per_class_analysis_summary.png

In [21]:

print(f"Successful seeds: {len(all_results)} / {len(ROBUSTNESS_SEEDS)}")
print(f"Failed seeds: {len(failed_seeds)}")
print(f"Results saved under: {ROBUSTNESS_OUTPUT_ROOT}")
summary_csv = ROBUSTNESS_METRICS_DIR / "summary_table.csv"
overall_json = ROBUSTNESS_METRICS_DIR / "statistical_analysis.json"
experiments_summary_json = ROBUSTNESS_METRICS_DIR / "experiments_summary.json"
if summary_csv.exists():
    print("\nPer-seed summary:")
    display(pd.read_csv(summary_csv).sort_values("Seed"))
if overall_json.exists():
    print("\nHigh-level robustness summary:")
    with open(overall_json, "r", encoding="utf-8") as f:
        print(json.dumps(json.load(f), indent=2))
print("\nKey files:")
print("  ", ROBUSTNESS_METRICS_DIR / "experiments")
print("  ", ROBUSTNESS_METRICS_DIR / "summary_table.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "summary_table.xlsx")
print("  ", ROBUSTNESS_METRICS_DIR / "overall_metrics_statistics.json")
print("  ", ROBUSTNESS_METRICS_DIR / "overall_metrics_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_statistics.json")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_summary.xlsx")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_f1_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_precision_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_recall_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "per_class_metrics_accuracy_summary.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "comprehensive_report_overall.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "comprehensive_report_per_class.csv")
print("  ", ROBUSTNESS_METRICS_DIR / "statistical_analysis.json")
print("  ", experiments_summary_json)
print("  ", ROBUSTNESS_OUTPUT_ROOT / "comparison_plots" / "robustness_analysis.png")
print("  ", ROBUSTNESS_OUTPUT_ROOT / "comparison_plots" / "learning_curves_overlay.png")
print("  ", ROBUSTNESS_OUTPUT_ROOT / "per_class_analysis_summary.png")

Successful seeds: 30 / 30
Failed seeds: 0
Results saved under: /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness

Per-seed summary:

,Seed,Best_Epoch,Early_Stopped,Best_Val_Macro_F1,Best_Val_Accuracy,Val_Loss_At_Best_Epoch,Min_Val_Loss,Test_Macro_F1,Test_Accuracy,Test_Macro_Precision,Test_Macro_Recall,Overfitting,Training_Time_Min,Trainable_Params
0,13,18,False,0.836745,0.836107,0.587575,0.577258,0.830296,0.829207,0.829806,0.831840,False,11.539363,86030222
1,14,18,False,0.849534,0.849066,0.553735,0.532104,0.828619,0.827952,0.829128,0.829685,False,11.573012,86030222
2,16,16,False,0.837342,0.837045,0.605519,0.566015,0.832199,0.831988,0.834060,0.833614,False,11.576890,86030222
3,17,16,False,0.835902,0.835693,0.626357,0.597994,0.844965,0.842850,0.846412,0.845060,False,11.574070,86030222
4,45,19,False,0.849329,0.847672,0.578153,0.517913,0.834327,0.832154,0.837417,0.832206,False,11.583092,86030222
5,48,16,False,0.841979,0.841494,0.544761,0.534467,0.830720,0.830808,0.831610,0.832502,False,11.575246,86030222
6,53,19,False,0.832973,0.831903,0.609690,0.573447,0.830744,0.830551,0.833019,0.830217,False,11.573763,86030222
7,58,18,False,0.831744,0.829798,0.625315,0.573256,0.850938,0.850354,0.851129,0.851638,False,11.585115,86030222
8,72,15,True,0.842807,0.840989,0.584166,0.543836,0.830039,0.829047,0.832506,0.830125,False,11.558378,86030222
9,102,18,False,0.849117,0.846970,0.555111,0.516313,0.830156,0.829047,0.831107,0.830663,False,11.568828,86030222
10,112,7,True,0.822618,0.822042,0.538973,0.538973,0.816549,0.815524,0.818176,0.819693,True,6.940207,86030222
11,115,15,True,0.841042,0.840748,0.559078,0.549017,0.831622,0.831228,0.831970,0.832814,False,11.573325,86030222
12,120,19,False,0.847594,0.844793,0.565745,0.543626,0.834861,0.833249,0.837031,0.833975,False,11.577488,86030222
13,126,18,False,0.833616,0.832323,0.620451,0.589982,0.833470,0.831313,0.836563,0.832215,False,11.573898,86030222
14,141,13,True,0.831244,0.830808,0.612292,0.594332,0.838231,0.838057,0.838141,0.839822,False,10.414513,86030222
15,215,20,False,0.839582,0.839232,0.608492,0.575394,0.839328,0.838628,0.839659,0.839605,False,11.575803,86030222
16,217,18,False,0.841169,0.840404,0.576405,0.547736,0.835653,0.834427,0.836118,0.836291,False,11.574240,86030222
17,259,19,False,0.852613,0.850581,0.548445,0.514387,0.833773,0.832323,0.834130,0.833865,False,11.581486,86030222
18,280,17,False,0.831701,0.829207,0.628057,0.589113,0.824147,0.822312,0.826891,0.823110,False,11.566771,86030222
19,288,15,True,0.836249,0.835270,0.623715,0.585001,0.831912,0.829626,0.835263,0.831435,False,11.572238,86030222
20,303,18,False,0.835134,0.833838,0.627070,0.569107,0.836988,0.836281,0.838728,0.836487,False,11.580655,86030222
21,309,12,True,0.839321,0.838220,0.580212,0.547242,0.832727,0.831988,0.836579,0.831741,False,9.830532,86030222
22,328,17,False,0.840188,0.838302,0.596065,0.525475,0.838650,0.837797,0.839453,0.840556,False,11.569931,86030222
23,333,17,False,0.844355,0.842929,0.592969,0.575125,0.824975,0.823470,0.828397,0.824213,False,11.583522,86030222
24,347,19,False,0.847936,0.845376,0.594158,0.548555,0.837761,0.836704,0.838084,0.838149,False,11.587579,86030222
25,360,20,False,0.837442,0.835941,0.598204,0.578643,0.828545,0.827865,0.828980,0.828721,False,11.568147,86030222
26,367,20,False,0.846998,0.845028,0.547547,0.519810,0.840953,0.838726,0.843761,0.840087,False,11.581979,86030222
27,378,19,False,0.839631,0.838302,0.603669,0.563953,0.827776,0.826263,0.831859,0.825369,False,11.577256,86030222
28,380,19,False,0.836203,0.833922,0.606017,0.580961,0.837783,0.837715,0.838003,0.838496,False,11.575939,86030222
29,457,19,False,0.836936,0.836032,0.605682,0.584480,0.845332,0.845533,0.845731,0.846325,False,11.582146,86030222

High-level robustness summary:
{
  "summary_statistics": [
    {
      "metric": "Test Macro F1",
      "mean": 0.8338012818611276,
      "std": 0.0067152681023404884,
      "min": 0.8165493988872169,
      "max": 0.850937547924178,
      "median": 0.8330982232095675,
      "q25": 0.8301907680641386,
      "q75": 0.8377776359357358,
      "cv_percent": 0.8053799206630314,
      "ci_95_lower": 0.8312508928071882,
      "ci_95_upper": 0.8363516709150669,
      "n": 30
    },
    {
      "metric": "Test Accuracy",
      "mean": 0.8327661482123742,
      "std": 0.006831805569979691,
      "min": 0.8155241935483871,
      "max": 0.8503538928210314,
      "median": 0.8319878910191726,
      "q25": 0.8290868414876629,
      "q75": 0.8374620829120324,
      "cv_percent": 0.820375033812905,
      "ci_95_lower": 0.8301714994390444,
      "ci_95_upper": 0.8353607969857039,
      "n": 30
    },
    {
      "metric": "Test Macro Precision",
      "mean": 0.8353236559038245,
      "std": 0.006394707213803825,
      "min": 0.8181760524800745,
      "max": 0.8511289422390816,
      "median": 0.8356904690083198,
      "q25": 0.8316720534114054,
      "q75": 0.8381266095549307,
      "cv_percent": 0.7655364682429254,
      "ci_95_lower": 0.8328950125447384,
      "ci_95_upper": 0.8377522992629106,
      "n": 30
    },
    {
      "metric": "Test Macro Recall",
      "mean": 0.8340173051802762,
      "std": 0.006798515121204491,
      "min": 0.8196930523086354,
      "max": 0.8516379356492152,
      "median": 0.8326579566697828,
      "q25": 0.8303284160330695,
      "q75": 0.8384090729138979,
      "cv_percent": 0.8151527646941288,
      "ci_95_lower": 0.831435299773505,
      "ci_95_upper": 0.8365993105870473,
      "n": 30
    },
    {
      "metric": "Best Val Macro F1",
      "mean": 0.8396347532070927,
      "std": 0.006654153209189352,
      "min": 0.8226175919848316,
      "max": 0.8526130085561837,
      "median": 0.8394515161027576,
      "q25": 0.8359774264030659,
      "q75": 0.8439676634568386,
      "cv_percent": 0.7925056917633483,
      "ci_95_lower": 0.8371075749545912,
      "ci_95_upper": 0.8421619314595942,
      "n": 30
    },
    {
      "metric": "Best Val Accuracy",
      "mean": 0.83833457347244,
      "std": 0.006433064466334975,
      "min": 0.8220424671385238,
      "max": 0.8505805148914689,
      "median": 0.838261298742969,
      "q25": 0.8342592807517807,
      "q75": 0.8425705184097411,
      "cv_percent": 0.7673624194799429,
      "ci_95_lower": 0.8358913624273727,
      "ci_95_upper": 0.8407777845175073,
      "n": 30
    },
    {
      "metric": "Val Loss At Best Epoch",
      "mean": 0.5901208410820654,
      "std": 0.027361248865025112,
      "min": 0.5389725921615478,
      "max": 0.6280565665614221,
      "median": 0.595111470308996,
      "q25": 0.5684100123903444,
      "q75": 0.6093908696165008,
      "cv_percent": 4.636550170784446,
      "ci_95_lower": 0.5797293230452579,
      "ci_95_upper": 0.6005123591188729,
      "n": 30
    },
    {
      "metric": "Min Val Loss",
      "mean": 0.5584504726272758,
      "std": 0.025230182258275197,
      "min": 0.5143868432890984,
      "max": 0.5979937834124411,
      "median": 0.5649840274164754,
      "q25": 0.5401358672928426,
      "q75": 0.578296717136137,
      "cv_percent": 4.517890752169615,
      "ci_95_lower": 0.5488683115460269,
      "ci_95_upper": 0.5680326337085246,
      "n": 30
    },
    {
      "metric": "Training Time (min)",
      "mean": 11.323180426094268,
      "std": 0.8938894070617491,
      "min": 6.940206583340963,
      "max": 11.587578805287679,
      "median": 11.574155193567275,
      "q25": 11.569104008873303,
      "q75": 11.579863197604816,
      "cv_percent": 7.894331569616087,
      "ci_95_lower": 10.983690516762428,
      "ci_95_upper": 11.662670335426109,
      "n": 30
    }
  ],
  "overfitting_count": 1,
  "overfitting_percentage": 3.3333333333333335,
  "total_experiments": 30
}

Key files:
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/summary_table.xlsx
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/overall_metrics_statistics.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/overall_metrics_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_statistics.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_summary.xlsx
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_f1_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_precision_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_recall_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/per_class_metrics_accuracy_summary.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/comprehensive_report_overall.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/comprehensive_report_per_class.csv
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/statistical_analysis.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/metrics/experiments_summary.json
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/comparison_plots/robustness_analysis.png
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/comparison_plots/learning_curves_overlay.png
   /home/ding-zhang/Dongmei/DATA255/Project/experiments/imageonly_vit_b16_robustness/per_class_analysis_summary.png